apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sylva-system

configurations:
- configuration.yaml

resources:
- sylva-units-release.yaml
- namespace.yaml

buildMetadata:
- originAnnotations

# Generate empty secret & configmap to let kustomize overlays & descendants add data with 'behavior: merge'

configMapGenerator:
- name: sylva-units-values

secretGenerator:
- name: sylva-units-secrets
