apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-os-images-info-capm3
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  generateExisting: true
  rules:
  - name: clone-os-images-info-capm3
    skipBackgroundRequests: false
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              sylva-project.org/workload-cluster: ""
    generate:
      kind: ConfigMap
      apiVersion: v1
      name: kyverno-cloned-os-image-server-images
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        name: capm3-os-image-server-os-images
        namespace: sylva-system
