apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      externalLabels:
        cluster: ${CLUSTER_NAME}  # required for multi-cluster dashboards
      remoteWrite:
        - url: ${THANOS_URL}
          basicAuth:
            username:
              name: ${SECRET_NAME}
              key: username
            password:
              name: ${SECRET_NAME}
              key: password
          tlsConfig:
            insecureSkipVerify: true
          queue_config:
            batch_send_deadline: 5s
            min_backoff: 1s
            max_backoff: 30s
