---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${SERVICE}-tls
  namespace: thanos
spec:
  secretName: ${SERVICE}-tls
  issuerRef:
    name: certificate-issuer
    kind: ClusterIssuer
  commonName: ${THANOS_DNS}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  emailAddresses:
  - surname.name@sylva.org
  subject:
    organizations:
    - Sylva
    countries:
    - eu
    organizationalUnits:
    - DEV
  dnsNames:
  - ${THANOS_DNS}
  - ${THANOS_STOREGATEWAY_DNS}
  - ${THANOS_RECEIVE_DNS}
  - ${THANOS_QUERY_DNS}
  - localhost
  ipAddresses:
  - 127.0.0.1
