---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: thanos-minio-user
   namespace: sylva-system
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   target:
      creationPolicy: Orphan
      name: thanos-minio-user
      template:
         type: Opaque
         data:
            CONSOLE_ACCESS_KEY: minio-monitoring-user
            CONSOLE_SECRET_KEY: "{{ .password | toString }}"
   data:
   - secretKey: password
     remoteRef:
        key: ${SECRET_PATH}/data/minio-monitoring-user-password
        property: password

