apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/OpenNebula/cluster-api-provider-opennebula/releases/download/v0.1.5/infrastructure-components.yaml

labels:
- pairs:
    clusterctl.cluster.x-k8s.io: ""

components:
- ../common-kustomize-components/crd-remove-caBundle
