apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- restart-kyverno-after-capo-crds.yaml
- globalnetworkset-for-capo-management-cluster.yaml
- globalnetworkset-for-capo-workload-clusters.yaml
