---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-kustomization-editor
rules:
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-kustomization-editor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-kustomization-editor
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: workload-clusters-propagate-mgmt-state-settings
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  generateExisting: true
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: reconcile-on-secret-update
    match:
      any:
      - resources:
          kinds:
          - Secret
          names:
          - ca-key-pair
          namespaces:
          - cert-manager
    mutate:
      targets:
      - apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        name: wkld-ds-copy-file
        namespace: kubeadm-capo
      patchStrategicMerge:
        metadata:
          annotations:
            reconcile.fluxcd.io/requestedAt: "{{ time_now_utc() }}"
            kyverno-applied: "true"
        spec:
          postBuild:
            substitute:
              DATA: "Substituted by Kyverno {{ time_now_utc() }}"

