{
 "title": "Pingmesh - Connectivity Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   { "name": "dest_type", "label": "destination Type", "query": "pods, nodes" }
  ]
 },
 "panels": [
  {
   "title": "Current average connectivity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pingmesh_connectivity_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current minimum connectivity",
   "type": "stat",
   "description": "Connectivity of the node with worst connectivity",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(pingmesh_connectivity_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connectivity Ratio - pod to pod",
   "type": "timeseries",
   "description": "For each node, indicates the ratio of node for which a pod-to-pod connectivity test succeeds.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(pingmesh_connectivity_ratio{pingmesh_dest_type=\"pods\"}) without(pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}