apiVersion: v1
kind: ServiceAccount
metadata:
  name: pingmesh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pingmesh
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list","get","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pingmesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pingmesh
subjects:
  - kind: ServiceAccount
    namespace: pingmesh
    name: pingmesh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pingmesh
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","get","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pingmesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pingmesh
subjects:
  - kind: ServiceAccount
    namespace: pingmesh
    name: pingmesh
