apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restart-minio-monitoring-tenant-on-cert-renewal
  namespace: minio-monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/description: >-
      This policy monitors MinIO-monitoring tenant certificate secrets and will update annotations
      to trigger pod rollouts when certificates are renewed.
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: minio-monitoring-tenant-restart
    match:
      any:
      - resources:
          kinds:
          - Secret
          names:
          - minio-monitoring-internal-tls
    mutate:
      targets:
        - apiVersion: minio.min.io/v2
          kind: Tenant
          name: monitoring
          namespace: minio-monitoring
      patchStrategicMerge:
        spec:
          poolsMetadata:
            annotations:
              minio-monitoring/triggerrestart: "{{request.object.metadata.resourceVersion}}"
