apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/releases/download/v2.5.1/install.yaml
components:
  - ../components/common
  - ../components/extra-config
  - ../components/persistant-sources

patches:
- target:
    labelSelector: app.kubernetes.io/component=image-automation-controller
  patch: |-
    $patch: delete
    kind: _unused_
    metadata:
      name: _unused_
- target:
    labelSelector: app.kubernetes.io/component=image-reflector-controller
  patch: |-
    $patch: delete
    kind: _unused_
    metadata:
      name: _unused_
- target:
    kind: Deployment
    name: helm-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 2Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 1Gi
# workaround for https://gitlab.com/sylva-projects/sylva-core/-/issues/2160
- target:
    kind: Deployment
    name: source-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/fluxcd/source-controller:v1.4.1

- target:
    kind: Deployment
    name: kustomize-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 1Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 512Mi

- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/component=kustomize-controller
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent-ssa=10
