apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Deletes a pod belonging to a deployment/statefulset/daemonset
kind: ChaosExperiment
metadata:
  name: '${SERVICE_NAME}'
  namespace: '${NAMESPACE}'
  labels:
    name: k8s-api-response
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: 3.4.0
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "apps"
          - "apps.openshift.io"
          - "argoproj.io"
          - "batch"
          - "litmuschaos.io"
        resources:
          - "deployments"
          - "jobs"
          - "pods"
          - "pods/log"
          - "replicationcontrollers"
          - "deployments"
          - "statefulsets"
          - "daemonsets"
          - "replicasets"
          - "deploymentconfigs"
          - "rollouts"
          - "pods/exec"
          - "events"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
          - "deletecollection"
    image: 'nikhilsethi31/go-runner:combined-image-v1.0.6'
    imagePullPolicy: 'IfNotPresent'
    args:
    - -c
    - ./experiments -name k8s-api-response
    command:
    - /bin/bash
    env:

    - name: TOTAL_CHAOS_DURATION
      value: '${TOTAL_CHAOS_DURATION}'

    # Period to wait before and after injection of chaos in sec

    - name: RAMP_TIME
      value: ''

    - name: CHAOS_INTERVAL
      value: '${CHAOS_INTERVAL}'

    # pod failures without '--force' & default terminationGracePeriodSeconds
    - name: FORCE
      value: 'false'

    labels:
      name: k8s-api-response
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: 3.4.0
