apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - patch-bond-policy.yaml
  - bmh-interface-mappings.yaml
  - bmh-disable-automatedcleaningmode.yaml

components:
  # the exclude-kube-system component will patch Policies and ClusterPolicies
  # having the sylva.org/kyverno-exclude-kube-system=add-matchCondition annotation:
  - ../exclude-kube-system
