apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |
      - op: add
        path: /spec/bootstrap
        value:
          initdb:
            import:
              type: microservice
              databases:
                - harbor
              source:
                externalCluster: harbor-old-db
      - op: add
        path: /spec/externalClusters
        value:
          - name: harbor-old-db
            connectionParameters:
              host: harbor-postgres-primary
              user: postgres
              dbname: harbor
            password:
              name: harbor-postgres-secrets
              key: admin-password
    target:
      kind: Cluster
      name: cnpg-harbor
      namespace: harbor
