# This example environment values files will let you build
# a Sylva one-node (1 control-plane) mgmt baremetal cluster

cluster_virtual_ip: 192.168.74.140

cluster:
  capi_providers:
    infra_provider: capm3
    bootstrap_provider: cabpr

  control_plane_replicas: 1
  cluster_services_cidrs:
    - 100.73.0.0/16
  cluster_pods_cidrs:
    - 100.72.0.0/16

  rke2:
    additionalUserData:
      config:
        #cloud-config
        users:
          - name: node-admin
            groups: users
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            lock_passwd: false
            passwd: $6$egxxI7LOEE22NHf2$FwdqMISkY9bLXCtHTb0wk7ZWu1/mATKhLkDBtzzT4dGw6Nw1qjRprlIDioxltzNsHIfpyfd/h6phD66i0lrdu1
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC26LPtszBaiDUleyFv4/CVV8FGJoqg5hoVHQpFDSDGqLH4Ytdua8NYvEgJkO3IGyYXRAr0hRjBvVi9+gSaShpKQvdMtVwiW80y7XkKucfpBve94zfn77jrj1mMoGd5vv0NNIxuyJPhZCliuA396S8td0TRWYB8vN/sfQhS8gbvsMtufdgi/xZjXvyr5zbX8Y1bnJIX6V2SfjFc3dDhpy8NJIDPDs4fbikLPaCGNvyDSPc1xkky9xv0X12PKLzQE/Q6eWxpNlKTXegr8vdelqVJdnjqZFM++7LTyIVg8pxB3zo/OpMFxO82go+xayOxJxg4+LZwrxIHNe6yKU5+wT9wMNxRCJ4MCqqYIVK7phsHohqfLcBn6WgqlJtEwK9iVGj7NjUckA6Nu5J7RtzjkhWatQIzyFHe+tpXkdPd19AAXnuC7MRFqcDvJQfebL8bsgx/wCwKBeq5GR3l770yKGOSpYcYlYBXo4f2KcLS1xkrnbw8iyA4pOrCLk7vMdcPkt4lnLXs3kXqPRVGcy2M9QEOTNNjkZgkhi88ppnPTaGSBSs2gsyvchBMfaGRRDb3dACgFktHEA20WwMuzLHZJFXwQAetjC4U6SGCpmwNu+Zs5lv043qvSB5TX3ZEnY2ax25wdv/EqtdflX9v05vW76eTh3A2BkDq5WqYIMEJXY44vw== root@bastion

  capm3:
    #image_key: ubuntu-jammy-hardened-rke2-1-29-9
    image_key: ubuntu-jammy-plain-rke2-1-29-9
    primary_pool_network: 192.168.74.128
    primary_pool_gateway: 192.168.74.129
    primary_pool_start: 192.168.74.150
    primary_pool_end: 192.168.74.150
    primary_pool_prefix: "26"
    provisioning_pool_network: 192.168.75.64
    provisioning_pool_gateway: 192.168.75.65
    provisioning_pool_start: 192.168.75.70
    provisioning_pool_end: 192.168.75.71
    provisioning_pool_prefix: "26"
    dns_servers:
    - 192.168.74.134

  control_plane:  # tweak network configuration as needed

    capm3:
      hostSelector:  # criteria for matching labels on BareMetalHost objects defined by baremetal_hosts value
        matchLabels:
          cluster-role: control-plane

      provisioning_pool_interface: ens10f1
      primary_pool_interface: ens10f0

    network_interfaces:
      # for CAPM3 folowing are used and mapped to Metal3Data.spec.template.spec.networkData.links
      ens10f0:
        type: phy
      ens10f1:
        type: phy

  baremetal_host_default:
    bmh_spec:
      online: true
      externallyProvisioned: false
      bmc:
        disableCertificateVerification: true
      bootMode: "UEFI"

  baremetal_hosts:  # corresponding credentials need to be set in secrets.yaml

    # this example is based on what worked on an HP Proliant DL360 Gen10
    ranworker1:
      bmh_metadata:
        labels:
          cluster-role: control-plane
      bmh_spec:
        description: my control plane node
        bmc:
          address: "redfish-virtualmedia://192.168.73.25/redfish/v1/Systems/1"   # put the real BMC address here ()
          disableCertificateVerification: true
        bootMACAddress: "b4:96:91:d8:b7:bc"    # put the real address here!
        rootDeviceHints:
          deviceName: /dev/sda


sylva_diskimagebuilder_images:
  ubuntu-jammy-hardened-rke2-1-29-9:
    default_enabled: false
  ubuntu-jammy-plain-rke2-1-29-9: 
    enabled: true

units:
  cabpoa:
    enabled: true
  openshift-assisted-installer:
    enabled: true
  longhorn:
    enabled: false
  minio-monitoring:
    enabled: true
  thanos:
    enabled: true
  capm3:
    enabled: true
  metal3:
    enabled: true
    helmrelease_spec:
      values:
        global:
          # Add console access to IPA - useful for debuging purposes
          ironicKernelParams: 'console=tty1 suse.autologin=tty1'
        metal3-mariadb:
          image:
            repository: registry.opensuse.org/isv/suse/edge/metal3/containers/images/suse/mariadb
  ingress-nginx:
    helmrelease_spec:
      values:
        controller:
          config:
            large-client-header-buffers: "4 16k"

metal3:
  bootstrap_ip: 192.168.74.141

openshift:
  assisted:
    serviceHostname: bm-assisted-service.example.com
    imageHostname: bm-image-service.example.com

proxies:
  # put your own proxy settings here if you need
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

# configure containerd registry mirrors following https://github.com/containerd/containerd/blob/main/docs/hosts.md
# see charts/syla-units/values.yaml for a more detailled example
# registry_mirrors:
#   hosts_config:
#     docker.io:
#     - mirror_url: http://your.mirror/docker
registry_mirrors:
  default_settings:
    skip_verify: true
    override_path: true
  hosts_config:
    docker.io:
      - mirror_url: http://192.168.74.136/v2/docker.io
    gcr.io:
      - mirror_url: http://192.168.74.136/v2/gcr.io
    ghcr.io:
      - mirror_url: http://192.168.74.136/v2/ghcr.io
    registry.gitlab.com:
      - mirror_url: http://192.168.74.136/v2/registry.gitlab.com
    registry.k8s.io:
      - mirror_url: http://192.168.74.136/v2/registry.k8s.io
    quay.io:
      - mirror_url: http://192.168.74.136/v2/quay.io
    registry.opensuse.org:
      - mirror_url: http://192.168.74.136/v2/registry.opensuse.org
    registry.suse.com:
      - mirror_url: http://192.168.74.136/v2/registry.suse.com

# add ntp servers if you need
ntp:
  enabled: true
  servers:
  - 192.168.74.134
  # - 1.2.3.4
  # - 1.2.3.5

