apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disallow-latest-and-main-tag.yaml
  - ensure-force-cluster-policy.yaml
  - ensure-pdb-unhealthypodeviction.yaml
  - block-rke2-uninstall-jobs.yaml
