---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: nfs-ganesha
spec:
  containers:
    - name: my-container
      image: nginx:1.19.6
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: nfs-pvc

