---
apiVersion: v1
kind: Secret
metadata:
  name: vault-k8s-auth-secret
  namespace: vault
  annotations:
    kubernetes.io/service-account.name: vault
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: ext-vault
  namespace: vault
type: Opaque
stringData:
  token: ${EXT_VAULT_TOKEN}
  addr: ${EXT_VAULT_URL}
  path: ${K8S_AUTH_PATH}
