apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: ${USERNAME}-password-${NAMESPACE:-sylva-system}
  namespace: vault
  annotations:
    sylvaproject.org/cluster-secrets: 'true'
spec:
  authentication:
    path: kubernetes
    role: admin
    serviceAccount:
      name: vault
  connection:
    address: https://vault.vault.svc.cluster.local:8200
    tLSConfig:
      skipVerify: true
  type: acl
  policy: |
    path "/sys/policies/password/+/generate" {
      capabilities = ["read"]
    }
    # path "/${CLUSTER_SECRETS_STORE:-cluster-secrets}/data/*" {
    #   capabilities = ["read", "list", "update", "delete"]
    # }
    # path "/${CLUSTER_SECRETS_STORE:-cluster-secrets}/data/${NAMESPACE:-sylva-system}/*" {
    #   capabilities = ["read", "list", "update", "delete"]
    # }
    # path "/${CLUSTER_SECRETS_STORE:-cluster-secrets}/metadata/${NAMESPACE:-sylva-system}/*" {
    #   capabilities = ["read", "list", "update", "delete"]
    # }
    path "/${CLUSTER_SECRETS_STORE:-cluster-secrets}/data/${NAMESPACE:-sylva-system}/${USERNAME}-password" {
      capabilities = ["create", "read", "list", "update", "delete"]
    }
    path "/${CLUSTER_SECRETS_STORE:-cluster-secrets}/metadata/${NAMESPACE:-sylva-system}/${USERNAME}-password" {
      capabilities = ["read", "list", "delete"]
    }
