apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: ${USERNAME}-password
  namespace: ${NAMESPACE:-sylva-system}
  annotations:
    sylvaproject.org/cluster-secrets: 'true'
spec:
  connection:
    tLSConfig:
      skipVerify: true
    address: https://vault.vault.svc.cluster.local:8200
  authentication:
    path: kubernetes
    role: "${USERNAME}-password-${NAMESPACE:-sylva-system}"
    serviceAccount:
      name: "${USERNAME}-password"
  isKVSecretsEngineV2: true
  path: "${CLUSTER_SECRETS_STORE:-cluster-secrets}/data/${NAMESPACE:-sylva-system}"
  secretKey: password
  secretFormat:
    passwordPolicyName: sylva-password-policy
#  kvSecretRetainPolicy: Retain
#  refreshPeriod: "${REFRESH_PERIOD}"