apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: "${USERNAME}-password"
  namespace: "${NAMESPACE:-sylva-system}"
  annotations:
    sylvaproject.org/cluster-secrets: 'true'
spec:
  # refreshPeriod: 1m0s
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: "${USERNAME}-password-${NAMESPACE:-sylva-system}"
        serviceAccount:
          name: "${USERNAME}-password"
      name: d
      path: "${CLUSTER_SECRETS_STORE:-cluster-secrets}/data/${NAMESPACE:-sylva-system}/${USERNAME}-password"
      connection:
        tLSConfig:
          skipVerify: true  # not cool but refering tlsSecret does not work in release v0.8.13 - see https://gitlab.com/sylva-projects/sylva-core/-/issues/261
        address: https://vault.vault.svc.cluster.local:8200
    - authentication:
        path: kubernetes
        role: "${USERNAME}-password-${NAMESPACE:-sylva-system}"
        serviceAccount:
          name: "${USERNAME}-password"
      name: md
      path: "${CLUSTER_SECRETS_STORE:-cluster-secrets}/metadata/${NAMESPACE:-sylva-system}/${USERNAME}-password"
      connection:
        tLSConfig:
          skipVerify: true  # not cool but refering tlsSecret does not work in release v0.8.13 - see https://gitlab.com/sylva-projects/sylva-core/-/issues/261
        address: https://vault.vault.svc.cluster.local:8200
  output:
    name: "${USERNAME}-password"
    stringData:
      username: "${USERNAME}"
      password: "{{ .d.password }}"
      version: "{{ .md.current_version }}"
    type: Opaque
    labels:
      sylvaproject.org/cluster-secrets: 'true'
    annotations:
      sylvaproject.org/cluster-secrets-type: ${PASSWORD_TYPE}
