---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '${UNIT_NAME}'
  labels:
    name: '${UNIT_NAME}'
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '${UNIT_NAME}'
  labels:
    name: '${UNIT_NAME}'
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '${UNIT_NAME}'
subjects:
  - kind: ServiceAccount
    name: '${UNIT_NAME}'
    namespace: '${NAMESPACE}'
