kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config-values
  namespace: sylva-system
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        configMaps: ${CONFIGMAPS}
        additionalScrapeConfigs:
          - job_name: 'minio-tenant-monitoring/cluster'
            scrape_interval: 1m
            scrape_timeout: 30s
            metrics_path: '/minio/v2/metrics/cluster'
            scheme: https
            tls_config:
              insecure_skip_verify: true
            follow_redirects: true
            kubernetes_sd_configs:
            - role: service
            relabel_configs:
            - source_labels: ['__meta_kubernetes_service_labelpresent_v1_min_io_tenant']
              regex: 'true'
              action: keep
            - source_labels: ['__meta_kubernetes_service_cluster_ip']
              regex: 'None'
              action: drop
            - source_labels: ['__meta_kubernetes_service_label_v1_min_io_tenant']
              target_label: 'minio_tenant'
              regex: '(.+)'
              replacement: '$1'
            - source_labels: ['__meta_kubernetes_namespace']
              target_label: 'namespace'
              regex: '(.+)'
              replacement: '$1'
          - job_name: 'minio-tenant-monitoring/bucket'
            scrape_interval: 1m
            scrape_timeout: 30s
            metrics_path: /minio/v2/metrics/bucket
            scheme: https
            tls_config:
              insecure_skip_verify: true
            follow_redirects: true
            kubernetes_sd_configs:
            - role: service
            relabel_configs:
            - source_labels: ['__meta_kubernetes_service_labelpresent_v1_min_io_tenant']
              regex: 'true'
              action: keep
            - source_labels: ['__meta_kubernetes_service_cluster_ip']
              regex: 'None'
              action: drop
            - source_labels: ['__meta_kubernetes_service_label_v1_min_io_tenant']
              target_label: 'minio_tenant'
              regex: '(.+)'
              replacement: '$1'
            - source_labels: ['__meta_kubernetes_namespace']
              target_label: 'namespace'
              regex: '(.+)'
              replacement: '$1'
          - job_name: 'minio-tenant-monitoring/resource'
            scrape_interval: 1m
            scrape_timeout: 30s
            metrics_path: /minio/v2/metrics/resource
            scheme: https
            tls_config:
              insecure_skip_verify: true
            follow_redirects: true
            kubernetes_sd_configs:
            - role: service
            relabel_configs:
            - source_labels: ['__meta_kubernetes_service_labelpresent_v1_min_io_tenant']
              regex: 'true'
              action: keep
            - source_labels: ['__meta_kubernetes_service_cluster_ip']
              regex: 'None'
              action: drop
            - source_labels: ['__meta_kubernetes_service_label_v1_min_io_tenant']
              target_label: 'minio_tenant'
              regex: '(.+)'
              replacement: '$1'
            - source_labels: ['__meta_kubernetes_namespace']
              target_label: 'namespace'
              regex: '(.+)'
              replacement: '$1'
          - job_name: 'minio-tenant-monitoring/node'
            scrape_interval: 1m
            scrape_timeout: 30s
            metrics_path: /minio/v2/metrics/node
            scheme: https
            tls_config:
              insecure_skip_verify: true
            follow_redirects: true
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - source_labels: ['__meta_kubernetes_pod_labelpresent_v1_min_io_tenant']
              regex: 'true'
              action: keep
            - source_labels: ['__meta_kubernetes_endpoint_port_name']
              regex: 'https-minio'
              action: keep
            - source_labels: ['__meta_kubernetes_pod_label_v1_min_io_tenant']
              target_label: 'minio_tenant'
              regex: '(.+)'
              replacement: '$1'
            - source_labels: ['__meta_kubernetes_namespace']
              target_label: 'namespace'
              regex: '(.+)'
              replacement: '$1'
            - source_labels: ['__meta_kubernetes_pod_label_v1_min_io_pool']
              target_label: 'minio_pool'
              regex: '(.+)'
              replacement: '$1'
          - job_name: 'pushgateway'
            honor_labels: true
            static_configs:
            - targets: ['prometheus-pushgateway.pushgateway.svc.cluster.local:9091']
          - job_name: 'snmp-exporter'
            scrape_interval: 90s
            scrape_timeout: 60s
            file_sd_configs:
              - files: ['/etc/prometheus/configmaps/prometheus-snmp-sd-files/snmp_*.json']
              - files: ['/etc/prometheus/configmaps/prometheus-snmp-sd-files/snmp_*.yaml']
              - files: ['/etc/prometheus/configmaps/prometheus-snmp-sd-files-bmh/snmp_*.json']
              - files: ['/etc/prometheus/configmaps/prometheus-snmp-sd-files-bmh/snmp_*.yaml']
            metrics_path: /snmp
            params:
              module: ['if_mib']
              auth: ['public_v2']
            relabel_configs:
            - source_labels: [__address__]
              target_label: '__param_target'
            - source_labels: ['__param_target']
              target_label: 'instance'
            - source_labels: ['module']
              target_label: '__param_module'
            - source_labels: ['auth']
              target_label: '__param_auth'
            - target_label: '__address__'
              replacement: 'snmp-exporter.snmp-exporter:9116'  # The SNMP exporter's real hostname:port.
            metric_relabel_configs:
            - regex: auth
              action: labeldrop
          - job_name: 'kyverno'
            scrape_interval: 1m
            scrape_timeout: 30s
            relabel_configs:
            - source_labels: [job]
              separator: ;
              regex: (.*)
              target_label: __tmp_prometheus_job_name
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance, __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance]
              separator: ;
              regex: (kyverno);true
              replacement: $1
              action: keep
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              separator: ;
              regex: metrics-port
              replacement: $1
              action: keep
            - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
              separator: ;
              regex: Node;(.*)
              target_label: node
              replacement: ${1}
              action: replace
            - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
              separator: ;
              regex: Pod;(.*)
              target_label: pod
              replacement: ${1}
              action: replace
            - source_labels: [__meta_kubernetes_namespace]
              separator: ;
              regex: (.*)
              target_label: namespace
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_service_name]
              separator: ;
              regex: (.*)
              target_label: service
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_name]
              separator: ;
              regex: (.*)
              target_label: pod
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_container_name]
              separator: ;
              regex: (.*)
              target_label: container
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_phase]
              separator: ;
              regex: (Failed|Succeeded)
              replacement: $1
              action: drop
            - source_labels: [__meta_kubernetes_service_name]
              separator: ;
              regex: (.*)
              target_label: job
              replacement: ${1}
              action: replace
            - separator: ;
              regex: (.*)
              target_label: endpoint
              replacement: metrics-port
              action: replace
            - source_labels: [__address__]
              separator: ;
              regex: (.*)
              modulus: 1
              target_label: __tmp_hash
              replacement: $1
              action: hashmod
            - source_labels: [__tmp_hash]
              separator: ;
              regex: "0"
              replacement: $1
              action: keep
            metric_relabel_configs:
            - source_labels: [__address__]
              separator: ;
              regex: (.*)
              target_label: cluster_id
              replacement: local
              action: replace
            - source_labels: [__address__]
              separator: ;
              regex: (.*)
              target_label: cluster_name
              replacement: local
              action: replace
            kubernetes_sd_configs:
            - role: endpoints
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true
              namespaces:
                own_namespace: false
                names:
                - kyverno