apiVersion: batch/v1
kind: Job
metadata:
  name: get-openstack-images
spec:
  backoffLimit: 5
  activeDeadlineSeconds: ${ACTIVE_DEADLINE_SECONDS:-1800}
  template:
    metadata:
      name: oci-tools-pod
      annotations:
        checksum: s${JOB_CHECKSUM}  # s prefix to avoid this turning into a number if we're unlucky
    spec:
      restartPolicy: Never
      serviceAccountName: get-openstack-images-sa
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: oci-tools-container
        image: registry.gitlab.com/sylva-projects/sylva-elements/container-images/oci-tools:0.1.3
        command: ["/bin/sh","-c", "/opt/scripts/get-openstack-images.py"]
        env:
          - name: OS_CLIENT_CONFIG_FILE
            value: "/etc/openstack/clouds.yaml"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INSECURE_CLIENT
            value: ${JOB_INSECURE_CLIENT}
          - name: http_proxy
            value: ${httpProxy}
          - name: https_proxy
            value: ${httpsProxy}
          - name: no_proxy
            value: ${noProxy}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: openstack-config
          mountPath: /etc/openstack
          readOnly: true
        - name: get-openstack-images-script
          mountPath: /opt/scripts
          readOnly: true
        - name: os-images-info
          mountPath: /opt/config
        - name: tmp-storage
          mountPath: /tmp
      volumes:
      - name: openstack-config
        secret:
          secretName: cluster-cloud-config
      - name: get-openstack-images-script
        configMap:
          name: get-openstack-images-script
          defaultMode: 0777
          items:
          - key: get-openstack-images.py
            path: get-openstack-images.py
      - name: os-images-info
        configMap:
          name: os-images-info
          items:
          - key: values.yaml
            path: os-images-info.yaml
      - name: tmp-storage
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: ${MAX_IMAGE_SIZE:-8Gi}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: get-openstack-images-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-openstack-images
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-openstack-images
subjects:
- kind: ServiceAccount
  name: get-openstack-images-sa
roleRef:
  kind: Role
  name: get-openstack-images
  apiGroup: rbac.authorization.k8s.io
