apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
configMapGenerator:
  - name: get-openstack-images-script
    behavior: create
    files:
      - get-openstack-images.py=./get-openstack-images.py
    options:
      disableNameSuffixHash: true
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
