apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - ../base

patches:
  - patch: |
      apiVersion: vault.banzaicloud.com/v1alpha1
      kind: Vault
      metadata:
        name: vault
      spec:
        image: ghcr.io/openbao/openbao:2.0.3

  - patch: |
      - op: add
        path: /spec/vaultEnvsConfig/-
        value:
          name: BAO_K8S_POD_NAME
          value: $(POD_NAME)

    target:
      kind: Vault
      name: vault
