apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: ${VAULT_API}
      path: ${SECRET_PATH}
      version: v2
      caProvider:  # the CA provider can be either Sylva CA for local VAult or .Values.security.vault.external_vault_ca for external Vault
        type: Secret
        name: vault-ca
        namespace: vault
        key: ca.crt
      auth:
        kubernetes:
          mountPath: ${K8S_AUTH_PATH}
          role: secret-reader
          serviceAccountRef:
            name: default
            namespace: vault
