apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/k-orc/openstack-resource-controller/releases/download/v2.6.0/install.yaml

components:
  - ../common-kustomize-components/crd-remove-caBundle

# Add labels to enable clusterctl move to retrieve resources correponding to capo CRDs
labels:
  - pairs:
      clusterctl.cluster.x-k8s.io: ""

patches:
- target:
    kind: Deployment
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/securityContext
      value:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
- target:
    kind: Deployment
    name: orc-controller-manager
  patch: |-
    kind: _unused_
    metadata:
      name: _unused_
    spec:
      template:
        spec:
          containers:
            - name: manager
              resources:
                requests:
                  memory: 256Mi
                limits:
                  memory: 1Gi

