# In some not-too-far future, this policy will not be required anymore:
# * we'll have upgraded to RKE2ControlPlane >= v1beta1 which has support for RKE2ControlPlane.spec.machineTemplate.nodeDeletionTimeout
# * we won't need anymore to support an upgrade path for which the starting point may have Machines without an adjusted nodeDeletionTimeout
#
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: cluster-machine-node-deletion-timeout-background
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      This policy fixes Machine definitions to force their spec.nodeDeletionTimeout.
      This is primarily meant to set this timeout to 0 (interpreted as "do infinite retries"
      by CAPI Machine controller), to avoid corner case issues due to a failed node
      deletion. See https://gitlab.com/sylva-projects/sylva-core/-/issues/1431.
spec:
  background: true
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: machine-node-deletion-infinite-timeout-background
    match:
      any:
      - resources:
          kinds:
          - "cluster.x-k8s.io/*/Machine"
          selector:
            matchLabels:
              cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME:-cluster}
    mutate:
      targets:  # needed to ensure that the background controller will act on existing resources even in the absence of any update on them
      - kind: Machine
        apiVersion: cluster.x-k8s.io/v1beta1
        name: '{{ request.object.metadata.name }}'
      patchStrategicMerge:
        spec:
          nodeDeletionTimeout: ${NODE_DELETION_TIMEOUT:-0s}
    skipBackgroundRequests: false
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: cluster-machine-node-deletion-timeout-mutating
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      This policy fixes Machine definitions to force their spec.nodeDeletionTimeout.
      This is primarily meant to set this timeout to 0 (interpreted as "do infinite retries"
      by CAPI Machine controller), to avoid corner case issues due to a failed node
      deletion. See https://gitlab.com/sylva-projects/sylva-core/-/issues/1431.
spec:
  rules:
  - name: machine-node-deletion-infinite-timeout-mutating
    match:
      any:
      - resources:
          kinds:
          - "cluster.x-k8s.io/*/Machine"
          - "cluster.x-k8s.io/*/Machine/status"  # increase the odds of this policy being triggered by Machine status updates
          selector:
            matchLabels:
              cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME:-cluster}
    mutate:
      patchStrategicMerge:
        spec:
          nodeDeletionTimeout: ${NODE_DELETION_TIMEOUT:-0s}
