---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.logging-root-fluentd.cattle-logging-system
  namespace: cattle-logging-system
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.72.82
      - key: domain
        op: =
        value: cattle-logging-system
      - key: label
        op: =
        value: app.kubernetes.io/managed-by=logging-root
      - key: label
        op: =
        value: app.kubernetes.io/name=fluentd
      - key: label
        op: =
        value: app.kubernetes.io/component=fluentd
      name: nv.ip.logging-root-fluentd.cattle-logging-system
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.logging-rancher-logging.cattle-logging-system
  namespace: cattle-logging-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: manager
    path: /manager
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: logging-rancher-logging.cattle-logging-system
      - key: domain
        op: =
        value: cattle-logging-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.logging-rancher-logging.cattle-logging-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.logging-root-fluentbit.cattle-logging-system
  namespace: cattle-logging-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-127
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.logging-root-fluentd.cattle-logging-system-egress-128
    ports: tcp/24240
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: logging-root-fluentd.cattle-logging-system
      - key: domain
        op: =
        value: cattle-logging-system
      name: nv.logging-root-fluentd.cattle-logging-system
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: fluent-bit
    path: /fluent-bit/bin/fluent-bit
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: logging-root-fluentbit.cattle-logging-system
      - key: domain
        op: =
        value: cattle-logging-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.logging-root-fluentbit.cattle-logging-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.logging-root-fluentd.cattle-logging-system
  namespace: cattle-logging-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-129
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.loki-gateway.loki-egress-130
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-gateway.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-gateway.loki
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: configmap-reload
    path: /configmap-reload
  - action: allow
    allow_update: false
    name: fluentd
    path: /usr/bin/ruby
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: ruby
    path: /usr/bin/ruby
  - action: allow
    allow_update: false
    name: tini
    path: /sbin/tini
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: logging-root-fluentd.cattle-logging-system
      - key: domain
        op: =
        value: cattle-logging-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.logging-root-fluentd.cattle-logging-system
      original_name: ''
  waf:
    settings: []
    status: true
