---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.loki-backend.loki
  namespace: loki
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.198.188
      - key: domain
        op: =
        value: loki
      - key: label
        op: =
        value: app.kubernetes.io/instance=loki
      - key: label
        op: =
        value: app.kubernetes.io/name=loki
      - key: label
        op: =
        value: app.kubernetes.io/component=backend
      name: nv.ip.loki-backend.loki
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.loki-gateway.loki
  namespace: loki
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.135.112
      - key: domain
        op: =
        value: loki
      - key: label
        op: =
        value: app.kubernetes.io/component=gateway
      - key: label
        op: =
        value: app.kubernetes.io/instance=loki
      - key: label
        op: =
        value: app.kubernetes.io/name=loki
      name: nv.ip.loki-gateway.loki
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.loki-read.loki
  namespace: loki
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.34.74
      - key: domain
        op: =
        value: loki
      - key: label
        op: =
        value: app.kubernetes.io/component=read
      - key: label
        op: =
        value: app.kubernetes.io/instance=loki
      - key: label
        op: =
        value: app.kubernetes.io/name=loki
      name: nv.ip.loki-read.loki
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.loki-write.loki
  namespace: loki
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.47.191
      - key: domain
        op: =
        value: loki
      - key: label
        op: =
        value: app.kubernetes.io/instance=loki
      - key: label
        op: =
        value: app.kubernetes.io/name=loki
      - key: label
        op: =
        value: app.kubernetes.io/component=write
      name: nv.ip.loki-write.loki
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.loki-backend.loki
  namespace: loki
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - any
    name: nv.loki-read.loki-egress-131
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-read.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-read.loki
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-write.loki-egress-132
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-133
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - any
    name: nv.loki-backend.loki-ingress-63
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-read.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-read.loki
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-backend.loki-ingress-64
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-backend.loki-ingress-65
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-backend.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-backend.loki
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: loki
    path: /usr/bin/loki
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: python
    path: /usr/local/bin/python3.12
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-backend.loki
      - key: domain
        op: =
        value: loki
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.loki-backend.loki
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.loki-gateway.loki
  namespace: loki
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - HTTP
    name: nv.loki-write.loki-egress-134
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-135
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: nginx
    path: /usr/sbin/nginx
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-gateway.loki
      - key: domain
        op: =
        value: loki
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.loki-gateway.loki
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.loki-read.loki
  namespace: loki
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-136
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-write.loki-egress-137
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - any
    name: nv.loki-read.loki-ingress-66
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-read.loki-ingress-67
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-read.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-read.loki
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: loki
    path: /usr/bin/loki
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-read.loki
      - key: domain
        op: =
        value: loki
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.loki-read.loki
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.loki-results-cache.loki
  namespace: loki
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: memcached
    path: /usr/local/bin/memcached
  - action: allow
    allow_update: false
    name: memcached_exporter
    path: /bin/memcached_exporter
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-results-cache.loki
      - key: domain
        op: =
        value: loki
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.loki-results-cache.loki
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.loki-write.loki
  namespace: loki
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-138
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - any
    name: nv.loki-write.loki-ingress-68
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.loki-write.loki-ingress-69
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: loki
    path: /usr/bin/loki
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.loki-write.loki
      original_name: ''
  waf:
    settings: []
    status: true
