apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted/releases/download/v0.3.3/controlplane-components.yaml
patches:
  - path: namespace-delete.yaml
    target:
      kind: Namespace
      name: capoa-system
labels:
  - pairs:
      clusterctl.cluster.x-k8s.io: ""
