apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    labelSelector: app.kubernetes.io/component=image-automation-controller
  patch: |-
    $patch: delete
    kind: _unused_
    metadata:
      name: _unused_
- target:
    labelSelector: app.kubernetes.io/component=image-reflector-controller
  patch: |-
    $patch: delete
    kind: _unused_
    metadata:
      name: _unused_
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/component in (kustomize-controller,helm-controller,source-controller)
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent=10
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/component=kustomize-controller
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent-ssa=10
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/component in (kustomize-controller,helm-controller,source-controller)
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --requeue-dependency=8s
    - op: remove
      path: /spec/template/spec/containers/0/resources/limits/cpu
  # workaround for https://gitlab.com/sylva-projects/sylva-core/-/issues/2160
- target:
    kind: Deployment
    name: source-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/fluxcd/source-controller:v1.4.1
