---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multus-bond-cni
  labels:
    tier: node
    app: multus-bond-cni
spec:
  selector:
    matchLabels:
      app: multus-bond-cni
  template:
    metadata:
      labels:
        tier: node
        app: multus-bond-cni
    spec:
      initContainers:
        - name: copy-cni-plugin
          # We're using a big image from openshift here, but at least it's tagged
          image: quay.io/openshift/origin-network-interface-bond-cni:4.20.0
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - |
              set -e -x
              mkdir -p /host/opt/cni/bin
              cp -f /bondcni/bond /host/opt/cni/bin/
          resources:
            limits:
              cpu: "100m"
              ephemeral-storage: "0Mi"
              memory: "8Mi"
            requests:
              cpu: "5m"
              ephemeral-storage: "0Mi"
              memory: "8Mi"
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin/
      containers:
        - name: sleep
          command:
            - sleep
            - infinity
          image: registry.gitlab.com/sylva-projects/sylva-elements/container-images/kube-job:v1.1.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "5m"
              ephemeral-storage: "0Mi"
              memory: "8Mi"
            requests:
              cpu: "0m"
              ephemeral-storage: "0Mi"
              memory: "0Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin/
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: multus
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      enableServiceLinks: false
      priorityClassName: system-node-critical
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
