apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubevirt-manager-certificate
  namespace: kubevirt-manager
spec:
  commonName: ${KUBEVIRT_MANAGER_DNS}
  dnsNames:
  - kubevirt-manager.sylva
  - localhost
  - ${KUBEVIRT_MANAGER_DNS}
  duration: 2160h0m0s
  emailAddresses:
  - surname.name@sylva.org
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    kind: ClusterIssuer
    name: certificate-issuer
  renewBefore: 360h0m0s
  secretName: kubevirt-manager-tls
  subject:
    countries:
    - eu
    organizationalUnits:
    - DEV
    organizations:
    - Sylva
