apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubevirt-manager-oidc-es-${CLUSTER_NAME}
  namespace: kubevirt-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-store-k8s-keycloak
  target:
    name: auth-secret # name of the k8s Secret to be created in the same namespace as ExternalSecret
    template:
      engineVersion: v2
      data:
        clientSecret: "{{ .clientSecret }}"
        clientID: "{{ .clientID }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: keycloak-client-secret-kubevirt-manager-${CLUSTER_NAME}-client  # this secret is a byproduct of the kubevirt-manager-client KeycloakClient resource
        property: CLIENT_SECRET
    - secretKey: clientID
      remoteRef:
        key: keycloak-client-secret-kubevirt-manager-${CLUSTER_NAME}-client
        property: CLIENT_ID
