# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: kubevirt-manager-oidc-init
#   namespace: kubevirt-manager
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: eso-store-k8s-keycloak
#   target:
#     name: auth-secret # name of the k8s Secret to be created in the same namespace as ExternalSecret
#     template:
#       engineVersion: v2
#       data:
#         .htpasswd: ${ADMIN_CREDENTIAL}
#   data:
#     - secretKey: clientSecret
#       remoteRef:
#         key: keycloak-client-secret-kubevirt-manager-client  # this secret is a byproduct of the kubevirt-manager-client KeycloakClient resource
#         property: CLIENT_SECRET
#     - secretKey: clientID
#       remoteRef:
#         key: keycloak-client-secret-kubevirt-manager-client
#         property: CLIENT_ID


apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: kubevirt-manager
  labels:
    app: kubevirt-manager
    kubevirt-manager.io/version: 1.4.0
    kubevirt-manager.io/managed: "true"
data:
  .htpasswd: ${ADMIN_CREDENTIAL}

