apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-db-restore
  namespace: harbor
spec:
  template:
    spec:
      containers:
        - name: pg-restore
          image: postgres:13
          command: ["/bin/sh", "-c"]
          args:
            - echo "Listing available backup file:"
              ls -lrth /data ;
              echo "Staring restore process"
              psql -h "${PGHOST}" -U "${PGUSER}" "${PGDATABASE}" < /data/harbor-backup.sql ;
              echo "Restore complete";
          volumeMounts:
            - mountPath: /data
              name: backup-storage
      restartPolicy: Never
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: backup-pvc
