apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-db-restore
  namespace: harbor
spec:
  template:
    spec:
#      initContainers:
#        - name: check-backup
#          image: bitnami/kubectl:1.27.4
#          command:
#            - /bin/sh
#            - "-c"
#          args:
#            - |
#              echo "Waiting for backup job to complete...";
#              while true; do
#                status=$(kubectl get job harbor-db-backup -n harbor -o jsonpath='{.status.succeeded}');
#                if [ "$status" == "1" ]; then
#                  echo "Backup job succeeded.";
#                  break;
#                fi;
#                echo "Backup job not completed yet. Retrying in 10 seconds...";
#                sleep 10;
#              done;
#              echo "Proceeding with restore.";
      containers:
        - name: pg-restore
          image: postgres:16
          command: ["/bin/sh", "-c"]
          args:
            - echo "Taking backup";
              echo "pghost is - ${PGHOST} , user is - ${PGUSER} , database is - ${PGDATABASE}" ;
              pg_dump -h "${PGHOST}" -U "${PGUSER}" "${PGDATABASE}" > /data/harbor-backup.sql ;
              echo "Backup complete";
              echo "Backup file created - /data/harbor-backup.sql" ;
              ls -lrth /data ;
              if [ ! -f /data/harbor-backup.sql ]; then
                echo "Backup file not found. Exiting.";
                exit 1;
              fi;
              echo "Backup file found for restore. Starting restore process...";
              psql -h "${PGHOSTHA}" -U "${PGUSER}" "${PGDATABASE}" < /data/harbor-backup.sql ;
              echo "Restore complete";
          volumeMounts:
            - mountPath: /data
              name: backup-storage
      restartPolicy: Never
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: backup-pvc
