apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-db-restore
  namespace: harbor
spec:
  template:
    spec:
      containers:
        - name: pg-restore
          image: postgres:13
          command: ["/bin/sh", "-c"]
          args:
            - echo "Listing available backup file:"
              ls -lrth /tmp;
              echo "Staring restore process"
              psql -h "$PGHOST" -U "$PGUSER" "$PGDATABASE" < "/tmp/$BACKUP_FILE";
              echo "Restore complete";
          volumeMounts:
            - mountPath: /data
              name: backup-storage
      restartPolicy: Never
      volumes:
        - name: backup-storage
          emptyDir: {}  # Same volume as in the backup job
