kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: syslog
  namespace: "syslog"
  annotations:
    volume.beta.kubernetes.io/storage-class: "${STORAGECLASS_NAME}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${STORAGE}
