# This example environment values files will let you build
# a Sylva two-node (1 control-plane + 1 worker) mgmt baremetal cluster

cluster_domain: '{{ .Values.cluster.cluster_api_cert_extra_SANs | first }}.nip.io'

cluster_virtual_ip: 192.168.100.1

cluster:
  capi_providers:
    infra_provider: capm3
    bootstrap_provider: cabpr

  control_plane_replicas: 3

  # Add kind container address to cluster kubernetes api certificate SubjectAltNames,
  # in order to be able to reach it from the outside through kubernetes-external service created by libvirt-metal unit
  # once pivot to management cluster will happen, this IP will be retrieved in a cluster-public-endpoint configMap created for that purpose
  cluster_api_cert_extra_SANs:
    - '{{ .Values._internal.bootstrap_node_ip }}'

  rke2:
    additionalUserData:
      config:
        #cloud-config
        users:
          - name: sylva-user
            groups: users
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            lock_passwd: false
            passwd: $1$pdWEicWs$9ZWQf5.CWyXccmP8Chuu01 # sylva

  capm3:
    image_key: ubuntu-jammy-plain-rke2-1-28-8
    primary_pool_network: 192.168.100.0
    primary_pool_gateway: 192.168.100.1
    primary_pool_start: 192.168.100.60
    primary_pool_end: 192.168.100.90
    primary_pool_prefix: "24"
    provisioning_pool_network: 192.168.10.0
    provisioning_pool_gateway: 192.168.10.1
    provisioning_pool_start: 192.168.10.60
    provisioning_pool_end: 192.168.10.90
    provisioning_pool_prefix: "24"

    dns_servers: [10.37.140.50]

  control_plane:
    capm3:
      hostSelector:
        matchLabels:
          cluster-role: control-plane

      provisioning_pool_interface: ens4
      primary_pool_interface: ens5

    network_interfaces:
      ens4:
        type: phy
      ens5:
        type: phy

  baremetal_host_default:
    bmh_metadata:
      annotations:
        sylvaproject.org/default-longhorn-disks-config: >-
          [{"path":"/var/longhorn/disks/disk_by-path_pci-0000:00:0a.0", "storageReserved":0, "allowScheduling":true, "tags":[ "vhdd", "fast"] },
           {"path":"/var/longhorn/disks/disk_by-path_pci-0000:00:0b.0", "storageReserved":0, "allowScheduling":true, "tags":[ "vhdd", "fast"] }]
    bmh_spec:
      online: false
      description: management cluster node
      bmc:
        disableCertificateVerification: true
      bootMode: legacy
      rootDeviceHints:
        deviceName: /dev/vda

  baremetal_hosts:
    management-cp-0:
      bmh_metadata:
        labels:
          cluster-role: control-plane
          snmp-enabled: "true"
        annotations:
          sylvaproject.org/snmp-auth: foo
          sylvaproject.org/snmp-hw-type: dell_idrac
          sylvaproject.org/snmp-endpoint: http://192.168.133.1:5432
      bmh_spec:
        bmc:
          address: redfish-virtualmedia://{{ .Values._internal.bootstrap_node_ip }}:8000/redfish/v1/Systems/c0014001-b10b-f001-c0de-feeb1e54ee15
            # bootMACAddress: fa:16:3e:4f:7b:25
        bootMACAddress: 52:54:00:44:44:00
    management-cp-1:
      bmh_metadata:
        labels:
          cluster-role: control-plane
          snmp-enabled: "true"
        annotations:
          sylvaproject.org/snmp-auth: foo
          sylvaproject.org/snmp-hw-type: dell_idrac
          sylvaproject.org/snmp-endpoint: http://192.168.133.1:5432
      bmh_spec:
        bmc:
          address: redfish-virtualmedia://{{ .Values._internal.bootstrap_node_ip }}:8001/redfish/v1/Systems/c0014001-b10b-f001-c0de-feeb1e54ee15
            #bootMACAddress: fa:16:3e:67:db:20
        bootMACAddress: 52:54:00:55:55:01
    management-cp-2:
      bmh_metadata:
        labels:
          cluster-role: control-plane
          snmp-enabled: "true"
        annotations:
          sylvaproject.org/snmp-auth: foo
          sylvaproject.org/snmp-hw-type: dell_idrac
          sylvaproject.org/snmp-endpoint: http://192.168.133.1:5432
      bmh_spec:
        bmc:
          address: redfish-virtualmedia://{{ .Values._internal.bootstrap_node_ip }}:8002/redfish/v1/Systems/c0014001-b10b-f001-c0de-feeb1e54ee15
            #bootMACAddress: fa:16:3e:07:5f:5b 
        bootMACAddress: 52:54:00:44:44:02


units:
  metal3:
    helmrelease_spec:
      values:
        global:
          # Add console access to IPA - useful for debuging purposes
          ironicKernelParams: 'console=ttyS0 suse.autologin=ttyS0 rootpwd="$$1$$DAhhpomu$$YqNcZc3ce5H7uswK4skCZ."'  # "secret"

  longhorn:
    # this setting can be overridden to true to enable Longhorn
    enabled: true
    helmrelease_spec:
      values:
        persistence:
          defaultClassReplicaCount: 3   # don't enable data replication (this is a single node setup)

  monitoring:
    enabled_conditions:
      - '{{ ternary true false (.Values.env_type | eq "ci") | include "preserve-type" }}'

  ingress-nginx:
    helmrelease_spec:
      values:
        controller:
          image:
            tag: nginx-1.8.1-rancher1  # fix for https://gitlab.com/sylva-projects/sylva-core/-/issues/696

libvirt_metal:
  #image: registry.gitlab.com/sylva-projects/sylva-elements/container-images/libvirt-metal:0.1.4  # customize if wanted
  nodes:
    management-cp-0:
      redfishPort: 8000
      memGB: 24
      numCPUs: 8
    management-cp-1:
      redfishPort: 8001
      memGB: 16
      numCPUs: 6
    management-cp-2:
      redfishPort: 8002
      memGB: 16
      numCPUs: 6


        # dummy configuration to allow deployment of snmp-exporter
snmp:
  devices:
    - alias: bar
      target: 192.168.100.2
      module: hp_cpq
      auth: bar
      cluster_name: dummy_cluster

proxies:
#  # put your own proxy settings here if you need
  http_proxy: "http://172.20.129.49:3128"
  https_proxy: "http://172.20.129.49:3128"
  no_proxy: "127.0.0.0/8,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.sylva,172.20.129.142,172.30.0.0/16,nip.io"

# configure containerd registry mirrors following https://github.com/containerd/containerd/blob/main/docs/hosts.md
# see charts/syla-units/values.yaml for a more detailled example
# registry_mirrors:
#   hosts_config:
#     docker.io:
#     - mirror_url: http://your.mirror/docker
#
#registry_mirrors:
#  default_settings:
#    capabilities:
#      - pull
#      - resolve
#    skip_verify: true
#  hosts_config:
#    docker.io:
#      - mirror_url: https://172.20.129.142
#    quay.io:
#      - mirror_url: https://172.20.129.142
#    registry.gitlab.com:
#      - mirror_url: https://172.20.129.142
#    gcr.io:
#      - mirror_url: https://172.20.129.142
#    ghcr.io:
#      - mirror_url: https://172.20.129.142
#    registry.k8s.io:
#      - mirror_url: https://172.20.129.142

helm_repo_spec_default:
  interval: 60m0s
ntp:
  enabled: yes
  servers:
   - 172.20.1.104
   - 172.20.1.105
sylva_core_oci_registry: oci://172.20.129.142/sylva-projects/sylva-core
oci_registry_extra_ca_certs: |-
  -----BEGIN CERTIFICATE-----
  MIIFPTCCAyWgAwIBAgIUBCG7warv3pzIgFvBb+wgUZUODDswDQYJKoZIhvcNAQEL
  BQAwHDEaMBgGA1UEAwwRbmV4dXMuc3lsdmEubG9jYWwwHhcNMjMxMDI5MDgwNDAz
  WhcNMzMxMDI2MDgwNDAzWjAcMRowGAYDVQQDDBFuZXh1cy5zeWx2YS5sb2NhbDCC
  AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAODXvIgdyKHmyEpIuxwrT2v2
  FD/5oYvQTMR57ro7Q0EyB7p8MhCMD/WSbtIiwg7xoHH9M8P8sFpo0+Ws9OhXzW9K
  qa83vT7oBVz/0/CLmsfY+iWl3A7297aCaZGP1tmPmDbGiRtmlRZ2mm+mpI4oSgX6
  yEj/LIO7G+8dz/hQUF2ZKVp1ra8teiQ8FOV8yiPUEQPCBBBPD30wkqvw8YUI8Z61
  BNLmhvKz0LgwZKhpdT0dljmIVO3v055mpSK25KJa1DUCiQvmaM2RpODx/CX3t+gN
  PqOgvkxf8bi9L6oMlBzlLxhReZuHUC8gI3sem4jqJ4vjCy64BYgwiRFuLT3g7vPf
  B9rUdyeTs6WXQPoFV0E2Tm3WwyoF+19Q2kWnd5j2YO0WPzaKYP80/5Em3IDLZ+4f
  tqrkn7t+g08+5qpO0hVQBU0JapOwfmr6VWNmXDhEuioSyJrxPtnlApdcyB/9fWNo
  IcbthDN60IPGVC2rlMJznfH06YiZQW6cSDzOGdY4cXi+ndp22UlZnaXfsP1hFaYv
  rN36xMNnfOLzxL2k28OtitLJ4rNuYvQXmsz0we8Ttmb644dZCyNifnnMxfBUggMr
  wMestOLSBAJ3jVu8pUi3DnIiwzM28XA/jjaohh9j6vljzRGqAFk6uJiv9EIrSNZe
  Cj112l48mgrUjmle50AFAgMBAAGjdzB1MB0GA1UdDgQWBBR5FaglSD+bfCbWRw2q
  ASQs+imHBjAfBgNVHSMEGDAWgBR5FaglSD+bfCbWRw2qASQs+imHBjAPBgNVHRMB
  Af8EBTADAQH/MCIGA1UdEQQbMBmCEW5leHVzLnN5bHZhLmxvY2FshwSsFIGOMA0G
  CSqGSIb3DQEBCwUAA4ICAQDKY7pD5YugxAn6kycAPfu844VS/XnCm1k8XZWcis+a
  usHOaH7eD8XSUrpGjPAKbzU2C7YzIQlaoB8UkWxY+ZCU9+DH0SiXPVysaf1O3huU
  G1J6AGdydpWUeu+3141o+ows3EZwTnVRpk/8qEpJra4cDMb6wSZCzygk9hSlVNl9
  7KnBGiTQ/JSiWB146RDri7BEOFikojGtOhb/OIaq8um4vukr7PRT8QrMk5sSUeLj
  NrwZQkWwwiJk+2boS5U3AiJ08IqX3eiFqyowRR3vGpopMzixF96gKMFljLBM0k4a
  mS4hmR+Vm+a/Jpvcnp/e5RhWi8k2dlv4pQP/NbxPsrD/6isONq6lftEl0YLqoyTI
  f1Dvilyq3qBv8klSj45JL67Lt6ivSGTcmMA7v4hPZKimjCGMDuuxMkYrLbc3aorF
  sC9KAXE2mUX60olszTo7Ix+ryNDh+k4tyekr1SoXBHC/sH5K+3zk5/1oZngpE+Rg
  qa/Pblbge6X1XPuma+UHSepzosoivKpRXYn7vd3FRPvhNeEQar2vJcYUjUEOzzgF
  pZU3QdcxsEuQyIKBFM/AoRqu3FAZx/64ZC0qYATG2JZd/57qUYB0n4h683tC+7cm
  r89nQH+Vh95OT1d163A+YOOAkP34aFqKA8vckkH+h7rlRJ55G9HwWDrPE7Up66M8
  YQ==
  -----END CERTIFICATE-----
sylva_diskimagebuilder_images:
  ubuntu-jammy-plain-rke2-1-28-8:
    default_enabled: true
  ubuntu-jammy-plain-rke2-1-27-10:
    default_enabled: false
  opensuse-15-5-plain-rke2-1-27-10:
    default_enabled: false

registry_mirrors:
  default_settings:
    skip_verify: true
    override_path: true
  hosts_config:
    docker.io:
      - mirror_url: https://172.20.129.37/v2/docker.io
    quay.io:
      - mirror_url: https://172.20.129.37/v2/quay.io
    registry.gitlab.com:
      - mirror_url: https://172.20.129.37/v2/registry.gitlab
    ghcr.io:
      - mirror_url: https://172.20.129.37/v2/ghcr.io
    registry.k8s.io:
      - mirror_url: https://172.20.129.37/v2/registry.k8s.io
    gcr.io:
      - mirror_url: https://172.20.129.37/v2/googlegcr.io
    registry.suse.com:
      - mirror_url: https://172.20.129.37/v2/registry.suse
    registry.opensuse.org:
      - mirror_url: https://172.20.129.37/v2/registry.opensuse.org

