---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.heat-operator-controller-manager.heat-operator-system
  namespace: heat-operator-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: kube-rbac-proxy
    path: /usr/local/bin/kube-rbac-proxy
  - action: allow
    allow_update: false
    name: manager
    path: /manager
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: heat-operator-controller-manager.heat-operator-system
      - key: domain
        op: =
        value: heat-operator-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.heat-operator-controller-manager.heat-operator-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.heat-operator-controller-manager-metrics-service.heat-operator-system
  namespace: heat-operator-system
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.177.128
      - key: domain
        op: =
        value: heat-operator-system
      - key: label
        op: =
        value: control-plane=controller-manager
      name: nv.ip.heat-operator-controller-manager-metrics-service.heat-operator-system
      original_name: ''
