---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    cnpg.io/cluster: cnpg-harbor
  name: cnpg-harbor
  namespace: harbor
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      cnpg.io/cluster: cnpg-harbor
      cnpg.io/instanceRole: replica
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    cnpg.io/cluster: cnpg-harbor
  name: cnpg-harbor-primary
  namespace: harbor
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      cnpg.io/cluster: cnpg-harbor
      cnpg.io/instanceRole: primary
