apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: control-plane-rke2-pdb
  namespace: rke2-control-plane-system
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: control-plane-rke2
      control-plane: controller-manager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bootstrap-rke2-pdb
  namespace: rke2-bootstrap-system
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: bootstrap-rke2
      control-plane: controller-manager
