apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
- ../oci-artifacts

patches:
  - target:
      kind: OCIRepository
    patch: |
      - op: replace
        path: /metadata/namespace
        value: WORKLOAD_CLUSTER_NAMESPACE
  - target:
      kind: Kustomization
    patch: |
      - op: replace
        path: /metadata/namespace
        value: WORKLOAD_CLUSTER_NAMESPACE
      - op: replace
        path: /spec/targetNamespace
        value: WORKLOAD_CLUSTER_NAMESPACE
