apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: SylvaUnitsRelease
    name: sylva-units
  patch: |
    kind: _unused_
    metadata:
      name: _unused_
    spec:
      sylvaUnitsSource:
        type: oci
        url: oci://SYLVA_BASE_OCI_REGISTRY/sylva-core
        tag: TBD  # this needs to be overridden at runtime (see README.md)
