apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- oci-repo.yaml

patches:
- target:
    kind: HelmRelease
    name: sylva-units
  patch: |
    kind: HelmRelease
    metadata:
      name: _unused_
    spec:
      chartRef:
        kind: OCIRepository # version is driven by OCIRepository/sylva-units, this needs to be overridden at runtime (see README.md)
        name: sylva-units
- target:
    kind: HelmRelease
    name: sylva-units
  # this patch removes the .spec.chart (replaced by .spec.chartRef in case of OCI deployments)
  patch: |
    - op: remove
      path: /spec/chart

- target:
    kind: HelmRelease
    name: sylva-units
    # this is not 100% right, the ConfigMap/use-oci-artifacts-values should be injected earlier (not last)
    # to mimic what we used to have:
    # valuesFiles:
    #   - charts/sylva-units/values.yaml
    #   - charts/sylva-units/workload.values.yaml
  patch: |
    - op: add
      path: /spec/valuesFrom/-
      value:
        kind: ConfigMap
        name: use-oci-artifacts-values
        valuesKey: use-oci-artifacts-values
        optional: true # only needed for 'validate_sylva_units' preview

- target:
    kind: HelmRelease
    name: sylva-units
  # this patch removes the CURRENT_COMMIT setting set fromm environment-values/base
  # which is not what we need for a deployment based on OCI artifcacts
  patch: |
    - op: remove
      path: /spec/values/source_templates/sylva-core/spec

- target:
    kind: GitRepository
    name: sylva-units
  patch: |
    kind: GitRepository
    metadata:
      name: _unused_
    $patch: delete
