---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.harbor-core.harbor
  namespace: harbor
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - Redis
    name: nv.harbor-redis.harbor-egress-102
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-redis.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-redis.harbor
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.harbor-portal.harbor-egress-103
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-portal.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-portal.harbor
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.harbor-registry.harbor-egress-104
    ports: tcp/5000
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-registry.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-registry.harbor
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.harbor-registry.harbor-egress-105
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-registry.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-registry.harbor
      original_name: ''
  - action: allow
    applications:
    - PostgreSQL
    name: nv.harbor-postgres-primary.harbor-egress-106
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-postgres-primary.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-postgres-primary.harbor
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-107
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.harbor-jobservice.harbor-egress-108
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-jobservice.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-jobservice.harbor
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.harbor-core.harbor-ingress-22
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-jobservice.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-jobservice.harbor
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.harbor-core.harbor-ingress-23
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: harbor_core
    path: /harbor/harbor_core
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-core.harbor
      - key: domain
        op: =
        value: harbor
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.harbor-core.harbor
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.harbor-jobservice.harbor
  namespace: harbor
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - Redis
    name: nv.harbor-redis.harbor-egress-109
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-redis.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-redis.harbor
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-110
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - PostgreSQL
    name: nv.harbor-postgres-primary.harbor-egress-111
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-postgres-primary.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-postgres-primary.harbor
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: harbor_jobservice
    path: /harbor/harbor_jobservice
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-jobservice.harbor
      - key: domain
        op: =
        value: harbor
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.harbor-jobservice.harbor
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.harbor-portal.harbor
  namespace: harbor
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.harbor-portal.harbor-ingress-24
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: nginx
    path: /usr/sbin/nginx
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-portal.harbor
      - key: domain
        op: =
        value: harbor
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.harbor-portal.harbor
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.harbor-postgres-primary.harbor
  namespace: harbor
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: sh
    path: '*'
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-postgres-primary.harbor
      - key: domain
        op: =
        value: harbor
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.harbor-postgres-primary.harbor
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.harbor-postgres-read.harbor
  namespace: harbor
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-112
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: sh
    path: '*'
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-postgres-read.harbor
      - key: domain
        op: =
        value: harbor
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.harbor-postgres-read.harbor
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.harbor-redis.harbor
  namespace: harbor
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: redis-server
    path: /usr/bin/redis-server
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-redis.harbor
      - key: domain
        op: =
        value: harbor
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.harbor-redis.harbor
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.harbor-registry.harbor
  namespace: harbor
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: harbor_registryctl
    path: /home/harbor/harbor_registryctl
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: registry_DO_NOT_USE_GC
    path: /usr/bin/registry_DO_NOT_USE_GC
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-registry.harbor
      - key: domain
        op: =
        value: harbor
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.harbor-registry.harbor
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.harbor-core.harbor
  namespace: harbor
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.58.51
      - key: domain
        op: =
        value: harbor
      - key: label
        op: =
        value: app=harbor
      - key: label
        op: =
        value: component=core
      - key: label
        op: =
        value: release=harbor
      name: nv.ip.harbor-core.harbor
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.harbor-jobservice.harbor
  namespace: harbor
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.205.114
      - key: domain
        op: =
        value: harbor
      - key: label
        op: =
        value: app=harbor
      - key: label
        op: =
        value: component=jobservice
      - key: label
        op: =
        value: release=harbor
      name: nv.ip.harbor-jobservice.harbor
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.harbor-portal.harbor
  namespace: harbor
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.233.191
      - key: domain
        op: =
        value: harbor
      - key: label
        op: =
        value: component=portal
      - key: label
        op: =
        value: release=harbor
      - key: label
        op: =
        value: app=harbor
      name: nv.ip.harbor-portal.harbor
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.harbor-postgres-primary.harbor
  namespace: harbor
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.159.186
      - key: domain
        op: =
        value: harbor
      - key: label
        op: =
        value: app.kubernetes.io/name=postgres
      - key: label
        op: =
        value: app.kubernetes.io/component=primary
      - key: label
        op: =
        value: app.kubernetes.io/instance=harbor-postgres
      name: nv.ip.harbor-postgres-primary.harbor
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.harbor-postgres-read.harbor
  namespace: harbor
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.26.129
      - key: domain
        op: =
        value: harbor
      - key: label
        op: =
        value: app.kubernetes.io/instance=harbor-postgres
      - key: label
        op: =
        value: app.kubernetes.io/name=postgres
      - key: label
        op: =
        value: app.kubernetes.io/component=read
      name: nv.ip.harbor-postgres-read.harbor
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.harbor-redis.harbor
  namespace: harbor
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.133.246
      - key: domain
        op: =
        value: harbor
      - key: label
        op: =
        value: app=harbor
      - key: label
        op: =
        value: component=redis
      - key: label
        op: =
        value: release=harbor
      name: nv.ip.harbor-redis.harbor
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.harbor-registry.harbor
  namespace: harbor
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.112.133
      - key: domain
        op: =
        value: harbor
      - key: label
        op: =
        value: component=registry
      - key: label
        op: =
        value: release=harbor
      - key: label
        op: =
        value: app=harbor
      name: nv.ip.harbor-registry.harbor
      original_name: ''
