apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kube-job

configMapGenerator:
- name: kube-job-cm
  behavior: merge
  options:
    disableNameSuffixHash: true
  files:
  - kube-job.sh=read-rke2-certs.sh

patches:
- target:
    kind: Job
  path: job.yaml
