apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://litmuschaos.github.io/litmus/litmus-operator-v3.10.0.yaml

# Patches namespace priviledges and adding labels
patches:
- path: patch-namespace.yaml
