# the scope of this policy is to add the clusterId into workload monitoring values
# this action is performed once the workload cluster is successfully enroled
# into rancher by getting the clusterName and inject it into monitoring hr manifest
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-monitoring-chart-cluster-id
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  generateExisting: true
  rules:
  - name: create-cluster-cm
    skipBackgroundRequests: false
    match:
      any:
      - resources:
          kinds:
          - management.cattle.io/v3/Cluster
          selector:
            matchLabels:
              cluster-api.cattle.io/capi-cluster-owner: '*'
    generate:
      kind: ConfigMap
      apiVersion: v1
      name: '{{request.object.spec.displayName}}-monitoring-info'
      namespace: '{{ request.object.metadata.labels."cluster-api.cattle.io/capi-cluster-owner-ns" }}'
      data:
        data:
          values.yaml: |
            global:
              cattle:
                clusterId: {{ request.object.metadata.name }}
                clusterName: {{ request.object.spec.displayName}}

