apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-installer-config-override
  namespace: assisted-installer
data:
  INSTALL_TO_EXISTING_ROOT: "true"
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  ingress:
    className: nginx
    assistedServiceHostname: "${ASSISTED_SERVICE_HOSTNAME}"
    imageServiceHostname: "${ASSISTED_IMAGE_HOSTNAME}"
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${ASSISTED_DB_SIZE}"
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${ASSISTED_FS_SIZE}"
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${ASSISTED_IMAGESTORE_SIZE}"
  osImages: "${ASSISTED_OS_IMAGES}"
