---
apiVersion: heatoperator.sylva/v1
kind: HeatStack
metadata:
  labels:
    app.kubernetes.io/name: heatstack
    app.kubernetes.io/instance: heatstack-capo-cluster-resources
    app.kubernetes.io/part-of: heat-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: heat-operator
  name: heatstack-capo-cluster-resources
spec:
  heatStack:
    namePrefix: "${STACK_NAME_PREFIX}"
    tag: ${CAPO_TAG}
    template:
      heat_template_version: "2017-09-01"

      parameters:
        network:
          type: string
          description: "Network name"
        external_network:
          type: string
          description: "External Network ID"
          default: ""
        cluster_virtual_ip_port_uuid:
          type: string
          description: "Port UUID to adopt as cluster virtual IP (if set, will be used instead of creating a new port to allocate a VIP)"
          default: ""
        cluster_floating_ip_uuid:
          type: string
          description: "Floating-ip UUID to adopt as cluster public IP (if set, will be used instead of allocating a floating IP)"
          default: ""
        control_plane_affinity_policy:
          type: string
          description: "Control plane affinity policy"
        worker_affinity_policy:
          type: string
          description: "Worker affinity policy"
        control_plane_security_group_name:
          type: string
          description: "Control plane security group name"
        worker_security_group_name:
          type: string
          description: "Worker security group name"
        common_security_group_name:
          type: string
          description: "Common security group name"
        control_plane_rules:
          type: json
          description: "Security group rules associated with the control plane VMs"
          default:
            direction: []
            port: []
            protocol: []
            remote_ip_prefix: []
        worker_rules:
          type: json
          description: "Security group rules associated with worker VMs"
          default:
            direction: []
            port: []
            protocol: []
            remote_ip_prefix: []
        common_sg_rules:
          type: json
          description: "Common security group rules associated with the control plane and worker VMs"
          default:
            direction: [ingress, ingress, ingress, ingress]
            port: ['80', '443', '22', '53']
            protocol: [tcp, tcp, tcp, udp]
            remote_ip_prefix: [0.0.0.0/0, 0.0.0.0/0, 0.0.0.0/0, 0.0.0.0/0]
        create_ironic_security_group:
          type: boolean
          description: "Whenever control plane and worker VMs security groups need to include Ironic flows"
          default: false
        ironic_rules:
          type: json
          description: "Security group rules associated with control plane and worker VMs for Ironic"
          default:
            direction: [ingress, ingress, ingress, ingress, ingress]
            port: ['5050', '6180', '6185', '6385', '9999']
            protocol: [tcp, tcp, tcp, tcp, tcp]
            remote_ip_prefix: [0.0.0.0/0, 0.0.0.0/0, 0.0.0.0/0, 0.0.0.0/0, 0.0.0.0/0]
        dummy_update_trigger:
          type: string
          description: >-
            not actually used, just here to ensure we can artificially update the Heat Stack
            whenever the sylva-units Helm release is updated, which we only do so that
            the updated_time field of the stack reflect the last time the sylva-units HelmRelease
            was updated
          default: "unspecified"

      conditions:
        vip_requested:
          equals:
            - get_param: cluster_virtual_ip_port_uuid
            - ""
        floating_ip_allocation_requested:
          not:
            equals:
              - get_param: external_network
              - ""
        adopt_port:
          not:
            equals:
              - get_param: cluster_virtual_ip_port_uuid
              - ""
        adopt_floating_ip:
          not:
            equals:
              - get_param: cluster_floating_ip_uuid
              - ""


      resources:
        port:
          type: OS::Neutron::Port
          condition: vip_requested
          properties:
            network: { get_param: network }
            name:
              list_join: ['-', [ {get_param: OS::stack_name}, 'sylva-virtual-ip-port-DO-NOT-DELETE-even-if-DOWN']]
            tags:
              - sylva-vip-port
        adopted-port:
          type: OS::Neutron::Port
          condition: adopt_port
          external_id: { get_param: cluster_virtual_ip_port_uuid }
        floating-ip:
          type: OS::Neutron::FloatingIP
          condition: floating_ip_allocation_requested
          properties:
            floating_network: { get_param: external_network }
            port_id: { if: [vip_requested, { get_resource: port }, { get_resource: adopted-port }] }
        adopted-floating-ip:
          type: OS::Neutron::FloatingIP
          condition: adopt_floating_ip
          external_id: {get_param: cluster_floating_ip_uuid }
        floating-ip-association:
          type: OS::Neutron::FloatingIPAssociation
          condition: adopt_floating_ip
          properties:
            floatingip_id: { get_resource: adopted-floating-ip }
            port_id: {if: [vip_requested, { get_resource: port }, {get_resource: adopted-port }] }
        srvgroup-ctrl-plane:
          type: OS::Nova::ServerGroup
          properties:
            policies:
              - get_param: control_plane_affinity_policy
        srvgroup-worker:
          type: OS::Nova::ServerGroup
          properties:
            policies:
              - get_param: worker_affinity_policy
        security-group-ctrl-plane:
          type: OS::Neutron::SecurityGroup
          properties:
            description: "Heat Stack managed security group for control plane VMs"
            name: { get_param: control_plane_security_group_name }
            rules:
              repeat:
                for_each:
                  <%direction%>: { get_param: [control_plane_rules, direction] }
                  <%port%>: { get_param: [control_plane_rules, port] }
                  <%protocol%>: { get_param: [control_plane_rules, protocol] }
                  <%remote_ip_prefix%>: { get_param: [control_plane_rules, remote_ip_prefix] }
                template:
                  protocol: <%protocol%>
                  port_range_min: <%port%>
                  port_range_max: <%port%>
                  remote_ip_prefix: <%remote_ip_prefix%>
                  direction: <%direction%>
                permutations: false
        security-group-worker:
          type: OS::Neutron::SecurityGroup
          properties:
            description: "Heat Stack managed security group for worker VMs"
            name: { get_param: worker_security_group_name }
            rules:
              repeat:
                for_each:
                  <%direction%>: { get_param: [worker_rules, direction] }
                  <%port%>: { get_param: [worker_rules, port] }
                  <%protocol%>: { get_param: [worker_rules, protocol] }
                  <%remote_ip_prefix%>: { get_param: [worker_rules, remote_ip_prefix] }
                template:
                  protocol: <%protocol%>
                  port_range_min: <%port%>
                  port_range_max: <%port%>
                  remote_ip_prefix: <%remote_ip_prefix%>
                  direction: <%direction%>
                permutations: false
        security-group-common:
          type: OS::Neutron::SecurityGroup
          properties:
            description: "Heat Stack managed common security group for control_plane and worker VMs"
            name: { get_param: common_security_group_name }
            rules:
              repeat:
                for_each:
                  <%direction%>: {if: [{get_param: create_ironic_security_group}, { list_concat: [{ get_param: [common_sg_rules, direction]}, { get_param: [ironic_rules, direction] }]}, { get_param: [common_sg_rules, direction] }]}
                  <%port%>: { if: [{get_param: create_ironic_security_group}, { list_concat: [{ get_param: [common_sg_rules, port]}, { get_param: [ironic_rules, port]}]}, { get_param: [common_sg_rules, port] }]}
                  <%protocol%>: { if: [{get_param: create_ironic_security_group}, { list_concat: [{ get_param: [common_sg_rules, protocol]}, { get_param: [ironic_rules, protocol]}]}, { get_param: [common_sg_rules, protocol] }]}
                  <%remote_ip_prefix%>: { if: [{get_param: create_ironic_security_group}, { list_concat: [{ get_param: [common_sg_rules, remote_ip_prefix]}, { get_param: [ironic_rules, remote_ip_prefix]}]}, { get_param: [common_sg_rules, remote_ip_prefix] }]}
                template:
                  protocol: <%protocol%>
                  port_range_min: <%port%>
                  port_range_max: <%port%>
                  remote_ip_prefix: <%remote_ip_prefix%>
                  direction: <%direction%>
                permutations: false
      outputs:
        allocated_ip:
          value:
            if:
              - vip_requested
              - get_attr: [port, fixed_ips, 0, ip_address]
              - get_attr: [adopted-port, fixed_ips, 0, ip_address]
          description: IP address allocated to the port
        allocated_fip:
          value:
            if:
              - floating_ip_allocation_requested
              - get_attr: [floating-ip, floating_ip_address]
              - if:
                - adopt_floating_ip
                - get_attr: [adopted-floating-ip, floating_ip_address]
                - ""
          description: Floating IP associated to the port
        control_plane_servergroup_id:
          value: { get_resource: srvgroup-ctrl-plane }
          description: Control plane server group ID
        worker_servergroup_id:
          value: { get_resource: srvgroup-worker }
          description: Control plane server group ID

    environment:
      parameters:
        network: "${CAPO_NETWORK_ID}"
        cluster_floating_ip_uuid: "${CLUSTER_FLOATING_IP_UUID}"
        cluster_virtual_ip_port_uuid: "${CLUSTER_VIRTUAL_IP_PORT_UUID}"
        external_network: "${CAPO_EXTERNAL_NETWORK_ID}"
        control_plane_affinity_policy: "${CONTROL_PLANE_AFFINITY_POLICY}"
        worker_affinity_policy: "${WORKER_AFFINITY_POLICY}"
        control_plane_security_group_name: "${CONTROL_PLANE_SECURITY_GROUP_NAME}"
        worker_security_group_name: "${WORKER_SECURITY_GROUP_NAME}"
        create_ironic_security_group: ${CAPO_CREATE_IRONIC_SECURITY_GROUP}
        common_security_group_name: "${COMMON_SECURITY_GROUP_NAME}"
        dummy_update_trigger: "${DUMMY_UPDATE_TRIGGER}"
  outputConfigMap:
    name: capo-cluster-resources
    labels:
  identityRef: cluster-cloud-config
  cloudName: capo_cloud
