apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: workload-clusters-propagate-mgmt-state-settings
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  generateExisting: true
  rules:
  - name: generate-cm
    skipBackgroundRequests: false
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              sylva-project.org/workload-cluster: ""
    generate:
      kind: ConfigMap
      apiVersion: v1
      name: mgmt-cluster-state-values
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        name: mgmt-cluster-state-values
        namespace: sylva-system

  - name: clone-ca-key-pair
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              sylva-project.org/workload-cluster: ""
    generate:
      apiVersion: v1
      kind: Secret
      name: ca-key-pair
      namespace: "{{request.object.metadata.name}}"
      synchronize: true   # 🔁 keep it updated on changes
      clone:
        namespace: cert-manager
        name: ca-key-pair

  - name: reconcile-on-secret-update
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              sylva-project.org/workload-cluster: ""
    mutate:
      targets:
      - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        name: wkld-copy-file
        namespace: "{{request.object.metadata.name}}"
      patchStrategicMerge:
        metadata:
          annotations:
            reconcile.fluxcd.io/requestedAt: "{{ time_now_utc() }}"
            kyverno_applied: "true"
        spec:
          postBuild:
            substituteFrom:
            - kind: Secret
              name: ca-key-pair

              
              
              
