apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: workload-clusters-propagate-mgmt-state-settings
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  generateExisting: true
  rules:
  - name: generate-cm
    skipBackgroundRequests: false
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              sylva-project.org/workload-cluster: ""
    generate:
      kind: ConfigMap
      apiVersion: v1
      name: mgmt-cluster-state-values
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        name: mgmt-cluster-state-values
        namespace: sylva-system

  - name: clone-ca-key-pair
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              sylva-project.org/workload-cluster: ""
    generate:
      apiVersion: v1
      kind: Secret
      name: ca-key-pair
      namespace: "{{request.object.metadata.name}}"
      synchronize: true   # 🔁 keep it updated on changes
      clone:
        namespace: cert-manager
        name: ca-key-pair

              
              
              
