apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: workload-clusters-propagate-mgmt-state-settings
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  generateExisting: true
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: generate-cm
    skipBackgroundRequests: false
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              sylva-project.org/workload-cluster: ""
    generate:
      kind: ConfigMap
      apiVersion: v1
      name: mgmt-cluster-state-values
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        name: mgmt-cluster-state-values
        namespace: sylva-system

  - name: clone-ca-key-pair
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              sylva-project.org/workload-cluster: ""
    generate:
      apiVersion: v1
      kind: Secret
      name: ca-key-pair-cloned
      namespace: "{{request.object.metadata.name}}"
      synchronize: true   # 🔁 keep it updated on changes
      clone:
        namespace: cert-manager
        name: ca-key-pair

  - name: label-cloned-secret
    match:
      any:
      - resources:
          kinds:
          - Secret
          names:
          - ca-key-pair-cloned
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            test/gen: "true"

  - name: reconcile-on-secret-update
    match:
      any:
      - resources:
          kinds:
          - Secret
          namespaces:
          - kubeadm-capo
          names:
          - ca-key-pair-cloned
          selector:
             matchLabels:
              test/gen: "true"
    mutate:
      targets:
      - apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        name: wkld-ds-copy-file
        namespace: "{{request.object.metadata.namespace}}"
      patchStrategicMerge:
        metadata:
          annotations:
            reconcile.fluxcd.io/requestedAt: "{{ time_now_utc() }}"
            kyverno-applied: "true"
        spec:
          postBuild:
            substitute:
              DATA: "Substituted by Kyverno"
              
              
              
