apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: globalnetworkset-of-metal3machines
  annotations:
    policies.kyverno.io/title: Add GlobalNetworkSet for a workload cluster
    policies.kyverno.io/category: Firewall
    policies.kyverno.io/subject: Metal3Machine
    policies.kyverno.io/minversion: 1.0.0
    policies.kyverno.io/description: >-
      Creates a GlobalNetworkSet for each workload cluster node so that firewall rules can be
      written to allow some traffic only from/to the workload clusters.
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  rules:
  - name: globalnetworkset-of-metal3machines
    match:
      any:
      - resources:
          kinds:
          - infrastructure.cluster.x-k8s.io/*/Metal3Machine
    exclude:
      any:
      - resources:
          namespaces:
          - sylva-system
    preconditions:
      all:
      - key: '{{ request.object.status.addresses[? type==''InternalIP'' && contains(address, ''.'') ] || `[]` | length(@) }}'
        operator: GreaterThanOrEquals
        value: 1
    context:
      - apiCall:
          urlPath: /apis/infrastructure.cluster.x-k8s.io/v1beta1/namespaces/{{ request.namespace }}/metal3machines/
          method: GET
          jmesPath: items[*].status.addresses[? type=='InternalIP' && contains(address, '.') ].address[]
        name: metal3machines
    generate:
      generateExisting: true
      synchronize: true
      apiVersion: crd.projectcalico.org/v1
      kind: GlobalNetworkSet
      name: "{{request.namespace}}-metal3machines-cluster-gns"
      data:
        kind: GlobalNetworkSet
        metadata:
          labels:
            role: workload-cluster-node
        spec:
          nets: '{{ metal3machines }}'

