---
sylva_diskimagebuilder_images:
  ubuntu-noble-hardened-rke2-1-30-9:
    enabled: true

cluster:
  capi_providers:
    bootstrap_provider: cabpr

  rke2:
    additionalUserData:
      config:
        #cloud-config
        users:
          - name: node-admin
            groups: users, sylva-ops, sudo
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            lock_passwd: false
            passwd: $1$pdWEicWs$9ZWQf5.CWyXccmP8Chuu01 # sylva

## Expected OS image must be configured here
  # capm3:
  #   os_image_selector:
  #     os: ubuntu
