apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: neuvector-to-vip
spec:
  order: 40
  preDNAT: true
  applyOnForward: true
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: app == 'neuvector-controller-pod'
    destination:
      nets:
      - ${CLUSTER_VIRTUAL_IP}
      ports:
      - 443
