---
apiVersion: kyverno.io/v2
kind: CleanupPolicy
metadata:
  name: kubernetes-vip-cleanup-policy
  namespace: kube-system
  annotations:
    policies.kyverno.io/title: Cleanup kubernetes-vip Service from kube-system
    policies.kyverno.io/minversion: 1.12.0
spec:
  schedule: "*/10 * * * *"
  match:
    any:
      - resources:
          kinds:
            - Service
          names:
            - kubernetes-vip
