---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-bmh-automatedcleaningmode
  namespace: sylva-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Disable BMH automatedCleaningMode
    policies.kyverno.io/minversion: 1.12.0
spec:
  background: true
  webhookConfiguration:
    matchConditions:
    - name: has-provision-end
      expression: "has(object.status) && object.status.operationHistory.provision.end != null"
    - name: has-automatedCleaningMode-metadata
      expression: "has(object.spec.automatedCleaningMode) && object.spec.automatedCleaningMode == 'metadata'"
  rules:
  - name: patch-automatedCleanedMode
    match:
      any:
      - resources:
          kinds:
          - metal3.io/*/BareMetalHost
          - metal3.io/*/BareMetalHost/status
    mutate:
      patchStrategicMerge:
        spec:
          automatedCleaningMode: "disabled"
      targets:
      - apiVersion: metal3.io/*
        kind: BareMetalHost
        name: '{{ request.object.metadata.name }}'
        namespace: '{{ request.object.metadata.namespace }}'
