---
apiVersion: v1
kind: Namespace
metadata:
  name: upstream-logging
  labels:
    kubernetes.io/metadata.name: upstream-logging
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest

