sylva_diskimagebuilder_images:
  leapmicro-6-0-0-plain-rke2-1-30-5:
    enabled: true

cluster:
  agent_config_format: ignition
  capm3:
    image_key: leapmicro-6-0-0-plain-rke2-1-30-5
  capo:
    image_key: leapmicro-6-0-0-plain-rke2-1-30-5

  baremetal_hosts:
    management-cp-0:
      ip_preallocations:
        primary: 192.168.100.60

    management-cp-1:
      ip_preallocations:
        primary: 192.168.100.61

    management-cp-2:
      ip_preallocations:
        primary: 192.168.100.62

    management-md-0:
      ip_preallocations:
        primary: 192.168.100.63
