sylva_diskimagebuilder_images:
  opensuse-5-5-leapmicro-rke2-1-28-12:
    enabled: true
  ubuntu-jammy-plain-rke2-1-28-12:
    default_enabled: false

cluster:
  air_gapped: false
  cis_profile: ""
  agent_config_format: ignition
  capm3:
    image_key: opensuse-5-5-leapmicro-rke2-1-28-8
  capo:
    image_key: opensuse-5-5-leapmicro-rke2-1-28-8
