apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Keycloak
  patch: |
    - op: add
      path: /spec/unsupported/podTemplate/spec/containers/0/env/-
      value:
        name: KC_SPI_TRUSTSTORE_FILE_FILE
        value: /mnt/keycloak-truststore/keycloak-truststore.jks
    - op: add
      path: /spec/unsupported/podTemplate/spec/containers/0/env/-
      value:
        name: KC_SPI_TRUSTSTORE_FILE_HOSTNAME_VERIFICATION_POLICY
        value: ANY
    - op: add
      path: /spec/unsupported/podTemplate/spec/containers/0/env/-
      value:
        name: KC_HTTPS_TRUST_STORE_FILE
        value: /mnt/keycloak-truststore/keycloak-truststore.jks
    - op: add
      path: /spec/unsupported/podTemplate/spec/containers/0/env/-
      value:
        name: KC_SPI_TRUSTSTORE_FILE_PASSWORD
        value: changeit
    - op: add
      path: /spec/unsupported/podTemplate/spec/containers/0/env/-
      value:
        name: KC_HTTPS_TRUST_STORE_PASSWORD
        value: changeit
    - op: add
      path: /spec/unsupported/podTemplate/spec/containers/0/volumeMounts
      value:
        - name: keycloak-truststore
          mountPath: /mnt/keycloak-truststore
    - op: add
      path: /spec/unsupported/podTemplate/spec/volumes
      value:
        - name: keycloak-truststore
          configMap:
            name: keycloak-truststore
            defaultMode: 0444
