apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineRole
metadata:
  name: sylva-admin
  namespace: vault
spec:
  name: sylva-admin
  connection:
    tLSConfig:
      skipVerify: true # see https://gitlab.com/sylva-projects/sylva-core/-/issues/261
    address: ${VAULT_API}
  authentication:
    path: ${K8S_AUTH_PATH}
    role: admin
  path: ${OIDC_AUTH_PATH}
  userClaim: sub
  allowedRedirectURIs:
    - "https://${VAULT_DNS}/v1/auth/${OIDC_AUTH_PATH}/oidc/callback"
    - "https://${VAULT_DNS}/ui/vault/auth/${OIDC_AUTH_PATH}/oidc/callback"
  groupsClaim: group
  tokenPolicies: # SSO user can read the secret path and gains admin privileges
    - secret-reader
    - admin
  tokenTTL: 1h
  boundAudiences:
    - vault
  boundClaims:
    group: infra-admins # must match the keycloak group name set in unit keycloak-resources
  roleType: oidc
