apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-keycloak
  namespace: keycloak
spec:
  # One primary and two standby servers
  instances: ${KEYCLOAK_POSTGRES_REPLICAS}
  # Sets Postgres shared buffers to 1GB
  postgresql:
    parameters:
      shared_buffers: "512MB"
      max_wal_size: "1GB"
      min_wal_size: "80MB"
      wal_keep_size: "128MB"
  # Sets the resources for Guaranteed QoS
  resources:
    requests:
      memory: "1Gi"
      cpu: 1
    limits:
      memory: "1Gi"
      cpu: 1
  # Sets the 20GB storage for PGDATA
  # This volume will also be used by the import
  # process to temporarily store the custom format
  # dump coming from the source database
  storage:
    size: 20Gi
    storageClass: ${storageClass}
  walStorage:
    size: 10Gi
    storageClass: ${storageClass}
  affinity:
    podAntiAffinityType: ${podAntiAffinityType}
  enablePDB: false
  # Initializes the cluster from scratch (initdb bootstrap)
  bootstrap:
    initdb:
      # Enables data checksums
      dataChecksums: true
      # Sets WAL segment size to 32MB
      walSegmentSize: 32
