---
cluster:
  control_plane:
    rolloutStrategy:
      rollingUpdate:
        maxSurge: 0
  additional_commands:
    pre_bootstrap_commands:
      - mkdir -p '/etc/containerd/hosts.d/172.17.0.1:5000'
      - echo '[host."http://172.17.0.1:5000"]' > '/etc/containerd/hosts.d/172.17.0.1:5000/hosts.toml'
  ck8s:
    users:
      - name: sylva-user
        groups: users
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        lock_passwd: false
        passwd: $1$pdWEicWs$9ZWQf5.CWyXccmP8Chuu01 # sylva

  k8s_version: 1.32.2

  capi_providers:
    bootstrap_provider: cabpck

  capm3:
    os_image_selector:
      os: ubuntu
      hardened: false

os_images_oci_registries:
  dib:
    url: oci://registry.gitlab.com/sylva-projects/sylva-elements/diskimage-builder/snapshots
    tag: '0.0.0-git-124585da'
    cosign_publickey: ""

sylva_diskimagebuilder_images:
  ubuntu-noble-plain-ck8s-1-32-2:
    os_images_oci_registry: dib

security:
  os_images:
    skip_signing_check: true
  oci_artifacts:
    skip_signing_check: true
