---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.calico-kube-controllers.calico-system
  namespace: calico-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - any
    name: nv.kube-apiserver-mgmt-cluster-cp.kube-system-egress-137
    ports: tcp/6443
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kube-apiserver-mgmt-cluster-cp.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-apiserver-mgmt-cluster-cp.kube-system
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-138
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.loki-gateway.loki-egress-139
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-gateway.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-gateway.loki
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: check-status
    path: '*'
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: calico-kube-controllers.calico-system
      - key: domain
        op: =
        value: calico-system
      name: nv.calico-kube-controllers.calico-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.calico-node.calico-system
  namespace: calico-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: calico-node
    path: /bin/calico-node
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: calico-node.calico-system
      - key: domain
        op: =
        value: calico-system
      name: nv.calico-node.calico-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.calico-typha.calico-system
  namespace: calico-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: calico-typha
    path: /code/calico-typha
  - action: allow
    allow_update: false
    name: pathWalker
    path: /usr/local/bin/pathWalker
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: tini
    path: /sbin/tini
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: calico-typha.calico-system
      - key: domain
        op: =
        value: calico-system
      name: nv.calico-typha.calico-system
      original_name: ''
  waf:
    settings: []
    status: true
