---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.capi-controller-manager.capi-system
  namespace: capi-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - any
    name: nv.kube-apiserver-main-mgmt-cp.kube-system-egress-94
    ports: tcp/6443
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kube-apiserver-main-mgmt-cp.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-apiserver-main-mgmt-cp.kube-system
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.capi-controller-manager.capi-system-ingress-16
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: manager
    path: /manager
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: capi-controller-manager.capi-system
      - key: domain
        op: =
        value: capi-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.capi-controller-manager.capi-system
      original_name: ''
  waf:
    settings: []
    status: true
