---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.fleet-agent.cattle-fleet-local-system
  namespace: cattle-fleet-local-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - any
    name: nv.kube-apiserver-mgmt-cluster-cp.kube-system-egress-194
    ports: tcp/6443
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kube-apiserver-mgmt-cluster-cp.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-apiserver-mgmt-cluster-cp.kube-system
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: fleetagent
    path: /usr/bin/fleetagent
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: fleet-agent.cattle-fleet-local-system
      - key: domain
        op: =
        value: cattle-fleet-local-system
      name: nv.fleet-agent.cattle-fleet-local-system
      original_name: ''
  waf:
    settings: []
    status: true
