---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.cert-manager-cainjector.cert-manager
  namespace: cert-manager
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: cainjector
    path: /app/cmd/cainjector/cainjector
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: cert-manager-cainjector.cert-manager
      - key: domain
        op: =
        value: cert-manager
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.cert-manager-cainjector.cert-manager
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.cert-manager-webhook.cert-manager
  namespace: cert-manager
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - any
    name: nv.kube-apiserver-main-mgmt-cp.kube-system-egress-96
    ports: tcp/6443
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kube-apiserver-main-mgmt-cp.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-apiserver-main-mgmt-cp.kube-system
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.cert-manager-webhook.cert-manager-ingress-18
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: webhook
    path: /app/cmd/webhook/webhook
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: cert-manager-webhook.cert-manager
      - key: domain
        op: =
        value: cert-manager
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.cert-manager-webhook.cert-manager
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.cert-manager.cert-manager
  namespace: cert-manager
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: controller
    path: /app/cmd/controller/controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: cert-manager.cert-manager
      - key: domain
        op: =
        value: cert-manager
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.cert-manager.cert-manager
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.cert-manager-webhook.cert-manager
  namespace: cert-manager
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.203.183
      - key: domain
        op: =
        value: cert-manager
      - key: label
        op: =
        value: app.kubernetes.io/component=webhook
      - key: label
        op: =
        value: app.kubernetes.io/instance=cert-manager
      - key: label
        op: =
        value: app.kubernetes.io/name=webhook
      name: nv.ip.cert-manager-webhook.cert-manager
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.cert-manager.cert-manager
  namespace: cert-manager
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.250.214
      - key: domain
        op: =
        value: cert-manager
      - key: label
        op: =
        value: app.kubernetes.io/name=cert-manager
      - key: label
        op: =
        value: app.kubernetes.io/component=controller
      - key: label
        op: =
        value: app.kubernetes.io/instance=cert-manager
      name: nv.ip.cert-manager.cert-manager
      original_name: ''
