---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.external-secrets-operator-cert-controller.external-secrets
  namespace: external-secrets
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - any
    name: nv.kube-apiserver-mgmt-cluster-cp.kube-system-egress-185
    ports: tcp/6443
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kube-apiserver-mgmt-cluster-cp.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-apiserver-mgmt-cluster-cp.kube-system
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-186
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.monitoring-pool-0.minio-monitoring-tenant-egress-187
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: monitoring-pool-0.minio-monitoring-tenant
      - key: domain
        op: =
        value: minio-monitoring-tenant
      name: nv.monitoring-pool-0.minio-monitoring-tenant
      original_name: ''
  - action: allow
    applications:
    - PostgreSQL
    name: nv.harbor-postgres-primary.harbor-egress-188
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: harbor-postgres-primary.harbor
      - key: domain
        op: =
        value: harbor
      name: nv.harbor-postgres-primary.harbor
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: external-secrets
    path: /bin/external-secrets
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: external-secrets-operator-cert-controller.external-secrets
      - key: domain
        op: =
        value: external-secrets
      name: nv.external-secrets-operator-cert-controller.external-secrets
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.external-secrets-operator-webhook.external-secrets
  namespace: external-secrets
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: dumb-init
    path: /usr/bin/dumb-init
  - action: allow
    allow_update: false
    name: external-secrets
    path: /bin/external-secrets
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: vault
    path: /bin/vault
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: external-secrets-operator-webhook.external-secrets
      - key: domain
        op: =
        value: external-secrets
      name: nv.external-secrets-operator-webhook.external-secrets
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.external-secrets-operator.external-secrets
  namespace: external-secrets
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-189
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.kube-apiserver-mgmt-cluster-cp.kube-system-egress-190
    ports: tcp/6443
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kube-apiserver-mgmt-cluster-cp.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-apiserver-mgmt-cluster-cp.kube-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.vault.vault-egress-191
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault.vault
      - key: domain
        op: =
        value: vault
      name: nv.vault.vault
      original_name: ''
  - action: allow
    applications:
    - PostgreSQL
    name: nv.gitea-postgres-postgresql-ha-postgresql.gitea-egress-192
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: gitea-postgres-postgresql-ha-postgresql.gitea
      - key: domain
        op: =
        value: gitea
      name: nv.gitea-postgres-postgresql-ha-postgresql.gitea
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.loki-gateway.loki-egress-193
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-gateway.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-gateway.loki
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.external-secrets-operator.external-secrets-ingress-41
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      - key: domain
        op: =
        value: cattle-monitoring-system
      name: nv.prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: bash
    path: /usr/bin/bash
  - action: allow
    allow_update: false
    name: external-secrets
    path: /bin/external-secrets
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: pgrep
    path: /bin/pgrep
  - action: allow
    allow_update: false
    name: psql
    path: /opt/bitnami/postgresql/bin/psql
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: external-secrets-operator.external-secrets
      - key: domain
        op: =
        value: external-secrets
      name: nv.external-secrets-operator.external-secrets
      original_name: ''
  waf:
    settings: []
    status: true
