---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.flux-webui-weave-gitops.flux-system
  namespace: flux-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.flux-webui-weave-gitops.flux-system-ingress-20
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: gitops-server
    path: /gitops-server
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: flux-webui-weave-gitops.flux-system
      - key: domain
        op: =
        value: flux-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.flux-webui-weave-gitops.flux-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.helm-controller.flux-system
  namespace: flux-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - HTTP
    name: nv.source-controller.flux-system-egress-113
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: source-controller.flux-system
      - key: domain
        op: =
        value: flux-system
      name: nv.source-controller.flux-system
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-114
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: helm-controller
    path: /usr/local/bin/helm-controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: helm-controller.flux-system
      - key: domain
        op: =
        value: flux-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.helm-controller.flux-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kustomize-controller.flux-system
  namespace: flux-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-123
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.source-controller.flux-system-egress-124
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: source-controller.flux-system
      - key: domain
        op: =
        value: flux-system
      name: nv.source-controller.flux-system
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.notification-controller.flux-system-egress-125
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: notification-controller.flux-system
      - key: domain
        op: =
        value: flux-system
      name: nv.notification-controller.flux-system
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: basename
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: busybox
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: git
    path: /usr/bin/git
  - action: allow
    allow_update: false
    name: git-remote-https
    path: /usr/libexec/git-core/git-remote-http
  - action: allow
    allow_update: false
    name: git-sh-i18n--en
    path: /usr/libexec/git-core/git-sh-i18n--envsubst
  - action: allow
    allow_update: false
    name: git-sh-i18n--envsubst
    path: /usr/libexec/git-core/git-sh-i18n--envsubst
  - action: allow
    allow_update: false
    name: git-submodule
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: kustomize-controller
    path: /usr/local/bin/kustomize-controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: sed
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: tini
    path: /sbin/tini
  - action: allow
    allow_update: false
    name: uname
    path: /bin/busybox
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kustomize-controller.flux-system
      - key: domain
        op: =
        value: flux-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kustomize-controller.flux-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.notification-controller.flux-system
  namespace: flux-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.notification-controller.flux-system-ingress-75
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: source-controller.flux-system
      - key: domain
        op: =
        value: flux-system
      name: nv.source-controller.flux-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: notification-controller
    path: /usr/local/bin/notification-controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: notification-controller.flux-system
      - key: domain
        op: =
        value: flux-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.notification-controller.flux-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.source-controller.flux-system
  namespace: flux-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: source-controller
    path: /usr/local/bin/source-controller
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: source-controller.flux-system
      - key: domain
        op: =
        value: flux-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.source-controller.flux-system
      original_name: ''
  waf:
    settings: []
    status: true
