---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.k8s-gateway.k8s-gateway
  namespace: k8s-gateway
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.39.219
      - key: domain
        op: =
        value: k8s-gateway
      - key: label
        op: =
        value: app.kubernetes.io/name=k8s-gateway
      - key: label
        op: =
        value: app.kubernetes.io/instance=k8s-gateway
      name: nv.ip.k8s-gateway.k8s-gateway
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.k8s-gateway.k8s-gateway
  namespace: k8s-gateway
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - any
    name: nv.kube-apiserver-main-mgmt-cp.kube-system-egress-116
    ports: tcp/6443
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kube-apiserver-main-mgmt-cp.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-apiserver-main-mgmt-cp.kube-system
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-117
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - any
    name: nv.k8s-gateway.k8s-gateway-ingress-25
    ports: udp/1053
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: coredns
    path: /coredns
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: k8s-gateway.k8s-gateway
      - key: domain
        op: =
        value: k8s-gateway
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.k8s-gateway.k8s-gateway
      original_name: ''
  waf:
    settings: []
    status: true
