---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.cluster-machines-ready-wkl-rke2-capm3.kube-job
  namespace: kube-job
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process: []
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: cluster-machines-ready-wkl-rke2-capm3.kube-job
      - key: domain
        op: =
        value: kube-job
      name: nv.cluster-machines-ready-wkl-rke2-capm3.kube-job
      original_name: ''
  waf:
    settings: []
    status: true
