---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.migrator.kube-storage-version-migrator
  namespace: kube-storage-version-migrator
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: migrator
    path: /migrator
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: migrator.kube-storage-version-migrator
      - key: domain
        op: =
        value: kube-storage-version-migrator
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.migrator.kube-storage-version-migrator
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.trigger.kube-storage-version-migrator
  namespace: kube-storage-version-migrator
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: trigger
    path: /trigger
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: trigger.kube-storage-version-migrator
      - key: domain
        op: =
        value: kube-storage-version-migrator
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.trigger.kube-storage-version-migrator
      original_name: ''
  waf:
    settings: []
    status: true
