apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nodes.yaml
- calico-system.yaml
- capi-system.yaml
- capi-rancher-import.yaml
- cert-manager.yaml
- cis-operator-system.yaml
- kube-system.yaml
- sylva-system.yaml
- external-secrets.yaml
- flux-system.yaml
- k8s-gateway.yaml
- keycloak.yaml
- kyverno.yaml
- minio-logging.yaml
- metallb-system.yaml
- kube-storage-version-migrator.yaml
- pushgateway.yaml
- rke2-bootstrap-system.yaml
- rke2-control-plane-system.yaml
- sylva-units-operator-system.yaml
- tigera-operator.yaml
- vault.yaml
- workload-cluster-operator-system.yaml
