apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- calico-system.yaml
- capi-rancher-import.yaml
- capi-system.yaml
- capm3-system.yaml
- capo-system.yaml
- cattle-fleet-local-system.yaml
- cattle-fleet-system.yaml
- cattle-logging-system.yaml
- cattle-monitoring-system.yaml
- cattle-system.yaml
- cert-manager.yaml
- cinder-csi.yaml
- cis-operator-system.yaml
- cluster-policies.yaml
- default.yaml
- external-secrets.yaml
- flux-system.yaml
- gitea.yaml
- harbor.yaml
- heat-operator-system.yaml
- k8s-gateway.yaml
- keycloak.yaml
- kube-job.yaml
- kube-storage-version-migrator.yaml
- kube-system.yaml
- kyverno.yaml
- loki.yaml
- metal3-system.yaml
- metallb-system.yaml
- minio-monitoring-tenant.yaml
- minio-operator.yaml
- os-images.yaml
- pushgateway.yaml
- rke2-bootstrap-system.yaml
- rke2-control-plane-system.yaml
- sylva-units-operator-system.yaml
- thanos.yaml
- tigera-operator.yaml
- vault.yaml
- workload-cluster-operator-system.yaml