---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kyverno-admission-controller.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.kyverno-admission-controller.kyverno-ingress-53
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.kyverno-admission-controller.kyverno-ingress-54
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      - key: domain
        op: =
        value: cattle-monitoring-system
      name: nv.prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: kyverno
    path: /ko-app/kyverno
  - action: allow
    allow_update: false
    name: kyverno-init
    path: /ko-app/kyverno-init
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-admission-controller.kyverno
      - key: domain
        op: =
        value: kyverno
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kyverno-admission-controller.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kyverno-background-controller.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.kyverno-background-controller.kyverno-ingress-55
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      - key: domain
        op: =
        value: cattle-monitoring-system
      name: nv.prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: background-controller
    path: /ko-app/background-controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-background-controller.kyverno
      - key: domain
        op: =
        value: kyverno
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kyverno-background-controller.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kyverno-cleanup-admission-reports.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-cleanup-admission-reports.kyverno
      - key: domain
        op: =
        value: kyverno
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kyverno-cleanup-admission-reports.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kyverno-cleanup-cluster-admission-reports.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-cleanup-cluster-admission-reports.kyverno
      - key: domain
        op: =
        value: kyverno
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kyverno-cleanup-cluster-admission-reports.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kyverno-cleanup-cluster-ephemeral-reports.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-cleanup-cluster-ephemeral-reports.kyverno
      - key: domain
        op: =
        value: kyverno
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kyverno-cleanup-cluster-ephemeral-reports.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kyverno-cleanup-controller.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.kyverno-cleanup-controller.kyverno-ingress-56
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      - key: domain
        op: =
        value: cattle-monitoring-system
      name: nv.prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: cleanup-controller
    path: /ko-app/cleanup-controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-cleanup-controller.kyverno
      - key: domain
        op: =
        value: kyverno
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kyverno-cleanup-controller.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kyverno-cleanup-ephemeral-reports.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-cleanup-ephemeral-reports.kyverno
      - key: domain
        op: =
        value: kyverno
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kyverno-cleanup-ephemeral-reports.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.kyverno-reports-controller.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.kyverno-reports-controller.kyverno-ingress-57
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      - key: domain
        op: =
        value: cattle-monitoring-system
      name: nv.prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: reports-controller
    path: /ko-app/reports-controller
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-reports-controller.kyverno
      - key: domain
        op: =
        value: kyverno
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.kyverno-reports-controller.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
