---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.kyverno-admission-controller.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-256
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.monitoring-pool-0.minio-monitoring-tenant-egress-257
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: monitoring-pool-0.minio-monitoring-tenant
      - key: domain
        op: =
        value: minio-monitoring-tenant
      name: nv.monitoring-pool-0.minio-monitoring-tenant
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-write.loki-egress-258
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: grep
    path: /usr/bin/grep
  - action: allow
    allow_update: false
    name: kyverno
    path: /ko-app/kyverno
  - action: allow
    allow_update: false
    name: kyverno-init
    path: /ko-app/kyverno-init
  - action: allow
    allow_update: false
    name: nginx
    path: /usr/local/nginx/sbin/nginx
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-admission-controller.kyverno
      - key: domain
        op: =
        value: kyverno
      name: nv.kyverno-admission-controller.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.kyverno-background-controller.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - HTTP
    - SSL
    name: nv.rancher.cattle-system-egress-259
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rancher.cattle-system
      - key: domain
        op: =
        value: cattle-system
      name: nv.rancher.cattle-system
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-260
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.monitoring-pool-0.minio-monitoring-tenant-egress-261
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: monitoring-pool-0.minio-monitoring-tenant
      - key: domain
        op: =
        value: minio-monitoring-tenant
      name: nv.monitoring-pool-0.minio-monitoring-tenant
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.thanos-ruler.thanos-egress-262
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-ruler.thanos
      - key: domain
        op: =
        value: thanos
      name: nv.thanos-ruler.thanos
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: awk
    path: /usr/bin/mawk
  - action: allow
    allow_update: false
    name: background-controller
    path: /ko-app/background-controller
  - action: allow
    allow_update: false
    name: calico-ipam
    path: /opt/cni/bin/calico-ipam
  - action: allow
    allow_update: false
    name: cut
    path: /usr/bin/cut
  - action: allow
    allow_update: false
    name: entrypoint.sh
    path: /bin/bash
  - action: allow
    allow_update: false
    name: getent
    path: /usr/bin/getent
  - action: allow
    allow_update: false
    name: head
    path: /usr/bin/head
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: pgrep
    path: /bin/pgrep
  - action: allow
    allow_update: false
    name: redis-server
    path: /opt/bitnami/redis/bin/redis-server
  - action: allow
    allow_update: false
    name: sed
    path: /bin/sed
  - action: allow
    allow_update: false
    name: setup.sh
    path: /bin/bash
  - action: allow
    allow_update: false
    name: tr
    path: /usr/bin/tr
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-background-controller.kyverno
      - key: domain
        op: =
        value: kyverno
      name: nv.kyverno-background-controller.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.kyverno-cleanup-admission-reports.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process: []
  process_profile:
    baseline: zero-drift
  target:
    policymode: Discover
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-cleanup-admission-reports.kyverno
      - key: domain
        op: =
        value: kyverno
      name: nv.kyverno-cleanup-admission-reports.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.kyverno-cleanup-cluster-admission-reports.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process: []
  process_profile:
    baseline: zero-drift
  target:
    policymode: Discover
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-cleanup-cluster-admission-reports.kyverno
      - key: domain
        op: =
        value: kyverno
      name: nv.kyverno-cleanup-cluster-admission-reports.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.kyverno-cleanup-controller.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: cleanup-controller
    path: /ko-app/cleanup-controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-cleanup-controller.kyverno
      - key: domain
        op: =
        value: kyverno
      name: nv.kyverno-cleanup-controller.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.kyverno-reports-controller.kyverno
  namespace: kyverno
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-263
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - PostgreSQL
    name: nv.postgres-primary.keycloak-egress-264
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: postgres-primary.keycloak
      - key: domain
        op: =
        value: keycloak
      name: nv.postgres-primary.keycloak
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-write.loki-egress-265
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-backend.loki-egress-266
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-backend.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-backend.loki
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.loki-read.loki-egress-267
    ports: tcp/7946
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-read.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-read.loki
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.monitoring-pool-0.minio-monitoring-tenant-egress-268
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: monitoring-pool-0.minio-monitoring-tenant
      - key: domain
        op: =
        value: minio-monitoring-tenant
      name: nv.monitoring-pool-0.minio-monitoring-tenant
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pathWalker
    path: /usr/local/bin/pathWalker
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: reports-controller
    path: /ko-app/reports-controller
  - action: allow
    allow_update: false
    name: run
    path: /usr/bin/bash
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kyverno-reports-controller.kyverno
      - key: domain
        op: =
        value: kyverno
      name: nv.kyverno-reports-controller.kyverno
      original_name: ''
  waf:
    settings: []
    status: true
