---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.metallb-webhook-service.metallb-system
  namespace: metallb-system
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.179.26
      - key: domain
        op: =
        value: metallb-system
      - key: label
        op: =
        value: app.kubernetes.io/component=controller
      - key: label
        op: =
        value: app.kubernetes.io/instance=metallb
      - key: label
        op: =
        value: app.kubernetes.io/name=metallb
      name: nv.ip.metallb-webhook-service.metallb-system
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.metallb-controller.metallb-system
  namespace: metallb-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: controller
    path: /controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: metallb-controller.metallb-system
      - key: domain
        op: =
        value: metallb-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.metallb-controller.metallb-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.metallb-speaker.metallb-system
  namespace: metallb-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: speaker
    path: /speaker
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: metallb-speaker.metallb-system
      - key: domain
        op: =
        value: metallb-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.metallb-speaker.metallb-system
      original_name: ''
  waf:
    settings: []
    status: true
