---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.console.minio-operator
  namespace: minio-operator
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - SSL
    name: nv.vault.vault-egress-181
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault.vault
      - key: domain
        op: =
        value: vault
      name: nv.vault.vault
      original_name: ''
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-182
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.kube-apiserver-mgmt-cluster-cp.kube-system-egress-183
    ports: tcp/6443
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: kube-apiserver-mgmt-cluster-cp.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-apiserver-mgmt-cluster-cp.kube-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.monitoring-pool-0.minio-monitoring-tenant-egress-184
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: monitoring-pool-0.minio-monitoring-tenant
      - key: domain
        op: =
        value: minio-monitoring-tenant
      name: nv.monitoring-pool-0.minio-monitoring-tenant
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.console.minio-operator-ingress-40
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-ingress-nginx-controller.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-ingress-nginx-controller.kube-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: awk
    path: /usr/bin/mawk
  - action: allow
    allow_update: false
    name: bank-vaults
    path: /usr/local/bin/bank-vaults
  - action: allow
    allow_update: false
    name: calico-ipam
    path: /opt/cni/bin/calico-ipam
  - action: allow
    allow_update: false
    name: containerd-shim-runc-v2
    path: /var/lib/rancher/rke2/data/v1.28.8-rke2r1-c4073db9beee/bin/containerd-shim-runc-v2
  - action: allow
    allow_update: false
    name: dumb-init
    path: /usr/bin/dumb-init
  - action: allow
    allow_update: false
    name: minio-operator
    path: /minio-operator
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: template
    path: /usr/local/bin/template
  - action: allow
    allow_update: false
    name: vault
    path: /bin/vault
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: console.minio-operator
      - key: domain
        op: =
        value: minio-operator
      name: nv.console.minio-operator
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.minio-operator.minio-operator
  namespace: minio-operator
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-298
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.monitoring-pool-0.minio-monitoring-tenant-egress-299
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: monitoring-pool-0.minio-monitoring-tenant
      - key: domain
        op: =
        value: minio-monitoring-tenant
      name: nv.monitoring-pool-0.minio-monitoring-tenant
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.vault.vault-egress-300
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault.vault
      - key: domain
        op: =
        value: vault
      name: nv.vault.vault
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.vault.vault-egress-301
    ports: tcp/8200
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault.vault
      - key: domain
        op: =
        value: vault
      name: nv.vault.vault
      original_name: ''
  - action: allow
    applications:
    - PostgreSQL
    name: nv.postgres-primary.keycloak-egress-302
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: postgres-primary.keycloak
      - key: domain
        op: =
        value: keycloak
      name: nv.postgres-primary.keycloak
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: calico-ipam
    path: /opt/cni/bin/calico-ipam
  - action: allow
    allow_update: false
    name: minio-operator
    path: /minio-operator
  - action: allow
    allow_update: false
    name: pathWalker
    path: /usr/local/bin/pathWalker
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: minio-operator.minio-operator
      - key: domain
        op: =
        value: minio-operator
      name: nv.minio-operator.minio-operator
      original_name: ''
  waf:
    settings: []
    status: true
