---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.logging-console.minio-logging
  namespace: minio-logging
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.152.247
      - key: domain
        op: =
        value: minio-logging
      - key: label
        op: =
        value: v1.min.io/tenant=logging
      name: nv.ip.logging-console.minio-logging
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.minio.minio-logging
  namespace: minio-logging
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.138.243
      - key: domain
        op: =
        value: minio-logging
      - key: label
        op: =
        value: v1.min.io/tenant=logging
      name: nv.ip.minio.minio-logging
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.logging-pool-0.minio-logging
  namespace: minio-logging
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-126
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.logging-pool-0.minio-logging-ingress-58
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      - key: domain
        op: =
        value: cattle-monitoring-system
      name: nv.prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.logging-pool-0.minio-logging-ingress-59
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-backend.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-backend.loki
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.logging-pool-0.minio-logging-ingress-60
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: logging-pool-0.minio-logging
      - key: domain
        op: =
        value: minio-logging
      name: nv.logging-pool-0.minio-logging
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.logging-pool-0.minio-logging-ingress-61
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: loki-write.loki
      - key: domain
        op: =
        value: loki
      name: nv.loki-write.loki
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.logging-pool-0.minio-logging-ingress-62
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: minio-operator.minio-operator
      - key: domain
        op: =
        value: minio-operator
      name: nv.minio-operator.minio-operator
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: minio
    path: /usr/bin/minio
  - action: allow
    allow_update: false
    name: minio-operator
    path: /minio-operator
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: logging-pool-0.minio-logging
      - key: domain
        op: =
        value: minio-logging
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.logging-pool-0.minio-logging
      original_name: ''
  waf:
    settings: []
    status: true
