---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.prometheus-pushgateway.pushgateway
  namespace: pushgateway
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.35.60
      - key: domain
        op: =
        value: pushgateway
      - key: label
        op: =
        value: app.kubernetes.io/instance=prometheus-pushgateway
      - key: label
        op: =
        value: app.kubernetes.io/name=prometheus-pushgateway
      name: nv.ip.prometheus-pushgateway.pushgateway
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.prometheus-pushgateway.pushgateway
  namespace: pushgateway
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.prometheus-pushgateway.pushgateway-ingress-76
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      - key: domain
        op: =
        value: cattle-monitoring-system
      name: nv.prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: curl
    path: /usr/bin/curl
  - action: allow
    allow_update: false
    name: grep
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: pushgateway
    path: /bin/pushgateway
  - action: allow
    allow_update: false
    name: sh
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: sleep
    path: /bin/busybox
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-pushgateway.pushgateway
      - key: domain
        op: =
        value: pushgateway
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.prometheus-pushgateway.pushgateway
      original_name: ''
  waf:
    settings: []
    status: true
