---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.rke2-control-plane-controller-manager.rke2-control-plane-system
  namespace: rke2-control-plane-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.rke2-control-plane-controller-manager.rke2-control-plane-system-ingress-85
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: manager
    path: /manager
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-control-plane-controller-manager.rke2-control-plane-system
      - key: domain
        op: =
        value: rke2-control-plane-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.rke2-control-plane-controller-manager.rke2-control-plane-system
      original_name: ''
  waf:
    settings: []
    status: true
