---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.rke2-control-plane-controller-manager.rke2-control-plane-system
  namespace: rke2-control-plane-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-334
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: manager
    path: /manager
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-control-plane-controller-manager.rke2-control-plane-system
      - key: domain
        op: =
        value: rke2-control-plane-system
      name: nv.rke2-control-plane-controller-manager.rke2-control-plane-system
      original_name: ''
  waf:
    settings: []
    status: true
