---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.cluster-garbage-collector.sylva-system
  namespace: sylva-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: bash
    path: /bin/bash
  - action: allow
    allow_update: false
    name: grep
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: kubectl
    path: /usr/local/bin/kubectl
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: sed
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: wc
    path: /bin/busybox
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: cluster-garbage-collector.sylva-system
      - key: domain
        op: =
        value: sylva-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.cluster-garbage-collector.sylva-system
      original_name: ''
  waf:
    settings: []
    status: true
