---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.vault-0.vault
  namespace: vault
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.5.12
      - key: domain
        op: =
        value: vault
      - key: label
        op: =
        value: statefulset.kubernetes.io/pod-name=vault-0
      - key: label
        op: =
        value: vault_cr=vault
      - key: label
        op: =
        value: app.kubernetes.io/name=vault
      name: nv.ip.vault-0.vault
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.vault-1.vault
  namespace: vault
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.242.153
      - key: domain
        op: =
        value: vault
      - key: label
        op: =
        value: app.kubernetes.io/name=vault
      - key: label
        op: =
        value: statefulset.kubernetes.io/pod-name=vault-1
      - key: label
        op: =
        value: vault_cr=vault
      name: nv.ip.vault-1.vault
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.vault-2.vault
  namespace: vault
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.72.125
      - key: domain
        op: =
        value: vault
      - key: label
        op: =
        value: app.kubernetes.io/name=vault
      - key: label
        op: =
        value: statefulset.kubernetes.io/pod-name=vault-2
      - key: label
        op: =
        value: vault_cr=vault
      name: nv.ip.vault-2.vault
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.vault-config-operator-controller-manager-metrics-service.vault
  namespace: vault
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.113.137
      - key: domain
        op: =
        value: vault
      - key: label
        op: =
        value: control-plane=vault-config-operator
      name: nv.ip.vault-config-operator-controller-manager-metrics-service.vault
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.vault-config-operator-webhook-service.vault
  namespace: vault
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.89.240
      - key: domain
        op: =
        value: vault
      - key: label
        op: =
        value: control-plane=vault-config-operator
      name: nv.ip.vault-config-operator-webhook-service.vault
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.vault-configurer.vault
  namespace: vault
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.232.221
      - key: domain
        op: =
        value: vault
      - key: label
        op: =
        value: app.kubernetes.io/name=vault-configurator
      - key: label
        op: =
        value: vault_cr=vault
      name: nv.ip.vault-configurer.vault
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.vault-operator.vault
  namespace: vault
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.143.128
      - key: domain
        op: =
        value: vault
      - key: label
        op: =
        value: app.kubernetes.io/name=vault-operator
      name: nv.ip.vault-operator.vault
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.vault.vault
  namespace: vault
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.26.175
      - key: domain
        op: =
        value: vault
      - key: label
        op: =
        value: app.kubernetes.io/name=vault
      - key: label
        op: =
        value: vault-active=true
      - key: label
        op: =
        value: vault_cr=vault
      name: nv.ip.vault.vault
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.vault-config-operator.vault
  namespace: vault
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - SSL
    name: nv.vault.vault-egress-157
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault.vault
      - key: domain
        op: =
        value: vault
      name: nv.vault.vault
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.vault-config-operator.vault-ingress-98
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: manager
    path: /manager
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault-config-operator.vault
      - key: domain
        op: =
        value: vault
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.vault-config-operator.vault
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.vault-configurer.vault
  namespace: vault
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: bank-vaults
    path: /usr/local/bin/bank-vaults
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault-configurer.vault
      - key: domain
        op: =
        value: vault
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.vault-configurer.vault
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.vault-operator.vault
  namespace: vault
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - SSL
    name: nv.vault.vault-egress-158
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault.vault
      - key: domain
        op: =
        value: vault
      name: nv.vault.vault
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: vault-operator
    path: /usr/local/bin/vault-operator
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault-operator.vault
      - key: domain
        op: =
        value: vault
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.vault-operator.vault
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.vault.vault
  namespace: vault
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: bank-vaults
    path: /usr/local/bin/bank-vaults
  - action: allow
    allow_update: false
    name: dumb-init
    path: /usr/bin/dumb-init
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: vault
    path: /bin/vault
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: vault.vault
      - key: domain
        op: =
        value: vault
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.vault.vault
      original_name: ''
  waf:
    settings: []
    status: true
