---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.console.minio-operator
  namespace: minio-operator
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: minio-operator
    path: /minio-operator
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: console.minio-operator
      - key: domain
        op: =
        value: minio-operator
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.console.minio-operator
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.console.minio-operator
  namespace: minio-operator
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.80.43
      - key: domain
        op: =
        value: minio-operator
      - key: label
        op: =
        value: app.kubernetes.io/instance=minio-operator-console
      - key: label
        op: =
        value: app.kubernetes.io/name=operator
      name: nv.ip.console.minio-operator
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.operator.minio-operator
  namespace: minio-operator
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.134.145
      - key: domain
        op: =
        value: minio-operator
      - key: label
        op: =
        value: operator=leader
      - key: label
        op: =
        value: app.kubernetes.io/instance=minio-operator
      - key: label
        op: =
        value: app.kubernetes.io/name=operator
      name: nv.ip.operator.minio-operator
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.sts.minio-operator
  namespace: minio-operator
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.138.70
      - key: domain
        op: =
        value: minio-operator
      - key: label
        op: =
        value: app.kubernetes.io/instance=minio-operator
      - key: label
        op: =
        value: app.kubernetes.io/name=operator
      name: nv.ip.sts.minio-operator
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.minio-operator.minio-operator
  namespace: minio-operator
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-139
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.monitoring-pool-0.minio-monitoring-egress-140
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: monitoring-pool-0.minio-monitoring
      - key: domain
        op: =
        value: minio-monitoring
      name: nv.monitoring-pool-0.minio-monitoring
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: minio-operator
    path: /minio-operator
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: minio-operator.minio-operator
      - key: domain
        op: =
        value: minio-operator
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.minio-operator.minio-operator
      original_name: ''
  waf:
    settings: []
    status: true
