---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.thanos-compactor.thanos
  namespace: thanos
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.63.98
      - key: domain
        op: =
        value: thanos
      - key: label
        op: =
        value: app.kubernetes.io/component=compactor
      - key: label
        op: =
        value: app.kubernetes.io/instance=thanos
      - key: label
        op: =
        value: app.kubernetes.io/name=thanos
      name: nv.ip.thanos-compactor.thanos
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.thanos-query-frontend.thanos
  namespace: thanos
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.57.182
      - key: domain
        op: =
        value: thanos
      - key: label
        op: =
        value: app.kubernetes.io/component=query-frontend
      - key: label
        op: =
        value: app.kubernetes.io/instance=thanos
      - key: label
        op: =
        value: app.kubernetes.io/name=thanos
      name: nv.ip.thanos-query-frontend.thanos
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.thanos-query-grpc.thanos
  namespace: thanos
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.93.225
      - key: domain
        op: =
        value: thanos
      - key: label
        op: =
        value: app.kubernetes.io/component=query
      - key: label
        op: =
        value: app.kubernetes.io/instance=thanos
      - key: label
        op: =
        value: app.kubernetes.io/name=thanos
      name: nv.ip.thanos-query-grpc.thanos
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.thanos-query.thanos
  namespace: thanos
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.99.4
      - key: domain
        op: =
        value: thanos
      - key: label
        op: =
        value: app.kubernetes.io/name=thanos
      - key: label
        op: =
        value: app.kubernetes.io/component=query
      - key: label
        op: =
        value: app.kubernetes.io/instance=thanos
      name: nv.ip.thanos-query.thanos
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.thanos-receive.thanos
  namespace: thanos
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.87.3
      - key: domain
        op: =
        value: thanos
      - key: label
        op: =
        value: app.kubernetes.io/instance=thanos
      - key: label
        op: =
        value: app.kubernetes.io/name=thanos
      - key: label
        op: =
        value: app.kubernetes.io/component=receive
      name: nv.ip.thanos-receive.thanos
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.thanos-storegateway.thanos
  namespace: thanos
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.47.121
      - key: domain
        op: =
        value: thanos
      - key: label
        op: =
        value: app.kubernetes.io/instance=thanos
      - key: label
        op: =
        value: app.kubernetes.io/name=thanos
      - key: label
        op: =
        value: app.kubernetes.io/component=storegateway
      name: nv.ip.thanos-storegateway.thanos
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.thanos-compactor.thanos
  namespace: thanos
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: thanos
    path: /bin/thanos
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-compactor.thanos
      - key: domain
        op: =
        value: thanos
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.thanos-compactor.thanos
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.thanos-query-frontend.thanos
  namespace: thanos
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.thanos-query-frontend.thanos-ingress-96
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: thanos
    path: /bin/thanos
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-query-frontend.thanos
      - key: domain
        op: =
        value: thanos
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.thanos-query-frontend.thanos
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.thanos-query.thanos
  namespace: thanos
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - HTTP
    name: nv.thanos-storegateway.thanos-egress-153
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-storegateway.thanos
      - key: domain
        op: =
        value: thanos
      name: nv.thanos-storegateway.thanos
      original_name: ''
  - action: allow
    applications:
    - HTTP
    name: nv.thanos-receive.thanos-egress-154
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-receive.thanos
      - key: domain
        op: =
        value: thanos
      name: nv.thanos-receive.thanos
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.thanos-receive.thanos-egress-155
    ports: tcp/10901
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-receive.thanos
      - key: domain
        op: =
        value: thanos
      name: nv.thanos-receive.thanos
      original_name: ''
  - action: allow
    applications:
    - any
    name: nv.thanos-storegateway.thanos-egress-156
    ports: tcp/10901
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-storegateway.thanos
      - key: domain
        op: =
        value: thanos
      name: nv.thanos-storegateway.thanos
      original_name: ''
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.thanos-query.thanos-ingress-97
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: thanos
    path: /bin/thanos
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-query.thanos
      - key: domain
        op: =
        value: thanos
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.thanos-query.thanos
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.thanos-receive.thanos
  namespace: thanos
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: thanos
    path: /bin/thanos
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-receive.thanos
      - key: domain
        op: =
        value: thanos
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.thanos-receive.thanos
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.thanos-ruler.thanos
  namespace: thanos
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: configmap-reload
    path: /opt/bitnami/configmap-reload/bin/configmap-reload
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: thanos
    path: /bin/thanos
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-ruler.thanos
      - key: domain
        op: =
        value: thanos
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.thanos-ruler.thanos
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.thanos-storegateway.thanos
  namespace: thanos
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: thanos
    path: /bin/thanos
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: thanos-storegateway.thanos
      - key: domain
        op: =
        value: thanos
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.thanos-storegateway.thanos
      original_name: ''
  waf:
    settings: []
    status: true
