---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu-operator
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
<<<<<<< HEAD
<<<<<<< HEAD
=======
    
>>>>>>> ec730c1ee (add new line at the end of files, to pass linter)
=======
>>>>>>> 498f5a002 (yaml)
