apiVersion: v1
kind: Secret
metadata:
  name: hpe-storage-secrets
  namespace: hpe-storage
stringData:
  serviceName: primera3par-csp-svc
  servicePort: "8080"
  backend: "{BACKEND_IP}"
  username: "${USERNAME}"
  password: "${PASSWORD}"
type: Opaque
