kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: _unused_
rules:
  - apiGroups:
      - cluster.x-k8s.io
    verbs:
      - get
      - list
    resources:
      - machinedeployments
      - machinesets
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    verbs:
      - get
      - list
      - delete
    resources:
      - dockermachinetemplates
      - vspheremachinetemplates
      - openstackmachinetemplates
      - metal3machinetemplates
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    verbs:
      - get
      - list
    resources:
      - dockermachines
      - vspheremachines
      - openstackmachines
      - metal3machines
  - apiGroups:
      - controlplane.cluster.x-k8s.io
    verbs:
      - get
      - list
    resources:
      - kubeadmcontrolplanes
      - rke2controlplanes
      - agentcontrolplanes
  - apiGroups:
      - bootstrap.cluster.x-k8s.io
    verbs:
      - get
      - list
      - delete
    resources:
      - kubeadmconfigtemplates
      - rke2configtemplates
      - agentbootstrapconfigtemplates
  - apiGroups: [""]
    verbs:
      - get
      - list
      - create
    resources:
      - events
