apiVersion: batch/v1
kind: CronJob
metadata:
  name: _unused_
spec:
  schedule: "37 */3 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
