---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.fleet-cleanup-gitrepo-jobs.cattle-fleet-system
  namespace: cattle-fleet-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process: []
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: fleet-cleanup-gitrepo-jobs.cattle-fleet-system
      - key: domain
        op: =
        value: cattle-fleet-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.fleet-cleanup-gitrepo-jobs.cattle-fleet-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.fleet-controller.cattle-fleet-system
  namespace: cattle-fleet-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: fleetcontroller
    path: /usr/bin/fleetcontroller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: fleet-controller.cattle-fleet-system
      - key: domain
        op: =
        value: cattle-fleet-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.fleet-controller.cattle-fleet-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.gitjob.cattle-fleet-system
  namespace: cattle-fleet-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.gitjob.cattle-fleet-system-ingress-21
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      - key: domain
        op: =
        value: cattle-monitoring-system
      name: nv.prometheus-rancher-monitoring-prometheus.cattle-monitoring-system
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: fleetcontroller
    path: /usr/bin/fleetcontroller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: tini
    path: /usr/sbin/tini
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: gitjob.cattle-fleet-system
      - key: domain
        op: =
        value: cattle-fleet-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.gitjob.cattle-fleet-system
      original_name: ''
  waf:
    settings: []
    status: true
