---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.helm-operation.cattle-system
  namespace: cattle-system
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-115
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ''
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: helm-operation.cattle-system
      - key: domain
        op: =
        value: cattle-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.helm-operation.cattle-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.rancher-webhook.cattle-system
  namespace: cattle-system
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.213.239
      - key: domain
        op: =
        value: cattle-system
      - key: label
        op: =
        value: app=rancher-webhook
      name: nv.ip.rancher-webhook.cattle-system
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.ip.rancher.cattle-system
  namespace: cattle-system
spec:
  egress: []
  file: []
  ingress: []
  process: []
  target:
    policymode: N/A
    selector:
      comment: ''
      criteria:
      - key: address
        op: =
        value: 100.73.106.11
      - key: domain
        op: =
        value: cattle-system
      - key: label
        op: =
        value: app=rancher
      name: nv.ip.rancher.cattle-system
      original_name: ''
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.rancher-webhook.cattle-system
  namespace: cattle-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.rancher-webhook.cattle-system-ingress-81
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: webhook
    path: /usr/bin/webhook
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rancher-webhook.cattle-system
      - key: domain
        op: =
        value: cattle-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.rancher-webhook.cattle-system
      original_name: ''
  waf:
    settings: []
    status: true
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.rancher.cattle-system
  namespace: cattle-system
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - SSL
    name: nv.rancher.cattle-system-ingress-82
    ports: any
    priority: 0
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rancher.cattle-system
      - key: domain
        op: =
        value: cattle-system
      name: nv.rancher.cattle-system
      original_name: ''
  - action: allow
    applications:
    - SSL
    name: nv.rancher.cattle-system-ingress-83
    ports: any
    priority: 0
    selector:
      comment: ''
      name: Workload:ingress
      original_name: ''
  process:
  - action: allow
    allow_update: false
    name: cp
    path: /usr/bin/cp
  - action: allow
    allow_update: false
    name: git
    path: /usr/lib/git/git
  - action: allow
    allow_update: false
    name: jailer.sh
    path: /usr/bin/bash
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: rancher
    path: /usr/bin/rancher
  - action: allow
    allow_update: false
    name: tar
    path: /usr/bin/tar
  - action: allow
    allow_update: false
    name: tini
    path: /usr/bin/tini
  process_profile:
    baseline: zero-drift
  target:
    policymode: Monitor
    selector:
      comment: ''
      criteria:
      - key: service
        op: =
        value: rancher.cattle-system
      - key: domain
        op: =
        value: cattle-system
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.rancher.cattle-system
      original_name: ''
  waf:
    settings: []
    status: true
