apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crossplane-podmonitor
  namespace: crossplane-system
spec:
  selector:
    matchLabels:
      app: crossplane
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
