apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak-provider-config.yaml
  - func-deployment-runtime-config.yaml
  - keycloak-functions-extra-resources.yaml
  - sylva-xbuiltinobj.yaml
