# Maybe would be good to enforce a good format too ? I see that type can be ommited, it would produce a working schema in the end.
# Also we could add a header comment in this file to explain rapidly the use and how to interact with this document

metal3:
  _meta:
    additionalProperties: false
  ironicKernelParams:
    type: string
    description: Raw override (if provided, takes precedence)
    upstream_path: .units.metal3.helmrelease_spec.values.global.ironicKernelParams
    example: console=ttyS0 suse.autologin=ttyS0 rootpwd="..."
    doc_only: false  # shown in doc, optional

loki:
  testing:
    type: string

another-unit:
  someparams:
    properties:
      param1:
        description: ""
      param2:
        description: ""


