---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: gitea-postgres-secrets
   annotations:
      kustomize.toolkit.fluxcd.io/force: Enabled
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   refreshInterval: 0s  # `vault-config-operator` can create new versions (>1) of the Vault secret/rancher value and ESO would by default sync that in Rancher's bootstrap secret, but Rancher app itself would only be using the initial version 1; this stops new version sync
   target:
      creationPolicy: Orphan
      name: gitea-postgres-secrets
   data:
   - secretKey: admin-password
     remoteRef:
        key: secret/data/${CLUSTER_NAME:management-cluster}/gitea-postgres-postgres-passwd
        property: password
   - secretKey: password
     remoteRef:
        key: secret/data/${CLUSTER_NAME:management-cluster}/gitea-postgres-gitea-passwd
        property: password
   - secretKey: postgres-password
     remoteRef:
        key: secret/data/${CLUSTER_NAME:management-cluster}/gitea-postgres-postgres-passwd
        property: password
   - secretKey: repmgr-password
     remoteRef:
        key: secret/data/${CLUSTER_NAME:management-cluster}/gitea-postgres-replication-passwd
        property: password
