apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: felix-configuration-annotations
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Update felixConfiguration annotations and labels
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Updates felixConfiguration annotations and labels to be imported in Helm
spec:
  background: true
  webhookTimeoutSeconds: 30
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: update-annotations
      match:
        any:
        - resources:
            kinds:
              - FelixConfiguration
      mutate:
        targets:
          - apiVersion: crd.projectcalico.org/v1
            kind: FelixConfiguration
            name: default
        patchStrategicMerge:
          metadata:
            labels:
              app.kubernetes.io/managed-by: Helm
            annotations:
              meta.helm.sh/release-name: rke2-calico
              meta.helm.sh/release-namespace: kube-system

