apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kube-job

configMapGenerator:
- name: kube-job-cm
  behavior: merge
  options:
    disableNameSuffixHash: true
  files:
  - kube-job.sh=cluster-rke2-migrate-legacy-etcd-certs.sh

patches:
- target:
    kind: Job
  path: job.yaml

- target:
    kind: ClusterRole
  patch: |
    - op: add
      path: /rules/-
      value:
        apiGroups: ["controlplane.cluster.x-k8s.io"]
        resources: ["rke2controlplanes"]
        verbs: ["list","get","patch"]
    - op: add
      path: /rules/-
      value:
        apiGroups: [""]
        resources: ["secrets"]
        verbs: ["list","get","create","patch","update","watch"]
