kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: _unused_
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - patch
      - update
      - delete
      - get
      - list
