apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: capi-pdb
  namespace: capi-system
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: cluster-api
      control-plane: controller-manager
