apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: reconcile-neuvector-helmrelease
  namespace: sylva-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Reconcile Neuvector HelmRelease
    policies.kyverno.io/minversion: 1.12.0
    policies.kyverno.io/description: >-
      Reconcile neuvector HelmRelease when neuvector-federation-* is created, excluding sylva-system namespace
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: reconcile-neuvector-helmrelease
      match:
        any:
          - resources:
              kinds:
              - HelmRelease
              names:
              - neuvector
              namespaces:
              - "*"
      exclude:
        any:
          - resources:
              namespaces:
                - sylva-system
      context:
        - name: configMapData
          apiCall:
            urlPath: "/api/v1/namespaces/{{ request.object.metadata.namespace }}/configmaps/neuvector-federation-{{ request.object.metadata.namespace }}"  # Utilisation de l'interpolation
            jmesPath: "data.fedinitcfg.yaml"  # Récupère les données du ConfigMap
      mutate:
        targets:
          - apiVersion: helm.toolkit.fluxcd.io/v2
            kind: HelmRelease
            name: neuvector
            namespace: "{{ request.object.metadata.namespace }}"
        patchesJson6902: |-
          - op: add
            path: /spec/values/controller/configmap/data/fedinitcfg.yaml
            value: {{ configMapData | toJson }}  # Injecte les données du ConfigMap
          - op: add
            path: /spec/metadata/annotations/reconcile.fluxcd.io~1requestedAt
            value: "{{ time_now_utc() }}"
          - op: add
            path: /spec/metadata/annotations/kyverno.reconcile-neuvector-helmrelease~1requestedAt
            value: "{{ time_now_utc() }}"
