---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: "${NAMESPACE:-sylva-system}"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 1800
  template:
    metadata:
      annotations:
        checksum: s${JOB_CHECKSUM}  # s prefix to avoid this turning into a number if we're unlucky
    spec:
      containers:
      - name: run-script
        image: registry.gitlab.com/sylva-projects/sylva-elements/container-images/kube-job:v1.1.1
        command: ["/bin/sh", "-c", "/opt/kube-job.sh"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: ${RUNASUSER:-1000}
          runAsGroup: ${RUNASGROUP:-1000}
          privileged: false
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /opt/
          name: script-volume
      restartPolicy: Never
      serviceAccountName: ${JOB_NAME}-sa
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: script-volume
        configMap:
          name: kube-job-cm
          defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${JOB_NAME}-sa
  namespace: "${NAMESPACE:-sylva-system}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${JOB_NAME}
  namespace: "${NAMESPACE:-sylva-system}"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${JOB_NAME}
  namespace: "${NAMESPACE:-sylva-system}"
subjects:
- kind: ServiceAccount
  name: ${JOB_NAME}-sa
roleRef:
  kind: Role
  name: ${JOB_NAME}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-job-${JOB_NAME}-${NAMESPACE:-sylva-system}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-job-${JOB_NAME}-${NAMESPACE:-sylva-system}
subjects:
- kind: ServiceAccount
  name: ${JOB_NAME}-sa
  namespace: "${NAMESPACE:-sylva-system}"
roleRef:
  kind: ClusterRole
  name: kube-job-${JOB_NAME}-${NAMESPACE:-sylva-system}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-job-cm
  # namespace: ${NAMESPACE}  ## we don't do this, because `kustomize.toolkit.fluxcd.io/substitute: disabled` won't let us, we patch the namespace in the unit definition instead
  labels:
    kube-job: script
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
data:
  kube-job.sh: |
    echo "noop kube-job script"
    sleep 5
    exit 1
