apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Deletes a pod belonging to a deployment/statefulset/daemonset
kind: ChaosExperiment
metadata:
  name: '${SERVICE_NAME}'
  namespace: '${NAMESPACE}'
  labels:
    name: pod-delete
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: 3.4.0
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "apps"
          - "apps.openshift.io"
          - "argoproj.io"
          - "batch"
          - "litmuschaos.io"
        resources:
          - "deployments"
          - "jobs"
          - "pods"
          - "pods/log"
          - "replicationcontrollers"
          - "deployments"
          - "statefulsets"
          - "daemonsets"
          - "replicasets"
          - "deploymentconfigs"
          - "rollouts"
          - "pods/exec"
          - "events"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
          - "deletecollection"
    image: 'litmuschaos/go-runner:3.4.0'
    imagePullPolicy: 'IfNotPresent'
    args:
    - -c
    - ./experiments -name pod-delete
    command:
    - /bin/bash
    env:

    - name: TOTAL_CHAOS_DURATION
      value: '${TOTAL_CHAOS_DURATION}'

    # Period to wait before and after injection of chaos in sec

    - name: RAMP_TIME
      value: ''

    - name: FORCE
      value: 'true'

    - name: CHAOS_INTERVAL
      value: '${CHAOS_INTERVAL}'

    - name: TARGET_PODS
      value: '${TARGET_PODS}'

    # pod failures without '--force' & default terminationGracePeriodSeconds
    - name: FORCE
      value: 'false'

    ## percentage of total pods to target
    - name: PODS_AFFECTED_PERC
      value: '${PODS_AFFECTED_PERC}'

    - name: LIB
      value: 'litmus'

    - name: LIB_IMAGE
      value: 'litmuschaos/go-runner:3.4.0'

    - name: LIB_IMAGE_PULL_POLICY
      value: 'IfNotPresent'

    ## it defines the sequence of chaos execution for multiple target pods
    ## supported values: serial, parallel
    - name: SEQUENCE
      value: '${SEQUENCE}'

    labels:
      name: pod-delete
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: 3.4.0
