apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vmware-system-csi

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v3.7.1/manifests/vanilla/vsphere-csi-driver.yaml
  - storageClass.yaml
  - vsphere-config-secret.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: vsphere-csi-controller
      namespace: vmware-system-csi
    patch: |-
      - op: replace
        path: /spec/replicas
        value: ${CONTROLLER_REPLICAS}

images:
- name: gcr.io/cloud-provider-vsphere/csi/release/driver
  newName: registry.k8s.io/csi-vsphere/driver
- name: gcr.io/cloud-provider-vsphere/csi/release/syncer
  newName: registry.k8s.io/csi-vsphere/syncer
