---
cluster:
  capi_providers:
    bootstrap_provider: cabpr

  capm3:
    os_image_selector:
      os: leapmicro
      os-release: "6.0"
      flavor: plain
      hardened: false

  rke2:
    additionalUserData:
      config:
        variant: fcos
        version: 1.4.0
        passwd:
          users:
            - name: root
              password_hash: $y$j9T$G8c3oUJT8Dekv2eIu/BBa1$mszH1TU0Xd3chgLh..Gb3IaTZxVmrcUmext0YZfeI1C

  baremetal_hosts:
    management-cp-0:
      ip_preallocations:
        primary: 192.168.100.20
        provisioning: 192.168.10.20
      interface_mappings:
        nic2:
          mac_address: 52:54:00:55:55:00
    management-cp-1:
      ip_preallocations:
        primary: 192.168.100.21
        provisioning: 192.168.10.21
      interface_mappings:
        nic1:
          mac_address: 52:54:00:44:44:01
    management-cp-2:
      ip_preallocations:
        primary: 192.168.100.22
        provisioning: 192.168.10.22
    management-md-0:
      ip_preallocations:
        primary: 192.168.100.23
        provisioning: 192.168.10.23
