apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests.yaml

components:
  - ../components/common
  - ../components/bootstrap
  - ../components/substituted-proxy-env-vars