apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- ../kube-job

configMapGenerator:

- name: kube-job-cm
  behavior: merge
  options:
    disableNameSuffixHash: true
  files:
  - kube-job.sh=patch-metallb.sh
