apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: root-fsgroup-okd-assisted-installer
  namespace: assisted-installer
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Use root fsGroup for StatefulSet/assisted-image-service and Deployment/assisted-service pods
    policies.kyverno.io/description: >-
      Apply `securityContext.fsGroup: 0` to allow for Longhorn volume permission shift to 2775/drwxrwsr-x
spec:
  failurePolicy: Ignore
  rules:
  - name: root-fsgroup-okd-assisted-installer
    match:
      any:
      - resources:
          kinds:
          - StatefulSet
          names:
          - assisted-image-service
      - resources:
          kinds:
          - Deployment
          names:
          - assisted-service
          # when operations[] is absent, the default behavior is to match on CREATE and UPDATE requests
    mutate:
      patchStrategicMerge:
        spec:
          template:
            spec:
              securityContext:
                fsGroup: 0
