apiVersion: v1
kind: Secret
metadata:
  name: backup-store-s3
  namespace: ${NAMESPACE:-sylva-system}
  labels:
    app: backup
data:
  S3_HOST: ${S3_HOST}
  S3_BUCKET: ${S3_BUCKET}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_SECRET_KEY: ${S3_SECRET_KEY}
  S3_CERT: ${S3_CERT}
