---
apiVersion: v1
kind: Namespace
metadata:
  name: testns
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-cert-config
  namespace: testns
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIID...your-certificate-content...IDAQAB
    ${ca.crt}
    -----END CERTIFICATE-----
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ca-cert-installer
  namespace: testns
spec:
  selector:
    matchLabels:
      app: ca-cert-installer
  template:
    metadata:
      labels:
        app: ca-cert-installer
    spec:
          #hostPID: true
      containers:
        - name: pause
          image: gcr.io/google-containers/pause:3.2
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: host-anchors
              mountPath: /host/etc/pki/trust/anchors
      initContainers:
        - name: install-ca-cert
          image: busybox:1.37.0
          command:
            - sh
            - -c
            - cp /config/ca.crt /host/etc/pki/trust/anchors/ca.crt
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: host-anchors
              mountPath: /host/etc/pki/trust/anchors
            - name: ca-cert
              mountPath: /config
      volumes:
        - name: host-anchors
          hostPath:
            path: /etc/pki/trust/anchors
            type: DirectoryOrCreate
        - name: ca-cert
          configMap:
            name: ca-cert-config
