apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restart-deployment-on-secret-change
  namespace: vault
  annotations:
    policies.kyverno.io/description: >-
      This policy monitors the vault-internal-tls secret and will set up the annotations in sts so that pods are restarted
      and takes the updated cert after expiration of old one.
spec:
  rules:
    - name: update-secret
      match:
        any:
          - resources:
              kinds:
                - Secret
              names:
                - vault-internal-tls
              operations:
                - UPDATE
      mutate:
        targets:
          - apiVersion: apps/v1
            kind: StatefulSet
            name: vault
            namespace: vault
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  vault-certs: "{{ request.object.metadata.resourceVersion }}"
