apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: thanos-aggregated-secret
  namespace: sylva-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Aggreate thanos credentials
    policies.kyverno.io/minversion: 1.11.0
    policies.kyverno.io/description: >-
      Aggregate thanos credentials from various (workload) cluster namespaces
      into a secret that is usable by thanos HelmRelease
    sylva.org/kyverno-exclude-kube-system: add-matchCondition
spec:
  generateExisting: true
  webhookConfiguration:
    matchConditions:
    - name: is-thanos-secret
      expression: "has(object.metadata) && has(object.metadata.labels) && 'sylva.io/aggregated-secret' in object.metadata.labels && object.metadata.labels['sylva.io/aggregated-secret'] == 'thanos'"
  rules:
  - name: thanos-aggregated-secret
    match:
      any:
      - resources:
          kinds:
          - Secret
          selector:
            matchLabels:
              sylva.io/aggregated-secret: thanos
    context:
    - name: tenantMap
      apiCall:
        urlPath: "/api/v1/secrets?labelSelector=sylva.io/aggregated-secret=thanos"
        jmesPath: "object_from_lists(items[].data.base64_decode(username), items[].data.base64_decode(password))"
      # Build a config that matches the chart values format, so that secret can be merged as is
      # to the chart values (without specifying targetPath, otherwise values would be injected as a string)
      # Secret content will have the following structure:
      #   auth:
      #     basicAuthUsers:
      #       management-cluster: foo
      #       test-workload1: bar
    - name: thanosConfig
      variable:
        value:
          auth:
            basicAuthUsers: "{{ tenantMap }}"
    generate:
      synchronize: true
      apiVersion: v1
      kind: Secret
      name: thanos-secrets
      namespace: sylva-system
      data:
        type: Opaque
        data:
          secrets: "{{ thanosConfig | to_string(@) | base64_encode(@) }}"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: reconcile-thanos-helmrelease
  namespace: sylva-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Reconcile sylve-units HelmReleases
    policies.kyverno.io/minversion: 1.12.0
    policies.kyverno.io/description: >-
      Reconcile thanos HelmRelease when thanos-secrets is updated
    sylva.org/kyverno-exclude-kube-system: add-matchCondition
spec:
  mutateExistingOnPolicyUpdate: true
  webhookConfiguration:
    matchConditions:
    - name: is-thanos-aggregated-secret
      expression: "has(object.metadata) && object.metadata.namespace == 'sylva-system' && object.metadata.name == 'thanos-secrets'"
  rules:
  - name: reconcile-thanos-helmrelease
    skipBackgroundRequests: false # Required here as we match a resource generated by background controller in previous policy
    match:
      any:
      - resources:
          kinds:
          - Secret
          namespaces:
          - sylva-system
          names:
          - thanos-secrets
    context:
    - name: thanosHelmReleaseExists
      apiCall:
        urlPath: "/apis/helm.toolkit.fluxcd.io/v2/namespaces/sylva-system/helmreleases/thanos"
    preconditions:
      all:
      - key: "{{ thanosHelmReleaseExists.metadata.name }}"
        operator: Equals
        value: "thanos"
    mutate:
      targets:
      - apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        name: thanos
        namespace: sylva-system
      patchStrategicMerge:
        metadata:
          annotations:
            reconcile.fluxcd.io/requestedAt: "{{ time_now_utc() }}"
            kyverno.reconcile-thanos-helmrelease/requestedAt: "{{ time_now_utc() }}"
