---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-reviewer-sa
  namespace: vault
  labels:
    role: vault-token-review-for-k8s-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: token-reviewer-sa
  namespace: vault
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-k8s-auth-secret
  namespace: vault
  annotations:
    kubernetes.io/service-account.name: token-reviewer-sa
type: kubernetes.io/service-account-token
