---
apiVersion: v1
kind: Namespace
metadata:
  name: stress
  labels:
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: stress
  namespace: stress
spec:
  selector:
    matchLabels:
      app: stress
  replicas: ${REPLICAS:-1}
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
        - name: stress-po
          image: nginx:1.25.5-alpine-slim
