apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minio-tenant-root-random-secret.yaml
  - minio-tenant-root-external-secret.yaml
  - minio-tenant-user-random-secret.yaml
  - minio-tenant-user-external-secret.yaml
  - minio-tenant-internal-certificate.yaml
