---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: ${TENANT_NAME}-user
   namespace: ${TENANT_NAME}
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   target:
      creationPolicy: Orphan
      name: ${TENANT_NAME}-user
      template:
         type: Opaque
         data:
            CONSOLE_ACCESS_KEY: ${TENANT_NAME}-user
            CONSOLE_SECRET_KEY: "{{ .password | toString }}"
   data:
   - secretKey: password
     remoteRef:
        key: secret/data/${TENANT_NAME}-user
        property: password
