---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: ${TENANT_NS}-user
   namespace: ${TENANT_NS}
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   target:
      creationPolicy: Orphan
      name: ${TENANT_NS}-user
      template:
         type: Opaque
         data:
            CONSOLE_ACCESS_KEY: ${TENANT_NS}-user
            CONSOLE_SECRET_KEY: "{{ .password | toString }}"
   data:
   - secretKey: password
     remoteRef:
        key: ${SECRET_PATH}/data/${TENANT_NS}-user-password
        property: password
