---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: backup-minio-user
   namespace: ${NAMESPACE:-sylva-system}
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   target:
      creationPolicy: Orphan
      name: backup-store-s3-${CRONJOB_NAME}
      template:
         type: Opaque
         data:
            S3_ACCESS_KEY: minio-backup-user
            S3_SECRET_KEY: "{{ .password | toString }}"
   data:
   - secretKey: password
     remoteRef:
        key: secret/data/minio-backup-user-password
        property: password
