apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sylva-system

resources:
  - ../base

buildMetadata:
  - originAnnotations

# Generate empty secret & configmap to let kustomize overlays & descendants add data with 'behavior: merge'

configMapGenerator:
  - name: sylva-units-values
    behavior: merge
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: sylva-units-secrets
    behavior: merge
    options:
      disableNameSuffixHash: true

# Apply the patch to modify the CronJob schedule
patches:
  - target:
      kind: CronJob
      name: batch-cronjob
    path: patch-cronjobs-policy.yaml
