---
# ---
# unit_templates:
#   kube-cronjob:
#     kustomization_spec:
#       patches:
#         - target:
#             kind: Cronjob
#           patch: |
#             - op: replace
#               path: /spec/schedule
#               value: "*/9 * * * *"

# patch-cronjobs-policy.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-cronjob
spec:
  schedule: "*/7 * * * *"
