apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: avoid-delete-mgmt-resources-flux
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    sylva.org/kyverno-exclude-kube-system: add-matchCondition
spec:
  background: false
  webhookConfiguration:
    matchConditions:
    - name: is-delete
      expression: request.operation == "DELETE"
    - name: match-label
      expression: >-
        has(oldObject.metadata) && has(oldObject.metadata.labels) && 'sylva-units/protected' in oldObject.metadata.labels
  rules:
  - name: helm-resources
    match:
      any:
      - resources:
          kinds:
          - helm.toolkit.fluxcd.io/*/HelmRelease
          - kustomize.toolkit.fluxcd.io/*/Kustomization
    validate:
      message: This is a mandatory resource, deleting it is not possible without breaking the Sylva management cluster.
      deny: {}
  validationFailureAction: Enforce
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: avoid-delete-mgmt-resources-capi
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    sylva.org/kyverno-exclude-kube-system: add-matchCondition
spec:
  background: false
  webhookConfiguration:
    matchConditions:
    - name: is-delete
      expression: request.operation == "DELETE"
    - name: match-ns
      expression: >-
        has(oldObject.metadata) && oldObject.metadata.namespace == "sylva-system"
  rules:
  - name: cluster-resources
    match:
      any:
      - resources:
          kinds:
          - cluster.x-k8s.io/*/Cluster
          - controlplane.cluster.x-k8s.io/*/*
    validate:
      message: Deleting the Sylva CAPI resources that describe the Cluster API cluster for the management cluster is not possible without breaking the Sylva management cluster.
      deny: {}
  validationFailureAction: Enforce
