apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: avoid-delete-mgmt-resources-flux
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  background: false
  webhookConfiguration:
    matchConditions:
    - name: is-delete
      expression: request.operation == "DELETE"
    - name: match-namespace
      expression: request.namespace == "sylva-system"
    - name: match-kinds
      expression: >-
        (request.resource.group == "helm.toolkit.fluxcd.io"      && request.resource.resource == "helmreleases")   ||
        (request.resource.group == "kustomize.toolkit.fluxcd.io" && request.resource.resource == "kustomizations")
    - name: match-names
      expression: >-
        request.name in [
          "cluster",
          "cluster-bmh",
        ]
  rules:
  - name: helm-resources
    match:
      any:
      - resources:  # repeat of .webhookConfiguration.matchConditions because Kyverno won't let us omit match.xx.resources.kind
          kinds:
          - helm.toolkit.fluxcd.io/*/HelmRelease
          - kustomize.toolkit.fluxcd.io/*/Kustomization
    validate:
      message: Deleting the Flux resources that describe the Sylva management cluster is not possible without breaking the Sylva management cluster.
      deny: {}
  validationFailureAction: Enforce
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: avoid-delete-mgmt-resources-capi
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  background: false
  webhookConfiguration:
    matchConditions:
    - name: is-delete
      expression: request.operation == "DELETE"
    - name: match-namespace
      expression: request.namespace == "sylva-system"
    - name: match-kinds
      expression: >-
        (request.resource.group == "cluster.x-k8s.io" && request.resource.resource == "clusters") ||
        (request.resource.group == "controlplane.cluster.x-k8s.io")
  rules:
  - name: cluster-resources
    match:
      any:
      - resources:
          kinds:  # repeat of .webhookConfiguration.matchConditions because Kyverno won't let us omit match.xx.resources.kind
          - cluster.x-k8s.io/*/Cluster
          - "controlplane.cluster.x-k8s.io/*/*"
    validate:
      message: Deleting the Sylva CAPI resources that describe the Cluster API cluster for the management cluster is not possible without breaking the Sylva management cluster.
      deny: {}
  validationFailureAction: Enforce
