apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: cluster-api-to-vip
spec:
  order: 40
  preDNAT: true
  applyOnForward: true
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: cluster.x-k8s.io/provider == 'cluster-api'
    destination:
      nets:
      - ${CLUSTER_VIRTUAL_IP}
      ports:
      - 6443
