apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: merge-neuvector-secrets
  namespace: sylva-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Merge Neuvector secrets for OIDC
    policies.kyverno.io/minversion: 1.12.0
    policies.kyverno.io/description: >-
      Merge neuvector secrets to create init config
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: merge-neuvector-secrets
    match:
      any:
        - resources:
            kinds:
            - Secret
            namespaces:
            - neuvector
            names:
            - neuvector-oidc-init
            - neuvector-usercfg
    context:
      - name: oidcNeuvector
        apiCall:
          urlPath: "/api/v1/namespaces/neuvector/secrets/neuvector-oidc-init"
          jmesPath: "data.oidcinitcfg || `{}`"
      - name: passwordprofileinitcfg
        apiCall:
          urlPath: "/api/v1/namespaces/neuvector/secrets/neuvector-usercfg"
          jmesPath: "data.passwordprofileinitcfg || `{}`"
      - name: userinitcfg
        apiCall:
          urlPath: "/api/v1/namespaces/neuvector/secrets/neuvector-usercfg"
          jmesPath: "data.userinitcfg || `{}`"
    generate:
      apiVersion: v1
      kind: Secret
      name: neuvector-init
      namespace: neuvector
      data:
        metadata:
          annotations:
            reconcile.fluxcd.io/requestedAt: "{{ time_now_utc() }}"
            kyverno.merge-neuvector-secrets/requestedAt: "{{ time_now_utc() }}"
        data:
          oidcinitcfg.yaml: |
            {{ oidcNeuvector }}
          passwordprofileinitcfg.yaml: |
            {{ passwordprofileinitcfg }}
          userinitcfg.yaml: |
            {{ userinitcfg }}

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-sylva-ca
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  rules:
  - name: add-sylva-ca
    match:
      resources:
        kinds:
        - Deployment
        names:
        - neuvector-controller-pod
        namespaces:
        - neuvector
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            name: "{{request.object.metadata.name}}"
        spec:
          template:
            spec:
              containers:
                - name: neuvector-controller-pod
                  volumeMounts:
                    - name: keycloak-ca
                      mountPath: /etc/ssl/certs
              volumes:
                - name: keycloak-ca
                  secret:
                    secretName: sylva-ca.crt
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: reconcile-neuvector-helmrelease
  namespace: sylva-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Reconcile Neuvector HelmRelease
    policies.kyverno.io/minversion: 1.12.0
    policies.kyverno.io/description: >-
      Reconcile neuvector HelmRelease when neuvector-federation-* is created, excluding sylva-system namespace
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: reconcile-neuvector-helmrelease
      match:
        any:
          - resources:
              kinds:
              - HelmRelease
              names:
              - neuvector
              namespaces:
              - "*"
      exclude:
        any:
          - resources:
              namespaces:
                - sylva-system
      context:
        - name: configMapData
          apiCall:
            urlPath: "/api/v1/namespaces/neuvector/configmaps?labelSelector=kustomize.toolkit.fluxcd.io/name=neuvector-federation-generate-workload-config,kustomize.toolkit.fluxcd.io/namespace={{ request.namespace }}"
            jmesPath: "items[0]"
      mutate:
        targets:
          - apiVersion: helm.toolkit.fluxcd.io/v2
            kind: HelmRelease
            name: neuvector
            namespace: "{{ request.namespace }}"
        patchStrategicMerge:
          metadata:
            annotations:
              reconcile.fluxcd.io/requestedAt: "{{ time_now_utc() }}"
              kyverno.reconcile-neuvector-helmrelease/requestedAt: "{{ time_now_utc() }}"
          spec:
            values:
              controller:
                configmap:
                  data:
                    fedinitcfg.yaml: |
                      {{ configMapData.data.fedinitcfg }}
