apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: merge-neuvector-secrets
  namespace: sylva-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Merge Neuvector secrets for OIDC
    policies.kyverno.io/minversion: 1.12.0
    policies.kyverno.io/description: >-
      Merge neuvector secrets when neuvector-oidc-init is created
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: merge-neuvector-secrets
      match:
        any:
          - resources:
              kinds:
              - Secret
              names:
              - neuvector-oidc-init
              namespaces:
              - neuvector
      context:
        - name: oidcNeuvector
          apiCall:
            urlPath: "/api/v1/namespaces/neuvector/secrets/neuvector-oidc-init"
            jmesPath: "data.oidcinitcfg | base64_decode(@) || `{}`"
        - name: passwordprofileinitcfg
          apiCall:
            urlPath: "/api/v1/namespaces/neuvector/secrets/neuvector-usercfg"
            jmesPath: "data.passwordprofileinitcfg | base64_decode(@) || `{}`"
        - name: userinitcfg
          apiCall:
            urlPath: "/api/v1/namespaces/neuvector/secrets/neuvector-usercfg"
            jmesPath: "data.userinitcfg | base64_decode(@) || `{}`"
      mutate:
        targets:
          - apiVersion: v1
            kind: Secret
            name: neuvector-init
            namespace: neuvector
        patchStrategicMerge:
          metadata:
            annotations:
              reconcile.fluxcd.io/requestedAt: "{{ time_now_utc() }}"
              kyverno.merge-neuvector-secrets/requestedAt: "{{ time_now_utc() }}"
          data:
              oidcinitcfg.yaml: |
                {{ oidcNeuvector }}
              passwordprofileinitcfg.yaml: |
                {{ passwordprofileinitcfg }}
              userinitcfg.yaml: |
                {{ userinitcfg }}

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-sylva-ca
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  rules:
  - name: add-sylva-ca
    match:
      resources:
        kinds:
        - Deployment
        names:
        - neuvector-controller-pod
        namespaces:
        - neuvector
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            name: "{{request.object.metadata.name}}"
        spec:
          template:
            spec:
              containers:
                - name: neuvector-controller-pod
                  volumeMounts:
                    - name: keycloak-ca
                      mountPath: /etc/ssl/certs
              volumes:
                - name: keycloak-ca
                  secret:
                    secretName: sylva-ca.crt
