apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: reconcile-neuvector-oidc-helmrelease
  namespace: sylva-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Reconcile Neuvector HelmRelease for OIDC
    policies.kyverno.io/minversion: 1.12.0
    policies.kyverno.io/description: >-
      Reconcile neuvector HelmRelease when neuvector-oidc-init is created
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: reconcile-neuvector-oidc-helmrelease
      match:
        any:
          - resources:
              kinds:
              - HelmRelease
              names:
              - neuvector
              namespaces:
              - sylva-system
      context:
        - name: oidcNeuvector
          apiCall:
            urlPath: "/api/v1/namespaces/neuvector/secrets/neuvector-oidc-init"
            jmesPath: "data.oidcinitcfg | base64_decode(@) || `{}`"
      mutate:
        targets:
          - apiVersion: helm.toolkit.fluxcd.io/v2
            kind: HelmRelease
            name: neuvector
            namespace: "{{ request.namespace }}"
        patchStrategicMerge:
          metadata:
            annotations:
              reconcile.fluxcd.io/requestedAt: "{{ time_now_utc() }}"
              kyverno.reconcile-neuvector-oidc-helmrelease/requestedAt: "{{ time_now_utc() }}"
          spec:
            values:
              controller:
                configmap:
                  data:
                    oidcinitcfg.yaml: |
                      {{ oidcNeuvector }}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-sylva-ca
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  rules:
  - name: add-sylva-ca
    match:
      resources:
        kinds:
        - Deployment
        names:
        - neuvector-controller-pod
        namespaces:
        - neuvector
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            name: "{{request.object.metadata.name}}"
        spec:
          template:
            spec:
              containers:
                - name: neuvector-controller-pod
                  volumeMounts:
                    - name: keycloak-ca
                      mountPath: /etc/ssl/certs
              volumes:
                - name: keycloak-ca
                  secret:
                    secretName: sylva-ca.crt
