apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: cluster-secrets
  namespace: vault
spec:
  authentication:
    path: kubernetes
    role: admin
    serviceAccount:
      name: vault
  connection:
    address: https://vault.vault.svc.cluster.local:8200
    tLSConfig:
      skipVerify: true
  path: kubernetes
  policies:
    - cluster-secrets
  targetNamespaces:
    targetNamespaces:
      - vault
  targetServiceAccounts:
    - cluster-secrets-sa
  tokenTTL: 3600
  tokenType: default
