apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: cluster-secrets
  namespace: vault
spec:
  authentication:
    path: kubernetes
    role: admin
    serviceAccount:
      name: vault
  connection:
    address: https://vault.vault.svc.cluster.local:8200
    tLSConfig:
      skipVerify: true
  type: acl
  policy: |

    path "sys/auth" {
      capabilities = ["read", "list"]
    }

    # query existing mounts
    path "/sys/mounts" {
      capabilities = [ "list", "read"]
      allowed_parameters = {
        "type" = ["kv"]
        "*"   = []
      }
    }

    path "/sys/mounts/${CLUSTER_SECRETS_STORE:-cluster-secrets}" {
      capabilities = [ "create", "read", "update", "delete", "list", "sudo" ]
    }
