apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: ${CLUSTER_SECRETS_STORE:-cluster-secrets}
  namespace: vault
spec:
  authentication:
    path: kubernetes
    role: cluster-secrets
    serviceAccount:
      name: cluster-secrets-sa
  config:
    forceNoCache: false
    listingVisibility: hidden
    defaultLeaseTTL: 3600s
    maxLeaseTTL: 3600s
  connection:
    address: https://vault.vault.svc.cluster.local:8200
    tLSConfig:
      skipVerify: true
  type: kv
  options:
    version: "2"
