# the management cluster has all units defined in values.yaml
# (except the ones explicitly set 'enabled: false' in values.yaml
#  and not explicitely set 'enabled: false' here)
units_enabled_default: true

unit_templates:
  # this unit template gather depends_on common
  # to most units
  base-deps:
    depends_on:
      # Flux, because starting unit reconciliation while Flux is
      #       reinstalling itself proved fragile in the past
      flux-system: true
      # Kyverno, because we're introducing Kyverno policies that manage pod
      #          security settings that need to be in place before things can start up
      #kyverno: true

units:

  capd:
    enabled: '{{ .Values.cluster.capi_providers.infra_provider | eq "capd" }}'

  capo:
    enabled: '{{ .Values.cluster.capi_providers.infra_provider | eq "capo" }}'

  capm3:
    enabled: '{{ .Values.cluster.capi_providers.infra_provider | eq "capm3" }}'

  metal3:
    enabled: '{{ tuple . "capm3" | include "unit-enabled" }}'

  capv:
    enabled: '{{ .Values.cluster.capi_providers.infra_provider | eq "capv" }}'

  cabpk:  # kubeadm
    enabled: '{{ .Values.cluster.capi_providers.bootstrap_provider | eq "cabpk" }}'

  cabpr:  # RKE2
    enabled: '{{ .Values.cluster.capi_providers.bootstrap_provider | eq "cabpr" }}'

  get-openstack-images:
    depends_on:
      '{{ .Values._internal.default_storage_class_unit }}': true

  cluster-bmh:
    depends_on:
      metal3: '{{ .Values.cluster.capi_providers.infra_provider | eq "capm3" }}'

  cluster:
    depends_on:
      # these dependencies are set here rather than in values.yaml, because slightly different ones
      # need to be declared for workload clusters in workload-cluster.values.yaml
      capi: true
      '{{ .Values.cluster.capi_providers.infra_provider }}': true
      '{{ .Values.cluster.capi_providers.bootstrap_provider }}': true
      kyverno-policies: '{{ .Values.cluster.capi_providers.infra_provider | eq "capm3" }}'
      os-image-server: '{{ .Values.cluster.capi_providers.infra_provider | eq "capm3" }}'

  kyverno-policy-prevent-mgmt-cluster-delete:
    info:
      description: Kyverno policies to prevent deletion of critical resources for mgmt cluster
      internal: true
    enabled_conditions:
    - '{{ tuple . "kyverno" | include "unit-enabled"  }}'
    depends_on:
      kyverno: true
      capi: true
    unit_templates:
    - base-deps
    repo: sylva-core
    kustomization_spec:
      path: ./kustomize-units/kyverno-policies/prevent-mgmt-cluster-delete
      wait: true
      postBuild:
        substitute:
          CLUSTER_NAME: '{{ .Values.cluster.name }}'

  os-image-server:
    enabled: '{{ tuple . "metal3" | include "unit-enabled" }}'

  kubevirt:
    enabled: false

  kepler:
    enabled: false

  kubevirt-test-vms:
    enabled: false

  prometheus-flux:
    depends_on:
      monitoring-crd: true

  monitoring:
    depends_on:
      keycloak-oidc-external-secrets: true
      keycloak-add-realm-role: true
      grafana-init: true
    annotations:
      sylvactl/readyMessage: "Grafana UI can be reached at https://{{ .Values.external_hostnames.grafana }} ({{ .Values.external_hostnames.grafana }} must resolve to {{ .Values.display_external_ip }})"
    helmrelease_spec:
      values:
        grafana:
          envFromSecret: grafana-oidc
          grafana.ini:
            server:
              root_url: 'https://{{ .Values.external_hostnames.grafana }}'
            auth.anonymous:
              enabled: false
            auth.generic_oauth:
              enabled: true
              name: Keycloak-OAuth
              scopes: openid email profile offline_access roles
              email_attribute_path: email
              login_attribute_path: username
              name_attribute_path: full_name
              client_id: grafana
              auth_url: 'https://{{ .Values.external_hostnames.keycloak }}/realms/sylva/protocol/openid-connect/auth'
              token_url: 'https://{{ .Values.external_hostnames.keycloak }}/realms/sylva/protocol/openid-connect/token'
              api_url: 'https://{{ .Values.external_hostnames.keycloak }}/realms/sylva/protocol/openid-connect/userinfo'
              role_attribute_path: contains(roles[*], 'grafanaadmin') && 'Admin' || 'Viewer'
              allow_assign_grafana_admin: true
              groups_attribute_path: groups
              use_refresh_token: true
              signout_redirect_url: 'http://{{ .Values.external_hostnames.keycloak }}/realms/sylva/protocol/openid-connect/logout'
          extraSecretMounts:
            - name: grafana-tls
              mountPath: "/etc/ssl/certs"
              secretName: grafana-general-tls
          ingress:
            enabled: true
            hosts:
              - '{{ .Values.external_hostnames.grafana }}'
            tls:
              - secretName: grafana-general-tls
                hosts:
                  - '{{ .Values.external_hostnames.grafana }}'
        global:
          cattle:
            clusterId: local
            clusterName: local
    helm_secret_values:
      grafana:
        # https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
        additionalDataSources:
          - name: Thanos
            type: "prometheus"
            access: "proxy"
            url: "https://{{ .Values.external_hostnames.thanos }}"
            basicAuth: true
            basicAuthUser: "thanos-user"
            jsonData:
              tlsSkipVerify: true
              timeInterval: 60s
              prometheusVersion: "0.35.0"
              customQueryParameters: "deduplicate=1"
            secureJsonData:
              basicAuthPassword: '{{ .Values._internal.thanos_password }}'
            #isDefault: true
          - name: Loki
            type: "loki"
            access: "proxy"
            url: "https://{{ .Values.external_hostnames.loki }}"
            basicAuth: true
            basicAuthUser: "loki-user"
            jsonData:
              tlsSkipVerify: true
              httpHeaderName1: 'X-Scope-OrgID'
            secureJsonData:
              httpHeaderValue1: '{{ .Values.cluster.name }}'
              basicAuthPassword: '{{ .Values._internal.loki_password }}'

  logging:
    depends_on:
      loki: '{{ tuple . "loki" | include "unit-enabled" }}'

  snmp-exporter:
    enabled: '{{ tuple . "capm3" | include "unit-enabled" }}'

  harbor-init:
    depends_on:
      sylva-ca: true
      keycloak-resources: true
      kyverno: true
      vault: true
      vault-config-operator: true
      eso-secret-stores: true
      keycloak-add-client-scope: true

  harbor:
    helmrelease_spec:
      _postRenderers:
        - kustomize:
            patchesStrategicMerge:
              - kind: Deployment
                apiVersion: apps/v1
                metadata:
                  name: harbor-core
                spec:
                  template:
                    spec:
                      containers:
                        - name: core
                          env:
                            - name: CONFIG_OVERWRITE_JSON
                              valueFrom:
                                secretKeyRef:
                                  key: CONFIG_OVERWRITE_JSON
                                  name: "harbor-oidc"

  management-flag:
    info:
      internal: true
      description: dummy unit to identify management cluster
      details: >
        This unit will produce a configmap in management cluster that can be used by apply scripts
        to assert that they are properly targeting the management cluster
    enabled: true
    unit_templates:
    - dummy

keycloak:
  keycloak_expire_password_days: 30

cluster:
  prevent_deletion: true

_internal:
  mgmt_cluster: true
