apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: coredns
  namespace: kube-system
  behavior: replace
  options:
    disableNameSuffixHash: true
  files:
  - Corefile=workload-coredns.yaml
