#!/bin/sh

BASE_DIR="$(realpath $(dirname $0)/..)"

FOOTER='This PR has been generated by [Renovate Bot Sylva instance](https://gitlab.com/sylva-projects/sylva-elements/renovate).\n\n'
FOOTER="$FOOTER$(awk '/##.CI.configuration/{found=1}{sub("\\[.\\]","[ ]")} found' $BASE_DIR/.gitlab/merge_request_templates/Default.md)"

FOOTER="$FOOTER\n\n:gear: If no checkbox is checked, a default pipeline will be enabled (capm3, or capo if ~capo label is set)"

export FOOTER

yq -i '.prFooter = strenv(FOOTER)' $BASE_DIR/renovate.json
