apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# We need a configmap in the same namespace as sylva-units in order to ensure
# that helmReleases won't reconcile until the kustomization controlling it will
# have its dependencies satistfied

resources:
  - root-dependency-cm.yaml
