apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- create-namespace.yaml
- create-custom-pod.yaml
- litmus.yaml
- rbac.yaml
- experiment.yaml
- benchmarking.yaml
- report.yaml
