apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  name: nodes-provider-ids
  namespace: sylva-system
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: nodes-provider-id-blacklist
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      This policy tracks providerIDs that have been set to nodes in nodes-provider-ids ConfigMap
spec:
  background: true
  mutateExistingOnPolicyUpdate: true
  failurePolicy: ${FAILURE_POLICY:-Fail}
  rules:
  - name: generate-nodes-provider-ids-list
    skipBackgroundRequests: false
    match:
      any:
      - resources:
          kinds:
          - /v1/Node
    context:
    - name: providerID
      variable:
        value: "{{ request.object.spec.providerID || '' | split(@, '/') | [-1] }}"
    - name: blacklistedIDs
      apiCall:
        urlPath: "/api/v1/namespaces/sylva-system/configmaps/nodes-provider-ids"
        jmesPath: "data || `{}`"
    preconditions:
      all:
      - key: "{{ providerID }}"
        operator: NotEquals
        value: ""
      # Ensure that we won't overwrite creationTimestamp of a given providerID once it is set
      - key: "{{ lookup(blacklistedIDs, providerID) || '' }}"
        operator: Equals
        value: ""
    mutate:
      targets:
      - kind: ConfigMap
        apiVersion: v1
        name: nodes-provider-ids
        namespace: sylva-system
      patchStrategicMerge:
        data:
          "{{ providerID }}": "{{ request.object.metadata.creationTimestamp }}"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-node-provider-id-reuse
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      This policy prevents the creation of a node with a providerID that has already been used in the past
spec:
  background: false
  validationFailureAction: Enforce
  failurePolicy: ${FAILURE_POLICY:-Fail}
  rules:
  - name: prevent-node-provider-id-reuse
    match:
      any:
      - resources:
          kinds:
          - /v1/Node
          operations:
          - CREATE
          - UPDATE
    preconditions:
      all:
      - key: "{{ request.oldObject.spec.providerID || '' }}"
        operator: Equals
        value: ''
    context:
    - name: providerID
      variable:
        value: "{{ request.object.spec.providerID || '' | split(@, '/') | [-1] }}"
    - name: blacklistedIDs
      apiCall:
        urlPath: "/api/v1/namespaces/sylva-system/configmaps/nodes-provider-ids"
        jmesPath: "data || `{}` | keys(@)"
    validate:
      message: Check if node providerID has already been used
      deny:
        conditions:
          any:
          - key: "{{ blacklistedIDs | contains(@, '{{ providerID }}') }}"
            operator: Equals
            value: true
            message: Blocking node creation as there was already a node with providerID {{ providerID }}
---
apiVersion: kyverno.io/v2
kind: ClusterCleanupPolicy
metadata:
  name: node-cleanup-policy
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Delete node that would be re-created by kubelet after node deletion by capi.
    policies.kyverno.io/minversion: 1.12.0
spec:
  schedule: "*/1 * * * *"
  match:
    any:
    - resources:
        kinds:
          - v1/Node
  context:
  - name: blacklistedIDs
    apiCall:
      urlPath: "/api/v1/namespaces/sylva-system/configmaps/nodes-provider-ids"
      jmesPath: "data || `{}`"
  conditions:
    all:
    # the condition to delete a Node is if we have recorded in the "nodes-provider-ids", for the same providerID,
    # a creationTimestamp different than the one on the Node ; because this corresponds to an already
    # seen server/machine (same providerID) which has recreated a Node (different creationTimestamp)
    #
    # (the "|| target.metadata.creationTimestamp" ensures that for a Node which has just appeared
    # and which hasn't been tracked in nodes-provider-ids, we take the right decision - no deletion)
    - key: "{{ lookup(blacklistedIDs, target.spec.providerID || '' | split(@, '/') | [-1] ) || target.metadata.creationTimestamp }}"
      operator: NotEquals
      value: "{{ target.metadata.creationTimestamp }}"
