apiVersion: v1
data:
  _dummy_: keep this here so that this dict is never empty
kind: ConfigMap
metadata:
  name: nodes-provider-ids
  namespace: sylva-system
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: nodes-provider-id-blacklist
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      This policy tracks providerIDs that have been set to nodes in nodes-provider-ids ConfigMap
spec:
  background: false
  admission: true
  mutateExistingOnPolicyUpdate: true
  failurePolicy: Fail
  # we need to ensure that we never hit the webhook in the early phases of Node creation
  # since this policy is only meant to allow us to prevent Node recreation with an old providerID
  # we configure the webhook to only be called on an update that changes spec.unschedulable to true
  # (this is sufficient to ensure that it will be called when cordoning/draining the node)
  webhookConfiguration:
    matchConditions:
    - name: only-on-update-of-spec-unschedulable-to-true
      expression: >-
        object.?spec.unschedulable.orValue(false) == true
  rules:
  - name: generate-nodes-provider-ids-list
    skipBackgroundRequests: false
    match:
      any:
      - resources:
          kinds:
          - /v1/Node
    context:
    - name: providerID
      variable:
        value: "{{ request.object.spec.providerID || '' | split(@, '/') | [-1] }}"
    - name: blacklistedIDs
      apiCall:
        urlPath: "/api/v1/namespaces/sylva-system/configmaps/nodes-provider-ids"
        jmesPath: "data || `{}`"
    preconditions:
      all:
      - key: "{{ providerID }}"
        operator: NotEquals
        value: ""
      # Ensure that we won't overwrite creationTimestamp of a given providerID once it is set
      - key: "{{ lookup(blacklistedIDs, providerID) || '' }}"
        operator: Equals
        value: ""
    mutate:
      targets:
      - kind: ConfigMap
        apiVersion: v1
        name: nodes-provider-ids  # this ConfigMap is read by the prevent-node-provider-id-reuse ValidatingAdmissionPolicy
        namespace: sylva-system
      patchStrategicMerge:
        data:
          "{{ providerID }}": "{{ request.object.metadata.creationTimestamp }}"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: prevent-node-provider-id-reuse
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["nodes"]
  matchConditions:
    - name: node-has-providerID
      expression: object.spec.?providerID.orValue("") != ""
    - name: not-providerID-is-unchanged
      expression: >-
        ! (request.operation == "UPDATE" &&
           (oldObject.spec.?providerID == object.spec.?providerID)
          )
  paramKind:
    apiVersion: v1
    kind: ConfigMap  # the ValidatingAdmissionPolicyBinding will bind this to the nodes-provider-ids ConfigMap
  variables:
    - name: blacklistedProviderIDsShort
      expression: params.data  # this will be the 'data' of the 'nodes-provider-ids' ConfigMap
    - name: providerID
      expression: object.spec.?providerID.orValue("")
    - name: providerIDShort
      expression: variables.providerID.substring(variables.providerID.lastIndexOf("/")+1)
  validations:
    - expression: >-
        ! (variables.providerIDShort in variables.blacklistedProviderIDsShort)
      messageExpression: >-
        "node can't reuse an old providerID: " + variables.providerIDShort
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: prevent-node-provider-id-reuse
spec:
  policyName: prevent-node-provider-id-reuse
  validationActions: [Deny]
  paramRef:
    parameterNotFoundAction: Allow
    namespace: sylva-system
    name: nodes-provider-ids  # nodes-provider-ids ConfigMap (populated by nodes-provider-id-blacklist Kyverno policy)
