apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
<<<<<<< HEAD
            memory: 128Mi
=======
            memory: 64M
>>>>>>> 3ad86f351 (test)
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo:v1.4.0
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              bootcmd:
                - root=/dev/vda
              # Add other configurations as needed
