apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: multus-kubevirt-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: multus
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: second
            bridge: {}
        resources:
          requests:
            memory: 128M
      networks:
      - name: default
        pod: {}
      - name: second
        multus:
          networkName: my-bridge
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo:v1.3.1
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
