#!/bin/bash

# This script will extract the content of DESCRIPTION variable defined under .scenario_xxxx section in $SCENARIO_DEFINITION_FILE file
# Then it will update section defined in $SCENARIO_DESCRIPTION_SECTION in the $CI_README file
# The end of the section to replace is defined by the regex in the awk command


BASE_DIR="$(realpath $(dirname $0)/../../..)"
CI_README=$BASE_DIR/.gitlab/README.md
SCENARIO_DESCRIPTION_SECTION="#### Scenario description"
TMP_FILE=$(mktemp)

SCENARIO_DEFINITION_FILE=$BASE_DIR/.gitlab/ci/deployments-base.yml
SCENARIO_DESCRIPTION="\n"
SCENARIO_DESCRIPTION+=$(yq -r 'to_entries | map(select(.key | test("^\\.scenario_"))) | map("* `" + (.key | sub("^\\.scenario_"; "")) + "`: " + (.value.variables.DESCRIPTION // "No description")) | .[]' $SCENARIO_DEFINITION_FILE)
SCENARIO_DESCRIPTION+="\n"

awk -v scenario_description_section="$SCENARIO_DESCRIPTION_SECTION" \
    -v scenario_description="$SCENARIO_DESCRIPTION" \
    '$0 == scenario_description_section { print; print scenario_description; found=1; next } found && /^generated by / { found=0 } !found' \
    "$CI_README" > $TMP_FILE && mv $TMP_FILE $CI_README
