#!/bin/bash

# This script will extract the content of DESCRIPTION variable defined under each mgmt-* / wkld-* jobs in all files under CI_TESTS_FOLDER folder
# Then it will update section defined in $TESTS_DESCRIPTION_SECTION in the $TESTS_README file
# The end of the section to replace is defined by the regex in the awk command


BASE_DIR="$(realpath $(dirname $0)/../../..)"
CI_TESTS_FOLDER=$BASE_DIR/.gitlab/ci/tests/**/*.yml
TESTS_README=$BASE_DIR/.gitlab/ci/tests/README.md
TESTS_DESCRIPTION_SECTION="## Tests description"

TMP_FILE=$(mktemp)

TESTS_DESCRIPTION="\n"
TESTS_DESCRIPTION+="### Tests run on management cluster\n"
TESTS_DESCRIPTION+="\n"
TESTS_DESCRIPTION+="| Name | Description |\n"
TESTS_DESCRIPTION+="|------|-------------|\n"
TESTS_DESCRIPTION+=$(cat $CI_TESTS_FOLDER | grep -v '^--- *$' | yq -r 'to_entries | map(select(.key | test("^mgmt"))) | map("| `" + (.key) + "`|" + (.value.variables.DESCRIPTION // "No description") + "|") | .[]')
TESTS_DESCRIPTION+="\n\n"
TESTS_DESCRIPTION+="### Tests run on workload cluster"
TESTS_DESCRIPTION+="\n\n"
TESTS_DESCRIPTION+="| Name | Description |\n"
TESTS_DESCRIPTION+="|------|-------------|\n"
TESTS_DESCRIPTION+=$(cat $CI_TESTS_FOLDER | grep -v '^--- *$' | yq -r 'to_entries | map(select(.key | test("^wkld"))) | map("| `" + (.key) + "` | " + (.value.variables.DESCRIPTION // "No description") + " |") | .[]')
TESTS_DESCRIPTION+="\n"

awk -v tests_description_section="$TESTS_DESCRIPTION_SECTION" \
    -v tests_description="$TESTS_DESCRIPTION" \
    '$0 == tests_description_section { print; print tests_description; found=1; next } found && /^generated by / { found=0 } !found' \
    "$TESTS_README" > $TMP_FILE && mv $TMP_FILE $TESTS_README
