apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap-values
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sylva-units.labels" . | indent 4 }}
data:
  bootstrap-values: {{ .Files.Get "bootstrap.values.yaml" | toYaml | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: management-values
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sylva-units.labels" . | indent 4 }}
data:
  management-values: {{ .Files.Get "management.values.yaml" | toYaml | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-values
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sylva-units.labels" . | indent 4 }}
data:
  workload-values: {{ .Files.Get "workload-cluster.values.yaml" | toYaml | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: use-oci-artifacts-values
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sylva-units.labels" . | indent 4 }}
data:
  use-oci-artifacts-values: {{ .Files.Get "use-oci-artifacts.values.yaml" | toYaml | nindent 4 }}
