apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: deny-cabundle-changes
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ["apiextensions.k8s.io"]
        apiVersions: ["v1"]
        operations: ["UPDATE"]
        resources: ["customresourcedefinitions"]
  validations:
    # validation should accept the UPDATE if, either:
    # - the CRD cert isn't handled by cert-manager ('cert-manager.io/inject-ca-from' annotation absent)
    # - or caBundle is not changed
    # - or cert-manager is making the change
    - expression: |2
           ! ('cert-manager.io/inject-ca-from' in object.?metadata.annotations.orValue({}))
        || (   object.spec.?conversion.webhook.clientConfig.caBundle ==
            oldObject.spec.?conversion.webhook.clientConfig.caBundle)
        || (request.userInfo.username == 'system:serviceaccount:cert-manager:cert-manager-cainjector')
      message: "Modification or addition of caBundle in CRDs is only allowed by cert-manager"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: deny-cabundle-changes-binding
spec:
  policyName: deny-cabundle-changes
  validationActions: [Deny]
  matchResources:
    namespaceSelector: {}
    objectSelector: {}
