apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restart-${TENANT_NS}-tenant-on-cert-renewal
  namespace: ${TENANT_NS}
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/description: >-
      This policy monitors ${TENANT_NS} tenant certificate secrets and will update annotations
      to trigger pod rollouts when certificates are renewed.
spec:
  rules:
  - name: ${TENANT_NS}-tenant-restart
    match:
      any:
      - resources:
          kinds:
          - Secret
          names:
          - ${TENANT_NS}-internal-tls
    context:
    - name: minioTenantExists
      apiCall:
        urlPath: "/apis/minio.min.io/v2/namespaces/${TENANT_NS}/tenants/${TENANT_NAME}"
    preconditions:
      all:
      - key: "{{ minioTenantExists.metadata.name }}"
        operator: Equals
        value: "${TENANT_NAME}"
      - key: "{{ request.object.data != oldObject.data }}"
        operator: Equals
        value: true
    mutate:
      mutateExistingOnPolicyUpdate: true
      targets:
        - apiVersion: minio.min.io/v2
          kind: Tenant
          name: ${TENANT_NAME}
          namespace: ${TENANT_NS}
      patchesJson6902: |-
        - op: replace
          path: /spec/env/1/value
          value: "{{ request.object.data || '' | to_string(@) | sha256(@) | truncate(@,`12`) }}"
