---
apiVersion: v1
kind: Secret
metadata:
  name: flux-sources-pvc
  namespace: flux-system
immutable: true
stringData:
  CRYPTO_KEY_VALUE: ${VOLUME_ENCRYPTION_KEY}
  CRYPTO_KEY_PROVIDER: "secret"
  CRYPTO_KEY_CIPHER: "aes-xts-plain64"
  CRYPTO_KEY_HASH: "sha256"
  CRYPTO_KEY_SIZE: "256"
  CRYPTO_PBKDF: "argon2i"
