apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- restrict-nodeName-nodeSelector.yaml
- disable-automount-sa.yaml
- ensure-pdb-minreplicas.yaml
- always-allow-pdb-unhealthy-pod-eviction.yaml
- ensure-pdb-unhealthypodeviction.yaml
