apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-and-main-tag
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Disallow Latest and Main Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The ':latest' and ':main' tags are mutable and can lead to unexpected errors if the
      image changes. A best practice is to use an immutable tag that maps to
      a specific version of an application Pod. This policy validates that the image
      specifies a tag and that it is not called `latest` or 'main'.
    sylva.org/kyverno-exclude-kube-system: add-matchCondition
spec:
  validationFailureAction: Enforce
  background: false # validation is moved from Kyverno policy engine to kube-api server
  webhookConfiguration:
    matchConditions:
    - name: 'is-create-or-update'
      expression: 'request.operation in ["CREATE", "UPDATE"]'
    - name: 'missing-or-mutable-image-tag'
      expression: >-
          !(
              (has(object.spec.containers) ? object.spec.containers : []) +
              (has(object.spec.initContainers) ? object.spec.initContainers : []) +
              (has(object.spec.ephemeralContainers) ? object.spec.ephemeralContainers : []) +
              (has(object.spec.template) && has(object.spec.template.spec.containers) ? object.spec.template.spec.containers : []) +
              (has(object.spec.template) && has(object.spec.template.spec.initContainers) ? object.spec.template.spec.initContainers : []) +
              (has(object.spec.template) && has(object.spec.template.spec.ephemeralContainers) ? object.spec.template.spec.ephemeralContainers : []) +
              (has(object.spec.jobTemplate) && has(object.spec.jobTemplate.spec.template) &&
               has(object.spec.jobTemplate.spec.template.spec.containers) ? object.spec.jobTemplate.spec.template.spec.containers : []) +
              (has(object.spec.jobTemplate) && has(object.spec.jobTemplate.spec.template) &&
               has(object.spec.jobTemplate.spec.template.spec.initContainers) ? object.spec.jobTemplate.spec.template.spec.initContainers : []) +
              (has(object.spec.jobTemplate) && has(object.spec.jobTemplate.spec.template) &&
               has(object.spec.jobTemplate.spec.template.spec.ephemeralContainers) ? object.spec.jobTemplate.spec.template.spec.ephemeralContainers : [])
          ).all(container,
              container.image.contains(':') &&
              !(container.image.endsWith(':latest')) &&
              !(container.image.endsWith(':main'))
          )
  rules:
  - name: require-valid-image-tag
    match:
      resources:
        kinds:
        - Pod
        - Pod/ephemeralcontainers
        - ReplicationController
        - DaemonSet
        - Deployment
        - ReplicaSet
        - StatefulSet
        - CronJob
        - Job
    validate:
      message: An immutable image tag is required (a tag must be provided and different from "main" or "latest")
      deny: {}
