apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |
      - op: add
        path: /spec/bootstrap
        value:
          initdb:
            import:
              type: microservice
              databases:
                - gitea
              source:
                externalCluster: gitea-old-db
      - op: add
        path: /spec/externalClusters
        value:
          - name: gitea-old-db
            connectionParameters:
              host: postgres-primary
              user: postgres
              dbname: gitea
            password:
              name: postgres
              key: postgres-password
    target:
      kind: Cluster
      name: cnpg-gitea
      namespace: gitea

