apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: grafana-groups-client-scope
  annotations:
    crossplane.io/external-name: builtin-sylva-realm-role-offline-access
spec:
  forProvider:
    clientIdRef:
      name: grafana
      policy:
        resolution: Required
        resolve: Always
    defaultScopes:
      - roles
        #- offline_access
      - profile
      - groups
      - email
    realmId: sylva
  providerConfigRef:
    name: keycloak-provider-config
