apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: grafana
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: ${CLIENT_GRAFANA}
spec:
  forProvider:
    accessType: CONFIDENTIAL
    realmId: sylva
    useRefreshTokens: false
    clientId: grafana
    clientAuthenticatorType: client-secret
    directAccessGrantsEnabled: true
    enabled: true
    implicitFlowEnabled: false
    name: grafana
    validRedirectUris:
      - https://${GRAFANA_DNS}/login/generic_oauth
    standardFlowEnabled: true
    rootUrl: https://${GRAFANA_DNS}
    adminUrl: https://${GRAFANA_DNS}
    webOrigins:
      - https://${GRAFANA_DNS}
  providerConfigRef:
    name: keycloak-provider-config
  managementPolicies:
    - "*"
  writeConnectionSecretToRef:
    name: keycloak-client-secret-grafana-client
    namespace: crossplane-system
