---
include:
  - local: .gitlab/ci/templates-deployments.yml
  - local: .gitlab/ci/tests/**/*.yml
    rules:
      - if: $SKIP_TESTS != 'true'

workflow:
  name: "Deployment pipeline - $WORKFLOW_NAME"
  rules:
    - when: always

stages:
  - deploy
  - deployment-test
  - delete
  - cleanup

default:
  tags:
    - gitlab-org-docker
  image: $CI_IMAGE
  before_script:
    - !reference [.deployment-information]
  cache:
    - key: toolbox  # cache share by all jobs
      paths:
        - ./bin/

.deployment-information:
  - |
      echo -e "[\\e[1;94mEnvironment INFO\\e[0m]"
      echo "  CAPO_TAG = $CAPO_TAG"
      echo "  OCI_TAG = ${OCI_TAG:-'N/A'}"
      echo "  ENV_NAME = $ENV_NAME"
      echo "  KIND_CLUSTER_NAME = $KIND_CLUSTER_NAME"
      echo "  BOOTSTRAP_WATCH_TIMEOUT_MIN = $BOOTSTRAP_WATCH_TIMEOUT_MIN"
      echo -e "[\\e[1;94mCommon cluster INFO\\e[0m]"
      echo "  REMOTE_VALUES = ${REMOTE_VALUES:-'N/A'}"
      echo -e "[\\e[1;94mManagement cluster INFO\\e[0m]"
      echo "  MANAGEMENT_CLUSTER_NAME = $MANAGEMENT_CLUSTER_NAME"
      echo "  MGMT_ADDITIONAL_VALUES = ${MGMT_ADDITIONAL_VALUES:-'N/A'}"
      echo "  MGMT_INITIAL_ADDITIONAL_VALUES = ${MGMT_INITIAL_ADDITIONAL_VALUES:-'N/A'}"
      echo "  MGMT_UPDATE_ADDITIONAL_VALUES = ${MGMT_UPDATE_ADDITIONAL_VALUES:-'N/A'}"
      echo "  MGMT_INITIAL_REVISION = ${MGMT_INITIAL_REVISION:-'N/A'}"
      echo "  MGMT_UPDATE_REVISION = ${MGMT_UPDATE_REVISION:-'N/A'}"
      echo "  MGMT_WATCH_TIMEOUT_MIN = ${MGMT_WATCH_TIMEOUT_MIN}"
      echo "  APPLY_WATCH_TIMEOUT_MIN = ${APPLY_WATCH_TIMEOUT_MIN}"
      echo -e "[\\e[1;94mWorkload cluster INFO\\e[0m]"
      echo "  WORKLOAD_CLUSTER_NAME = $WORKLOAD_CLUSTER_NAME"
      echo "  WC_ADDITIONAL_VALUES = ${WC_ADDITIONAL_VALUES:-'N/A'}"
      echo "  WC_INITIAL_ADDITIONAL_VALUES = ${WC_INITIAL_ADDITIONAL_VALUES:-'N/A'}"
      echo "  WC_UPDATE_ADDITIONAL_VALUES = ${WC_UPDATE_ADDITIONAL_VALUES:-'N/A'}"
      echo "  WC_INITIAL_REVISION = ${WC_INITIAL_REVISION:-'N/A'}"
      echo "  WC_UPDATE_REVISION = ${WC_UPDATE_REVISION:-'N/A'}"
      echo "  APPLY_WC_WATCH_TIMEOUT_MIN = ${APPLY_WC_WATCH_TIMEOUT_MIN}"


# ----------------------------------------------------------
.test-tags:
  tags:
    - gitlab-org-docker
  dependencies: []

.rules:skip-if-only-deploy-mgmt:
  rules:
    - if: $ONLY_DEPLOY_MGMT
      when: never
    - when: on_success

.rules:run-if-only-deploy-mgmt:
  rules:
    - if: $ONLY_DEPLOY_MGMT

# ----------------------------------------------------------

deploy-management-cluster:
  needs:
    - job: create-runner
      optional: true
  extends:
    - .deploy-management

# ----------------------------------------------------------

deploy-workload-cluster:
  needs:
    - job: deploy-management-cluster
      artifacts: false
  extends:
    - .deploy-workload
    - .rules:skip-if-only-deploy-mgmt

# ----------------------------------------------------------

update-management-cluster:
  needs:
    - job: deploy-management-cluster
      artifacts: false
    - job: deploy-workload-cluster
      artifacts: false
  extends:
    - .update-management
    - .rules:skip-if-only-deploy-mgmt

# ----------------------------------------------------------

update-workload-cluster:
  needs:
    - job: deploy-workload-cluster
      artifacts: false
    - job: update-management-cluster
      artifacts: false
  extends:
    - .update-workload
    - .rules:skip-if-only-deploy-mgmt

# ----------------------------------------------------------

delete-workload-cluster:
  dependencies: []
  extends:
    - .delete-workload
  rules:
    - if: $ONLY_DEPLOY_MGMT
      when: never
    - when: always
