---
include:
  - local: .gitlab/ci/templates-deployments.yml
  - local: .gitlab/ci/tests/**/*.yml
    rules:
      - if: $SKIP_TESTS != 'true'

workflow:
  name: "Deployment pipeline - $WORKFLOW_NAME"
  rules:
    - when: always

stages:
  - deploy
  - deployment-test
  - delete
  - cleanup

variables:
  PREVIEW_MGMT_CLUSTER: "false"     # Controls whether management cluster preview
  DEPLOY_MGMT_CLUSTER: "true"       # Controls whether management cluster deploys
  DEPLOY_WORKLOAD_CLUSTER: "true"   # Controls whether workload cluster deploys
  UPDATE_MGMT_CLUSTER: "true"       # Controls whether management cluster updates
  UPDATE_WORKLOAD_CLUSTER: "true"   # Controls whether workload cluster updates
  DELETE_WORKLOAD_CLUSTER: "true"   # Controls whether workload cluster deletion


default:
  tags:
    - gitlab-org-docker
  image: $CI_IMAGE
  before_script:
    - !reference [.deployment-information]
  cache:
    - key: toolbox  # cache shared by all jobs
      paths:
        - ./bin/
  interruptible: true

# ----------------------------------------------------------
.test-tags:
  # Just to avoid test-tags to be empty in some cases which lead to syntax error
  variables:
# ----------------------------------------------------------

# Rules reusable in tests definition
.rules:need-management-cluster:
  rules:
    - if: $DEPLOY_MGMT_CLUSTER == "true"
      when: on_success

.rules:need-management-cluster-update:
  rules:
    - if: $DEPLOY_MGMT_CLUSTER == "true" && $UPDATE_MGMT_CLUSTER == "true"
      when: on_success

.rules:need-workload-cluster:
  rules:
    - if: $DEPLOY_WORKLOAD_CLUSTER == "true"
      when: on_success

.rules:need-workload-cluster-update:
  rules:
    - if: $DEPLOY_WORKLOAD_CLUSTER == "true" && $UPDATE_WORKLOAD_CLUSTER == "true"
      when: on_success

# ----------------------------------------------------------

preview-management-cluster:
  extends:
    - .preview-management
  rules:
    - if: $PREVIEW_MGMT_CLUSTER == "true"
      when: always

# ----------------------------------------------------------

deploy-management-cluster:
  needs:
    - job: create-runner-wait
      optional: true
  extends:
    - .deploy-management
    - .rules:need-management-cluster

# ----------------------------------------------------------

deploy-workload-cluster:
  needs:
    - job: deploy-management-cluster
      artifacts: false
      optional: true
  extends:
    - .deploy-workload
    - .rules:need-workload-cluster

# ----------------------------------------------------------

update-management-cluster:
  needs:
    - job: deploy-management-cluster
      artifacts: false
    - job: deploy-workload-cluster
      artifacts: false
      optional: true
  extends:
    - .update-management
    - .rules:need-management-cluster-update

# ----------------------------------------------------------

update-workload-cluster:
  needs:
    - job: deploy-workload-cluster
      artifacts: false
    - job: update-management-cluster
      artifacts: false
      optional: true
  extends:
    - .update-workload
    - .rules:need-workload-cluster-update

# ----------------------------------------------------------

delete-workload-cluster:
  dependencies: []
  extends:
    - .delete-workload
  rules:
    - if: $DEPLOY_WORKLOAD_CLUSTER == "true" && $DELETE_WORKLOAD_CLUSTER == "true"
      when: always

initialize-summary:
  extends: .summary
  stage: .post
  needs: []

update-summary:
  extends: .summary
  stage: .post
