apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-ha-values
  namespace: sylva-system
data:
  values.yaml: |
    replicas: 2
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: "true"
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
      selector:
        matchLabels:
          app: rke2-metrics-server
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: rke2-metrics-server
            namespaces:
              - kube-system
            topologyKey: kubernetes.io/hostname

