apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: metallb-resources-annotations
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
    policies.kyverno.io/title: Update metallb resources annotations and labels
    policies.kyverno.io/description: >-
      Updates RKE2 deployed metallb resources annotations and labels to be imported in helm
spec:
  background: true
  webhookTimeoutSeconds: 30
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: update-annotations
      match:
        any:
        - resources:
            kinds:
              - IPAddressPool
              - L2Advertisement
              - BGPPeer
              - BGPAdvertisement
            namespaces:
              - metallb-system
      mutate:
        targets:
          - apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            name: '{{ request.object.metadata.name }}'
          - apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            name: '{{ request.object.metadata.name }}'
          - apiVersion: metallb.io/v1beta2
            kind: BGPPeer
            name: '{{ request.object.metadata.name }}'
          - apiVersion: metallb.io/v1beta1
            kind: BGPAdvertisement
            name: '{{ request.object.metadata.name }}'
        patchStrategicMerge:
          metadata:
            labels:
              app.kubernetes.io/managed-by: Helm
            annotations:
              meta.helm.sh/release-name: metallb-resources
              meta.helm.sh/release-namespace: metallb-system
